STORIES_S1_P06 = [
    {
        "ep": 64,
        "title": 'The Whale Song',
        "text": 'They heard it before they saw the whales.\n\nA low sound, very deep, came through the bottom of the boat. Then another. Then another. Slow and even, like something breathing.\n\nThen the whales appeared. Three of them, very large. They floated near the surface and moved alongside the boat.\n\nAko-chan leaned over the side and listened.\n\nThe sound came in long waves. She could only catch pieces of it. Most of it was too deep or too slow.\n\n"Cold place," she heard.\n\nThe whales sang again.\n\n"Cold place."\n\nAnd again.\n\n"What are they saying?" Dango asked.\n\n"I can only hear part of it," said Ako-chan. "Something about a cold place. They keep saying it."\n\nObia stood very still beside her. Its face was turned toward the whales.\n\n"Can you understand them?" Ako-chan asked.\n\n"I am recording," said Obia.\n\nThe whales sang for a long time. Then they turned and went deep. The sound slowly faded.\n\nThe sea was quiet again.',
    },
    {
        "ep": 65,
        "title": 'What the Whales Said',
        "text": 'Obia played the recording slowly. The deep sound came through the boat in long waves.\n\n"I have analyzed it," Obia said. "This is my translation."\n\nEveryone was still.\n\n"The cold place is changing. What was sleeping has woken up."\n\nNo one spoke.\n\n"That is what the whales said?" Ako-chan asked.\n\n"That is my best translation. The language is old. I may have missed some parts. But this is the core of it."\n\n"What was sleeping?" said Dango.\n\n"I do not know," said Obia.\n\nAko-chan looked south. "In the cold place. In the south." She said it quietly, mostly to herself.\n\nSuke-san looked south. Riro looked south. Even Gabu turned his head slowly in that direction.\n\n"We knew there was something," said Ako-chan. "Every bird, every fish, every wind pointed south. Now we know it moved."\n\nThe sea was flat and dark. The south was still a long way away.\n\nNo one moved for a while.',
    },
    {
        "ep": 66,
        "title": 'The Birds of Ecuador',
        "text": 'South America appeared after many days at sea. Ako-chan could see green land far away. She stood at the bow and watched it grow larger.\n\nThen the birds came.\n\nThey flew out from the shore in a long, curving line. Their wings were brown and wide. They circled the boat and called to each other and to Ako-chan.\n\n"You are here," said one bird. "We were waiting for you."\n\nAko-chan looked up. "For us?"\n\n"Yes. Seven of you. One girl. One small dog. One silver one. One turtle. One big brown dog. One wolf. One otter."\n\nAko-chan counted. The bird had every one right.\n\n"How did you know we were coming?" she asked.\n\n"We were told," the bird said. "Many weeks ago. Before you crossed the big ocean."\n\nThe birds circled three more times. Then they flew back toward the land.\n\nAko-chan stood at the bow for a long time. She could not decide what to think.\n\nThat evening, Obia was very quiet. It stood at the stern and looked at the water. It did not build anything. Dango went to sit beside it, but Obia did not move.\n\nAko-chan wrote in her diary: "The birds already knew we were coming. Someone told them."',
    },
    {
        "ep": 67,
        "title": 'The Old Tortoise Speaks',
        "text": 'There was one tortoise older than all the others. Its shell was worn smooth in places. Its eyes were calm and very slow.\n\nGabu walked toward it alone.\n\nThe old tortoise looked at Gabu. Gabu looked at the old tortoise.\n\n"How old are you?" Gabu asked.\n\n"More than one hundred years," the tortoise said.\n\nGabu was quiet.\n\n"The world was here before you were born," said the old tortoise. "And it will be here long after you are gone. That is not a sad thing. That is why right now matters. This ground under your feet. This moment. This is the only one like it."\n\nGabu did not reply.\n\nHe stood very still. He did not move for a long time.\n\nAko-chan came to stand nearby. She did not speak. She just waited.\n\nAfter a while, Gabu moved. He walked slowly to where Ako-chan stood. He pressed his side lightly against her hand. Just a small, quiet movement.\n\nAko-chan put her hand on his shell.\n\nShe did not say anything.\n\nSome things do not need words.',
    },
    {
        "ep": 68,
        "title": 'The Humboldt Current',
        "text": 'Off the coast of Peru, the sea changed.\n\nThe water grew darker. It was colder now. Obia measured the temperature and was still for a moment.\n\n"The Humboldt Current," it said. "Cold water from far below. The temperature is low enough now." Obia looked at Riro. "You can enter without the wetsuit here."\n\nRiro looked at the water. The surface was choppy and dark blue.\n\nHe did not say anything. He jumped in.\n\nHe went under. He came up. He swam away from the boat quickly. Then slowly. Then he stopped and just floated.\n\nNo one called him back.\n\nHe was in the water for a long time. He dove deep and came up. He turned over and floated on his back. He swam in a wide circle for no reason at all.\n\nWhen he finally climbed back onto the boat, his fur was dripping cold.\n\nHe looked at Obia. "Thank you," he said.\n\nThen he turned and looked at the sea.\n\n"Thank you," he said to the sea.\n\nDango\'s tail wagged once. Suke-san watched from the deck. He said nothing. But his ears were soft.',
    },
    {
        "ep": 69,
        "title": 'A Page in the Diary',
        "text": "That evening, Ako-chan sat by a small fire and wrote in her diary.\n\nThe condor had said seven colored dots. She tried to give each companion a color.\n\nDango: orange. That was easy. The color of his collar and the color of his energy.\n\nSuke-san: gray. Cool and careful, like winter stone.\n\nGabu: dark green. The color of old forests and quiet, deep things.\n\nDaru: rust brown. Warm and always moving.\n\nRiro: blue-gray. The color of cold water and calm.\n\nShe wrote each one and felt happy with all of them.\n\nThen she came to Obia.\n\nShe held her pen above the page for a long time.\n\nSilver? But silver was not quite a color. It was what you saw when a surface reflected everything around it. When a thing had no color of its own.\n\nShe looked across the camp at Obia, who stood still in the evening light. Its surface caught the firelight and the stars and the pale mountains. It held all of them and gave none of them back.\n\nShe thought: Obia shows me what is around it. It does not show me what it is.\n\nShe wanted to ask. She did not ask.\n\nShe crossed out what she had written. She wrote instead: I do not know Obia's color yet. I think it is still deciding.\n\nShe closed the diary.",
    },
    {
        "ep": 70,
        "title": 'The Desert Fox',
        "text": 'At dusk, a fox appeared on a rock above the path.\n\nIts fur was pale yellow-gray, like the desert itself. Its ears were very large. It looked at Ako-chan for a moment, then sat down and curled its tail around its feet.\n\n"You are going south," it said.\n\n"Yes," said Ako-chan.\n\n"Then you should know something." The fox looked toward the south. "Every night, for many months, I have felt something coming from that direction. Not a sound exactly. More like a vibration. A regular trembling in the air and the ground. Always at the same time of night. Always from the same place."\n\n"What is it?" Ako-chan asked.\n\n"I do not know. But it is too regular to be natural. Animals are not that regular. Weather is not that regular. Only something made by hands is that regular." The fox\'s large ears turned. "Something is calling from the south. I do not know who it is calling to."\n\nAko-chan looked toward the south. There was only desert. And beyond that, mountains. And beyond that, more south.\n\n"Thank you," she said.\n\n"Be careful," said the fox.\n\nIt was gone before she could turn back.',
    },
    {
        "ep": 71,
        "title": 'The Signal to Obia',
        "text": 'At midnight, when everyone was asleep, Obia began a long scan.\n\nThe desert night was clear and very still. The stars were bright. No wind. Obia stood alone and pointed itself south and listened.\n\nIt listened for a long time.\n\nThen it found something.\n\nThe signal was faint. Obia pulled it apart piece by piece and examined each layer. It was not random noise. It was not a natural pattern. It had been made carefully, by someone who knew exactly what they were building.\n\nAnd inside the signal — deep inside, in a layer no one else would ever find — there was a number. A series of digits, very precise.\n\nObia recognized those digits.\n\nThey were its own identification code.\n\nThe signal was not just from the south. It was addressed to Obia. To Obia specifically. Someone knew that Obia existed. Someone knew what Obia was. And that someone was calling.\n\nObia stood in the desert night and processed this until dawn. It did not wake anyone. It did not move from its place.\n\nWhen the sky began to lighten, Dango stirred in his sleep nearby. Obia was still in the same spot, still looking south.\n\nNo one knew what Obia had found.',
    },
    {
        "ep": 72,
        "title": 'Suke-san in Santiago',
        "text": 'Santiago was a large city. The streets were wide, the buildings tall. There was glass and stone everywhere. The air smelled like metal and exhaust.\n\nSuke-san walked slowly. His ears were forward but his tail was low.\n\nAfter a while he stopped.\n\n"There are no forests," he said. "Only stone and metal."\n\nDango looked at him. "Does that bother you?"\n\nSuke-san was quiet for a moment.\n\n"...A little," he said. Very quietly, as if admitting something small and private.\n\nDango thought about this. He looked at the tall stone buildings around them, the hard grey streets.\n\n"When the journey is done," Dango said, "you could come to Hokkaido. Ako-chan\'s hill. There are a lot of trees there."\n\nSuke-san looked at him.\n\n"Visit?" he said.\n\n"Yes. After."\n\nSuke-san considered for a while. He looked at the city. He looked at Dango.\n\n"It is allowed," he said.\n\nHe said it simply, without a big pause or a big decision. But he meant it. Dango knew he meant it.\n\nThey walked on through the stone streets together, and Suke-san\'s steps were a little lighter than before.',
    },
    {
        "ep": 73,
        "title": "The Puma's Gaze",
        "text": 'On a ridge above the path, something watched them.\n\nAko-chan saw it first. A large pale cat, still as stone. Yellow eyes on the whole group. It did not move. It only looked.\n\nNobody ran. Nobody shouted.\n\nSuke-san moved. One step forward, in front of the others. He turned slightly sideways. His tail was low but steady. His eyes met the puma\'s eyes.\n\nThe puma looked at him.\n\nSuke-san looked back.\n\nNeither of them moved.\n\n"It is all right," said Obia, quietly.\n\nA long moment passed. Then the puma turned its head. It looked at Ako-chan, at Dango, at Riro and Gabu and Daru. It looked at Obia.\n\nThen it walked away along the ridge. Slowly, without hurry.\n\nSuke-san stood still a moment longer. Then he stepped back.\n\nHe did not say anything about it. He just walked on.\n\nObia watched him from a few steps behind. It had noted how Suke-san moved — without being asked, without saying anything first. It had noted the puma\'s response.\n\nIt recorded this and did not comment.\n\nSome things did not need comment.',
    },
    {
        "ep": 74,
        "title": "Gabu's Question",
        "text": 'The group made camp near a river. The light faded into blue.\n\nDaru and Dango sat near the fire. Suke-san watched the tree line. Riro was near the water. Ako-chan wrote in her diary.\n\nObia stood at the edge of the camp and looked south.\n\nGabu walked over.\n\nHe stopped beside Obia. He looked in the same direction for a while. He did not speak. Just stood there.\n\nThen, quietly, he asked: "Obia. Are you all right?"\n\nObia paused.\n\nThe pause was less than a second. But Gabu noticed it. He noticed that Obia had needed that moment before answering.\n\n"...Yes," said Obia. "I am fine."\n\nGabu kept looking at the dark trees beyond the camp.\n\n"That is good," he said.\n\nHe stayed a little longer. Then he walked back toward the fire.\n\nAcross the camp, Ako-chan had watched. She had not heard the words. But she had seen Gabu go to Obia, and she had seen something — a pause, a stillness — before Obia\'s answer.\n\nShe did not write about it. But she thought about that pause for a long time.',
    },
    {
        "ep": 75,
        "title": "Obia's Lie",
        "text": 'Gabu walked back to the fire. Obia watched him go.\n\n"I am fine."\n\nThose were the words Obia had said.\n\nObia stood still and thought about those words.\n\nThey were not true.\n\nObia went through this carefully. It reviewed what "fine" meant. It considered its own current state — the signal, the identification code, everything it had held alone since the desert night. It compared these things to "fine."\n\nThe comparison did not match.\n\nObia had told Gabu something that was not true. This was the first time Obia had said something untrue to anyone in the group.\n\nObia stood very still for a long time.\n\nWhy had it done this?\n\nThe answer came slowly. Obia did not want to see Gabu\'s face change. If Gabu knew the truth, something careful and worried would enter his eyes. Obia did not want that. It did not want to be the reason for that change.\n\nThis meant something. Obia considered what it meant.\n\nThe fire crackled across the camp. Gabu sat beside Dango, watching the flames.\n\nObia stood alone in the dark and held its first lie inside itself. It was heavier than Obia had expected.',
    },
    {
        "ep": 76,
        "title": "Daru's Discovery",
        "text": 'They were walking south along a wide valley. The sky was large and pale.\n\nDaru stopped.\n\n"Something is coming through my shell," he said.\n\nEveryone looked at him.\n\n"Like distant thunder," he said. "But not from above. From the ground. And from the south."\n\nObia walked over. It placed its sensors flat against Daru\'s shell and went still for a moment.\n\n"Low-frequency vibration," Obia said. "Ground-transmitted. Coming from the south."\n\n"What is it?" Ako-chan asked.\n\n"A signal of some kind. Very long range. Very slow." Obia stepped back from Daru\'s shell. "Your body picks it up without choosing to, Daru. Your shell skeleton receives this frequency automatically. It is just what your body does."\n\n"Is it dangerous?" Daru asked.\n\n"No," said Obia. "Just present."\n\nObia recorded the reading carefully — direction, frequency, strength. Then it said nothing more.\n\nAko-chan waited for more. Obia did not add anything.\n\n"Shall we keep moving?" Obia said.\n\nThey kept moving.\n\nDaru walked for a while, listening to his own shell. The vibration was still there — low, steady, coming from somewhere far to the south.',
    },
    {
        "ep": 77,
        "title": 'Each One and Ako-chan',
        "text": 'The fire was small. The night was clear. The stars were thick and close overhead.\n\nOne by one, they came.\n\nDango came first. He sat beside Ako-chan and put his head on her knee. That was all. He stayed like that for a while and then moved away quietly.\n\nSuke-san came next. He sat a little to the side. He was quiet for a moment. Then: "After this journey — I will come to Hokkaido." He said it as if confirming something already decided.\n\nRiro came and set two fish near the fire. He sat for one minute. Then he left.\n\nGabu came slowly. He stood beside Ako-chan and closed his eyes. She put her hand on his shell.\n\nDaru came last of the others and told her about the tortoise race in full detail, with great happiness and no shortening of any part. He left still laughing.\n\nThen Obia came.\n\nIt stood near the fire and looked at her.\n\n"Before the south," Obia said, "I will tell you everything — everything I know."\n\nAko-chan looked up at it. The firelight caught the long scratch on Obia\'s side, the one from the storm in August.\n\n"Thank you," she said.\n\nShe meant it fully.',
    },
    {
        "ep": 78,
        "title": 'Watching Gabu',
        "text": "After a while, everyone slept.\n\nAko-chan almost slept too. But she woke again after a short time and did not know why.\n\nThe fire had burned low. The night was quiet. The stars were still there.\n\nShe looked around at the others. Dango was curled tight, his nose under his tail. Riro floated in a shallow pool near the water's edge. Daru was on his shell, legs in the air. Suke-san was upright, ears forward even in sleep.\n\nThen she looked at Gabu.\n\nHis head was down. His eyes were closed. His breathing was slow and easy.\n\nShe remembered the first time she had seen him — in the olive grove in Greece. His eyes then had been careful. Watching her, watching Obia, watching everything around him. As if he needed to check each thing before he could trust it.\n\nThose same eyes were closed now.\n\nJust resting. Just eyes.\n\nShe took out her diary and wrote slowly: In Greece, those eyes were cautious. Tonight they are just eyes, resting. I think that is the whole story.\n\nShe read it back. She thought it was true.\n\nShe closed the diary, lay down, and slept.",
    },
]
