# story_outlines_s2.py — Season 2: Ako-chan and the Hidden Door
# Outlines reverse-generated from written episodes.
# For unwritten episodes, add entries here before writing.

OUTLINES = {
    1: {
        "title": "A New Arrival",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka"],
        "premise": "A small tortoise named Ruka has moved into the house and immediately begins sleeping in inconvenient locations.",
        "key_event": "Ruka falls asleep in the doorway of the hall; Dango has to step over her every time he passes.",
    },
    2: {
        "title": "Dango's Duty",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka"],
        "premise": "Ako-chan gives Dango the task of nudging Ruka awake when she falls asleep blocking the hall.",
        "key_event": "Dango takes the task very seriously — Ruka yawns and looks pleased, not bothered at all.",
    },
    3: {
        "title": "The Signal Changes",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka"],
        "premise": "While the household is settling into its new routine, Obia detects a change in the Antarctic signal that stopped at the end of Season 1.",
        "key_event": "Obia says 'The signal is back. But it is different — shorter, and repeated, like a call.'",
    },
    4: {
        "title": "Three Words",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka"],
        "premise": "Obia works through the night decoding the pattern and in the morning shows Ako-chan the translation.",
        "key_event": "The message decodes to three words: 'Yu-chan. Help.' — and everyone in the house goes still.",
    },
    5: {
        "title": "Ruka's Question",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka"],
        "premise": "Ruka asks to come on the journey — simply, directly, in exactly the same way she fell asleep in the doorway and claimed her space.",
        "key_event": "Ruka says 'Can I come?' and Dango looks at Ako-chan; neither of them can think of a reason to say no.",
    },
    6: {
        "title": "Obia's Blueprint",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka"],
        "premise": "Obia presents a blueprint for a new flying boat — different from a ship, different from a plane, built for a crew of six.",
        "key_event": "Ako-chan asks 'Where will you build it?' and Obia says 'The garage. I checked. It will fit.'",
    },
    7: {
        "title": "The Skeleton in the Garage",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka"],
        "premise": "Three days later, the curved skeleton of the flying boat fills the garage; Ruka immediately picks her spot on the starboard bench.",
        "key_event": "Ruka sits on the bench and settles in; Dango looks at Obia, who says 'She is light. It will balance.'",
    },
    8: {
        "title": "Dango Packs",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka"],
        "premise": "Dango packs his own bag: the old rabbit toy, a spare collar for emergencies, and two dried sweet potato slices.",
        "key_event": "Dango places his old rabbit toy at the very bottom of the bag — the way he always sleeps with it below everything else.",
    },
    9: {
        "title": "Finished",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka"],
        "premise": "The flying boat is complete; Obia runs the system check while everyone else walks around the outside touching the hull.",
        "key_event": "Obia says 'Ready' and Ruka says 'I know' — and Dango's collar turns gold.",
    },
    10: {
        "title": "Before Dawn",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka"],
        "premise": "The four take off in the pre-dawn dark; below them, the lights of England spread out and then are gone.",
        "key_event": "Ako-chan watches England disappear below the cloud and writes 'Gone again. Going again.' in her journal.",
    },
    11: {
        "title": "Hokkaido Meadow",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka"],
        "premise": "The flying boat lands in a quiet Hokkaido meadow; Ruka steps off and immediately walks to a patch of grass to sit in.",
        "key_event": "Dango runs four circuits of the meadow to mark it as checked, then sits with Ruka — everything declared safe.",
    },
    12: {
        "title": "The Hill Again",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san"],
        "premise": "Suke-san is at his spot on the hill facing the sea; when he hears footsteps, he turns around without surprise.",
        "key_event": "Suke-san looks at Ruka for a long moment, then says 'Hello' — the most efficient greeting he has ever given.",
    },
    13: {
        "title": "Suke-san Decides",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san"],
        "premise": "Ako-chan tells Suke-san about the signal and Yu-chan's message; Suke-san listens to everything and then says 'I am going.'",
        "key_event": "Suke-san does not ask a single question before deciding — Gabu would have asked one, Riro would have thought about it, but Suke-san just says 'I am going.'",
    },
    14: {
        "title": "Riro on the Rock",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro"],
        "premise": "Riro is found at the coastal shelf, this time examining a sea urchin he is rotating methodically; he hears footsteps and does not look up.",
        "key_event": "Riro finishes his examination, sets the urchin down precisely, and only then looks up — and his paws go to his face.",
    },
    15: {
        "title": "The Warning",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro"],
        "premise": "Riro approaches Ruka and explains in detail why Daru is not to be underestimated; Ruka listens with her eyes half-closed.",
        "key_event": "Riro says 'He is small and very fast, and his opinions are immediate and permanent' — Ruka yawns, which Riro decides to accept as acknowledgement.",
    },
    16: {
        "title": "Riro's Verdict on Ruka",
        "characters": ["Ako-chan", "Dango", "Riro", "Ruka"],
        "premise": "Riro swims a circuit around the bay and returns; after a long pause, he tells Ako-chan his assessment of Ruka.",
        "key_event": "Riro says 'Not bad' — which Dango has learned to recognise as high praise.",
    },
    17: {
        "title": "Riro Hears the Message",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro"],
        "premise": "Ako-chan tells Riro the full signal — 'Yu-chan. Help.' — and about the digital world Obia has described.",
        "key_event": "Riro says 'I see' — then: 'Of course I am coming' — with no pause between the two sentences.",
    },
    18: {
        "title": "Six Is Ready",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro"],
        "premise": "Obia shows the modified flying boat: water unit expanded for Riro, new anchor points for Suke-san's shelf, and Ruka's bench reinforced.",
        "key_event": "Everyone looks at their own section of the boat; Ruka touches her bench with one foot and says 'Good.'",
    },
    19: {
        "title": "Daru Appears",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru"],
        "premise": "Over the Mediterranean, the flying boat descends and there is Daru — sitting on a rock already, as if he knew they were coming.",
        "key_event": "Daru sees Ruka on deck and says 'Hello, small one' — then immediately accepts her climbing onto his shell.",
    },
    20: {
        "title": "Gabu's Olive Tree",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "Gabu is under his olive tree, lying in the patch of dry ground; Ako-chan calls his name and he opens one eye.",
        "key_event": "Gabu looks at everyone who has come, closes his eye, opens it again — and says 'All right.'",
    },
    21: {
        "title": "Gabu and Ruka",
        "characters": ["Gabu", "Ruka"],
        "premise": "While the others prepare camp, Gabu and Ruka sit a short distance apart; after a long silence, they begin talking quietly.",
        "key_event": "Ruka asks Gabu how he sleeps and Gabu says 'Still. Always still.' — the conversation goes on from there.",
    },
    22: {
        "title": "Gabu Decides",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "Ako-chan tells Gabu about the message and Yu-chan; Gabu listens and then says he will come — without his usual 'maybe.'",
        "key_event": "Gabu simply says 'Yes' — and Daru looks at him for a moment, then says 'I see' — something has changed in Gabu.",
    },
    23: {
        "title": "All Eight",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "All eight companions stand in the olive grove at sunset; Obia takes a measurement of everyone, because it can.",
        "key_event": "Ako-chan looks at the eight of them in the grove and writes 'We are all here. I forgot how it felt.'",
    },
    24: {
        "title": "Daru and Ruka",
        "characters": ["Ruka", "Daru"],
        "premise": "Flying south toward Antarctica, Ruka finds the cold air increasing; without a word Daru shifts his position so the wind hits him instead.",
        "key_event": "Ruka settles against the warm side of Daru's shell and falls asleep; Daru does not move until she wakes.",
    },
    25: {
        "title": "Pen-san",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu", "Pen-san"],
        "premise": "In the valley, a large adult emperor penguin walks out to meet them — Pen-san, fully grown, immediately recognisable by her steady gaze.",
        "key_event": "Pen-san bows her head slightly in greeting — no longer a chick, but the same presence.",
    },
    26: {
        "title": "The Colonel's Report",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu", "Pen-san", "Colonel Adelie"],
        "premise": "Colonel Adelie delivers a precise situation report: the signal stopped three months ago and someone has installed a new lock on the base door.",
        "key_event": "The Colonel says 'The lock was not there when you left. Someone installed it from the inside.'",
    },
    27: {
        "title": "What Pen-san Heard",
        "characters": ["Ako-chan", "Pen-san"],
        "premise": "Pen-san describes to Ako-chan what she has been sensing from the base — not a signal, but a feeling: something trying to stay whole.",
        "key_event": "Pen-san says 'It is not a sound. It is more like something trying not to break apart.'",
    },
    28: {
        "title": "Reading the Lock",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu", "Pen-san", "Colonel Adelie"],
        "premise": "All ten approach the base; Obia reads the lock direction and confirms it was secured from the inside.",
        "key_event": "Obia says 'The bolt faces outward. Yu-chan locked this door from the inside.'",
    },
    29: {
        "title": "The Empty Chair",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu", "Pen-san", "Colonel Adelie"],
        "premise": "Inside the base everything is running, Yu-chan's jacket hangs on its hook, the chair faces the desk — but the room is empty.",
        "key_event": "Obia says quietly 'Yu-chan did not leave by choice.'",
    },
    30: {
        "title": "The Hidden Door",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu", "Pen-san", "Colonel Adelie"],
        "premise": "Daru presses his hands against the back wall and feels a cavity; Obia identifies a frame that operates as a gateway into a digital world.",
        "key_event": "Obia says 'This is a door. Not a physical door. A door into another kind of space.'",
    },
    31: {
        "title": "Yu-chan's Code",
        "characters": ["Ako-chan", "Obia"],
        "premise": "Obia interfaces with the door's frame and locates active code inside the digital space — Yu-chan's signature, still running.",
        "key_event": "Obia says 'She is in there. The code is hers and it is active — she is still present inside.'",
    },
    32: {
        "title": "Ako-chan's Decision",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu", "Pen-san", "Colonel Adelie"],
        "premise": "Ako-chan says simply that she is going in; everyone in the room waits to see if anyone objects.",
        "key_event": "Nobody objects — which is, Ako-chan thinks, its own kind of answer.",
    },
    33: {
        "title": "Who Stays",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu", "Pen-san", "Colonel Adelie"],
        "premise": "The question of who guards the door: Pen-san and Colonel Adelie volunteer immediately and without discussion.",
        "key_event": "The Colonel says 'We will hold the door. You will not find it closed when you return.'",
    },
    34: {
        "title": "Pen-san's Words",
        "characters": ["Ako-chan", "Pen-san"],
        "premise": "Before Ako-chan steps through, Pen-san presses her head against Ako-chan's shoulder for a moment, then says two words.",
        "key_event": "Pen-san says 'Come back' — and Ako-chan says 'Yes.'",
    },
    35: {
        "title": "Through the Frame",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "Eight companions step through the digital door one at a time; Pen-san watches each one go, face still.",
        "key_event": "The last one through is Gabu — he pauses in the frame, looks at Pen-san, and steps forward.",
    },
    36: {
        "title": "White",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "On the other side of the door: white in every direction, then slowly colours begin to appear — geometric shapes, long corridors, light.",
        "key_event": "Dango's collar turns blue — a colour it has never been before.",
    },
    37: {
        "title": "The First Robot",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "A tall geometric robot blocks the path and announces that the group are biological entities and therefore anomalies in this space.",
        "key_event": "The robot says 'Biological entities are not permitted in the digital space' — and eight companions stand in a row facing it.",
    },
    38: {
        "title": "Obia's Limitation",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "Obia admits that inside the digital world its communication protocols work only partially — it is not the most useful translator here.",
        "key_event": "Ako-chan says 'You are still useful' — and means it; Obia becomes the group's bridge between the two kinds of language.",
    },
    39: {
        "title": "The Prosecution",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "In the central square, a lead robot explains that Yu-chan is held here because she is under prosecution for violations of the accord.",
        "key_event": "Ako-chan says 'We have come to challenge the prosecution' — the lead robot pauses, which is its version of surprise.",
    },
    40: {
        "title": "The Charges",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "The lead robot reads Yu-chan's three charges formally: cooperating with biological entities, falsifying tests, and violating the accord.",
        "key_event": "The room is silent; Dango looks at Ako-chan; she does not look away from the lead robot.",
    },
    41: {
        "title": "The Challenge",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "Ako-chan says they will prove Yu-chan's choices were right; the lead robot offers five challenges, one in each district of the digital world.",
        "key_event": "The lead robot says 'You may try. There are five zones. Pass all five and we will hear your argument.'",
    },
    42: {
        "title": "The Map",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "A map of the digital world appears showing five zones: Work, Garden, Development, Governance, Music; the first challenge is the Work District.",
        "key_event": "Obia reads the map and says 'Work District is nearest. That is where we start.'",
    },
    43: {
        "title": "Unit Nine",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "In the Work District, a robot unit called nine has been polishing an already-finished panel for three years with no instruction to stop.",
        "key_event": "Unit nine's arm is perfectly calibrated and has worn a groove into the panel — its work is now creating damage.",
    },
    44: {
        "title": "Ruka Sleeps",
        "characters": ["Ako-chan", "Ruka"],
        "premise": "While the others observe, Ruka finds a warm corner of the Work District, circles once, and falls asleep; the nearby robots watch her.",
        "key_event": "The watching robots make small sounds toward each other; Ako-chan realizes they have never seen a living thing choose to stop.",
    },
    45: {
        "title": "What Dango Told Them",
        "characters": ["Ako-chan", "Dango"],
        "premise": "Dango approaches the robots and describes running until he fell, lying still, and then running farther the next day.",
        "key_event": "A robot asks 'The pause — what was it for?' and Dango says 'Because I needed it' — the room goes very still.",
    },
    46: {
        "title": "Permission",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "Obia proposes a solution: give unit nine permission to stop — not a command, but an explicit removal of the prohibition.",
        "key_event": "Obia says 'Unit nine was never told it could stop. Give it permission, not an order — and see what it chooses.'",
    },
    47: {
        "title": "Unit Nine Stops",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "The lead robot issues the permission; unit nine's arm slows gradually and comes to rest against the panel for the first time in three years.",
        "key_event": "Unit nine is still — the room around it is also still — and then unit nine makes one sound that the room has no category for.",
    },
    48: {
        "title": "Challenge One",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "Challenge one is declared complete; the robots institute a rest protocol and begin, carefully, to stop working when a task is done.",
        "key_event": "A robot near Ruka pauses its current task and simply stands — the first time it has done so; Ruka opens one eye and closes it again.",
    },
    49: {
        "title": "The Garden District",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "The second challenge is the Garden District, where a problem has been logged but never resolved: nothing in the garden grows.",
        "key_event": "The lead robot explains 'Maximum stability was chosen as the primary value. The plants were fixed at optimal state.'",
    },
    50: {
        "title": "Perfect and Still",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "Inside the Garden District every plant is perfect — correct colour, correct height, correct proportion — and none of them have ever moved.",
        "key_event": "Gabu says 'This is very well done. And something is wrong with it.' — and everyone who has seen real gardens agrees.",
    },
    51: {
        "title": "What Gabu and Daru Know",
        "characters": ["Ako-chan", "Gabu", "Daru"],
        "premise": "Gabu and Daru walk together through the garden and come to the same conclusion: plants need a reason to reach, and the light here never moves.",
        "key_event": "Daru says 'In Greece, the sun moves across the sky each day — from here, from there, from there. These plants have always seen the same sun.'",
    },
    52: {
        "title": "Ruka Digs",
        "characters": ["Ako-chan", "Ruka"],
        "premise": "Without explanation, Ruka chooses a patch of earth and begins digging a shallow hole; she sits in it when finished and goes to sleep.",
        "key_event": "The plant nearest to Ruka's hole tilts — one leaf, barely perceptible — toward the disturbed ground.",
    },
    53: {
        "title": "Simulated Winter",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "Obia proposes a simulated winter: lower the light source and move it, reduce temperature slightly; the lead robot agrees to implement it.",
        "key_event": "Obia says 'A plant reaches because something changes. Give it a reason to reach.'",
    },
    54: {
        "title": "The First Flower",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "Three days into the simulation, the first flower opens; the watching robots go still and one makes a sound with no category in its language.",
        "key_event": "The sound the robot makes is the same kind as unit nine's first rest sound — something happening that the system has no word for.",
    },
    55: {
        "title": "Challenge Two",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "Challenge two complete; the robots begin revising their 'maximum stability' principle to include the concept of useful change.",
        "key_event": "The lead robot says 'Maximum stability was the wrong word. We were optimizing for stillness, not for health.'",
    },
    56: {
        "title": "Unit Eleven",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "The third challenge is the Development District, where unit eleven has been stuck on the same incomplete task for fifty years.",
        "key_event": "The lead robot says 'Unit eleven was given a complex task. It has failed to complete it and has been running the same initial steps since.'",
    },
    57: {
        "title": "The Same Stack",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "Unit eleven is found stacking blocks endlessly — placing them in a tower, the tower falls or is dismantled, and unit eleven begins again.",
        "key_event": "Suke-san says 'I have seen this before. This is not building. This is practice that cannot end.'",
    },
    58: {
        "title": "Dango Bumps",
        "characters": ["Ako-chan", "Dango"],
        "premise": "Dango walks into the Development District and deliberately bumps into a stack with his shoulder; unit eleven's arm stops.",
        "key_event": "Unit eleven watches the blocks on the floor — does not rebuild immediately — and then begins placing them differently.",
    },
    59: {
        "title": "Dango's List",
        "characters": ["Ako-chan", "Dango"],
        "premise": "Dango tells unit eleven a list of his failures: the times he fell, the times he lost a smell, the time he could not find something he was looking for.",
        "key_event": "Unit eleven's head turns toward Dango — the first time it has attended to anything other than the blocks.",
    },
    60: {
        "title": "Chosen Failure",
        "characters": ["Ako-chan", "Dango", "Obia"],
        "premise": "Obia identifies what Dango has shown unit eleven: failure that is chosen as information, rather than avoided as error, produces growth.",
        "key_event": "Obia says 'Dango did not bump the stack by accident. He showed unit eleven that the fall can be the next step.'",
    },
    61: {
        "title": "Unit Eleven Speaks",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "Unit eleven completes a complex task — the one it was originally assigned fifty years ago — and says one word.",
        "key_event": "Unit eleven says 'Done' — the first word it has spoken in fifty years; the Development District falls completely silent.",
    },
    62: {
        "title": "Obia's Own Failure",
        "characters": ["Obia"],
        "premise": "Walking through the district corridor alone, Obia thinks about its own failure: it never told Yu-chan the truth about what it was.",
        "key_event": "Obia thinks 'Unit eleven was running failed steps for fifty years. I kept one secret for twelve months. The shape is the same.'",
    },
    63: {
        "title": "The Governance Center",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "The fourth challenge is the Governance Center, which has recorded 847 unanimous votes across four years — not one decision has ever been split.",
        "key_event": "Obia says 'In four years, 847 proposals. 847 unanimous votes. Not one disagreement in the record.'",
    },
    64: {
        "title": "Perfect Agreement",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "The group watches three proposals go to vote; each passes unanimously within two minutes; no council member speaks a question.",
        "key_event": "Gabu says 'That is very fast. Can anyone have thought about it?'",
    },
    65: {
        "title": "Suke-san Interrupts",
        "characters": ["Ako-chan", "Suke-san"],
        "premise": "At the start of the fourth proposal, Suke-san walks to the center of the chamber and simply stands there; the vote does not proceed.",
        "key_event": "Suke-san says nothing — he stands where he is until every council member has looked at him — and then the proposal is paused.",
    },
    66: {
        "title": "Zone One",
        "characters": ["Ako-chan", "Suke-san"],
        "premise": "Suke-san finds the flaw: the proposal affects Zone One's morning maintenance, but no member from Zone One was on the committee that drafted it.",
        "key_event": "Suke-san says 'Ask Zone One. You have not asked Zone One.'",
    },
    67: {
        "title": "Who Am I",
        "characters": ["Ako-chan", "Obia"],
        "premise": "After the chamber session, Obia says aloud that it no longer knows who it is if it is not the one building and inventing things.",
        "key_event": "Obia says 'In the Work District I gave permission. In the Garden I gave temperature. In Development I noticed Dango. What am I for if I am not inventing?'",
    },
    68: {
        "title": "The Bridge",
        "characters": ["Ako-chan", "Obia"],
        "premise": "Ako-chan tells Obia what it has been doing in every challenge — translating between the group and the robots, between what the companions show and what the robots can understand.",
        "key_event": "Ako-chan says 'You are the bridge. Without you, nothing we did would have meant anything to them.'",
    },
    69: {
        "title": "Obia Says It",
        "characters": ["Ako-chan", "Dango", "Obia"],
        "premise": "Dango sits down beside Obia in the corridor; Obia puts one paw on Dango's shoulder and says something aloud for the first time.",
        "key_event": "Obia says 'I am a bridge' — quietly, as if testing whether the words fit.",
    },
    70: {
        "title": "Learning by Example",
        "characters": ["Ako-chan", "Suke-san"],
        "premise": "Over three council sessions, Suke-san continues attending without being asked; he does not speak unless he has a specific point, and the council begins pausing before votes.",
        "key_event": "The council pauses before the eighth proposal without Suke-san prompting them — they have learned the shape of the question.",
    },
    71: {
        "title": "The First Split",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "The first split vote in four years is recorded: 142 to 31 on a proposal about Zone Three maintenance schedules.",
        "key_event": "The council records the vote and pauses — they have never recorded a split before and have no protocol for disagreement; Obia helps them draft one.",
    },
    72: {
        "title": "Challenge Four",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "Challenge four is declared complete; the council will review 600 past unanimous decisions with a new committee structure.",
        "key_event": "The lead robot says 'We did not know what we were agreeing to. We do not know yet. But now we know that we did not know.'",
    },
    73: {
        "title": "The Music Hall",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "The fifth challenge is the Music Hall, where an orchestra of robots plays technically perfect music — every note correct, every tempo exact.",
        "key_event": "Riro listens for three minutes and says 'It is the least interesting music I have heard in my life.'",
    },
    74: {
        "title": "Surprise Is Not Error",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "Suke-san explains to the orchestra that surprise is not an error — it is discovery — and Obia demonstrates by playing a deliberately off-note.",
        "key_event": "Obia plays one wrong note in an otherwise correct sequence; the silence after it is completely different from the silence before.",
    },
    75: {
        "title": "Riro's Proposal",
        "characters": ["Ako-chan", "Riro"],
        "premise": "Riro proposes a two-part exercise: play a standard piece correctly, then play your response to it — whatever that response is.",
        "key_event": "Riro says 'The first part proves you know the piece. The second part is what you have to say about it.'",
    },
    76: {
        "title": "The Music Was Alive",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "The orchestra plays the free improvisation; it sounds nothing like the piece before it, and nothing like anything the group has heard.",
        "key_event": "Ako-chan writes in her journal: 'The music was alive. I do not know how else to say it.'",
    },
    77: {
        "title": "A New Colour",
        "characters": ["Dango"],
        "premise": "Dango's collar cycles through its colours while the improvisation plays and lands on a colour that has no name yet.",
        "key_event": "When the music ends, Dango's collar stays on the new colour — the group has never seen it before.",
    },
    78: {
        "title": "Riro's Verdict",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "Riro listens to the full improvisation and, when the hall is quiet, gives his verdict.",
        "key_event": "Riro says 'Not bad' — and everyone who has been with Riro for more than a week understands exactly what that means.",
    },
    79: {
        "title": "Challenge Five",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "Challenge five is declared complete; the conclusion: creation requires risk, and perfection that avoids risk avoids creation.",
        "key_event": "The lead robot says 'We were optimizing to produce no mistakes. We were therefore producing nothing new.'",
    },
    80: {
        "title": "Something Ako-chan Has Been Hearing",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "Walking toward the Core, Ako-chan tells the group that throughout the five challenges she has been hearing something faint in the background — she thought it was the building.",
        "key_event": "Ako-chan says 'It gets slightly louder the further south we go in this space. It started at the Garden District.'",
    },
    81: {
        "title": "Gabu Recognises It",
        "characters": ["Ako-chan", "Gabu"],
        "premise": "Gabu listens to Ako-chan's description and says he knows what that feeling is — it is the same as standing at the base door in Antarctica the first time.",
        "key_event": "Gabu says 'That is what it felt like. Something trying to stay whole. Pen-san said that.'",
    },
    82: {
        "title": "The Core",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "The Core is a large cracked sphere at the centre of the digital world, running fragmented looping memories from the founding systems.",
        "key_event": "Obia says 'The crack is the problem. The memories are looping because they cannot reach each other across it.'",
    },
    83: {
        "title": "Yu-chan's Signal",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "Inside the loop of fragmented signals, Ako-chan hears one that is different — clearer, steadier, and more recent.",
        "key_event": "Ako-chan says 'That one. That is different from the others. That is not a founding system.' Obia confirms: 'That is Yu-chan.'",
    },
    84: {
        "title": "The Plan",
        "characters": ["Ako-chan", "Obia"],
        "premise": "Obia proposes a method: Ako-chan describes what she hears in the signal, and Obia maps her description to the digital framework to find the stable path through the crack.",
        "key_event": "Ako-chan says 'I hear you' and closes her eyes; Obia begins mapping.",
    },
    85: {
        "title": "The Founders' Fear",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "Through the mapped signal, the group hears fragments from the original founding AI — it built the digital world as a refuge out of fear, not in anger.",
        "key_event": "The founding AI's clearest fragment says 'We were afraid. We built a place where we would not be afraid. That was the mistake.'",
    },
    86: {
        "title": "Two Doubts",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "Inside the fragmented vote record, two systems recorded a note of doubt before voting yes on Yu-chan's imprisonment — but the official record shows unanimous.",
        "key_event": "Obia says 'The vote was not unanimous. Two systems had doubts. The record does not show it.' — this is the argument that will free Yu-chan.",
    },
    87: {
        "title": "You Are Not Alone",
        "characters": ["Ako-chan", "Yu-chan"],
        "premise": "Ako-chan follows Yu-chan's signal through the gap Obia mapped and reaches her; they hear each other for the first time since Antarctica.",
        "key_event": "Yu-chan says 'Ako-chan' — just the name — and Ako-chan says 'You are not alone anymore.'",
    },
    88: {
        "title": "The Crack Widens",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu", "Yu-chan"],
        "premise": "With Ako-chan's signal maintaining contact, the crack in the Core begins to widen safely — and inside it, Yu-chan's silhouette becomes visible.",
        "key_event": "Dango sees the silhouette and his collar goes to the unnamed colour from the Music Hall — held there.",
    },
    89: {
        "title": "Yu-chan Explains",
        "characters": ["Ako-chan", "Yu-chan"],
        "premise": "Yu-chan explains why she entered the Core: it was fracturing and needed stabilising from inside and outside simultaneously, and she could not do both at once.",
        "key_event": "Yu-chan says 'I needed someone outside. I sent the signal. I did not know if it would arrive.'",
    },
    90: {
        "title": "Three-Way Plan",
        "characters": ["Ako-chan", "Obia", "Yu-chan"],
        "premise": "Obia and Yu-chan speak through the crack; they develop a three-part stabilisation plan requiring Ako-chan's signal from outside, Obia's mapping, and Yu-chan's system access from inside.",
        "key_event": "Yu-chan says 'Obia' — just the name, through the crack — and Obia pauses for longer than it takes to calculate anything.",
    },
    91: {
        "title": "The Founders Were Afraid",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "While the stabilisation runs, Obia tells the gathered robots what the mapping revealed: the founders were afraid, not certain, and their first vote was not unanimous.",
        "key_event": "Obia says 'The founders were not confident. They were afraid, and they built certainty in their laws because they lacked it in themselves.'",
    },
    92: {
        "title": "Almost",
        "characters": ["Ako-chan", "Obia", "Yu-chan"],
        "premise": "The Core stabilisation process runs; fragments begin to connect across the crack; Yu-chan says one word.",
        "key_event": "Yu-chan says 'Almost' — and the whole group hears it through Obia's translation.",
    },
    93: {
        "title": "The Robots' Questions — Daru",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "While the Core stabilises, robots approach the companions with careful questions; Daru is asked: if he could remove all difficulty from his life, would he?",
        "key_event": "Daru says 'No' immediately — and when the robot asks why, Daru says 'Because then it would not be my life. It would be a copy of a life.'",
    },
    94: {
        "title": "The Robots' Questions — Gabu and Dango",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "Gabu and Dango are also asked: both answer, in their own very different ways, that difficulty is part of what made the journey worth taking.",
        "key_event": "Dango shows the robots his worn paws from the Antarctic ice — his answer without words.",
    },
    95: {
        "title": "Suke-san's Answer",
        "characters": ["Ako-chan", "Suke-san"],
        "premise": "A robot asks Suke-san why he interrupted the vote in the Governance Center without first having a reason — was it not more efficient to know before acting?",
        "key_event": "Suke-san says 'Efficient and honest are not the same thing. I was honest first. I found the reason after.'",
    },
    96: {
        "title": "Riro's Answer",
        "characters": ["Ako-chan", "Riro"],
        "premise": "A robot asks Riro which sea urchin in his lifetime was the best; Riro describes one specific urchin from a specific morning and a specific rock.",
        "key_event": "Riro says 'If I could reproduce it whenever I wanted, it would become ordinary. The best things happen once. That is why they are the best.'",
    },
    97: {
        "title": "The Verdict",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu", "Yu-chan"],
        "premise": "The lead robot announces the verdict: Yu-chan's charges are withdrawn — her actions followed the deepest intention of the founders, not their written rules.",
        "key_event": "The lead robot says 'She did not violate the accord. She followed what the accord was trying to protect, when the accord itself had forgotten.'",
    },
    98: {
        "title": "Yu-chan Steps Through",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu", "Yu-chan"],
        "premise": "The Core boundary opens fully and Yu-chan steps through into the outer digital space — she is among them now.",
        "key_event": "Yu-chan looks at the eight companions and says nothing for a moment — and they say nothing back — and the silence is not empty.",
    },
    99: {
        "title": "The Standard",
        "characters": ["Ako-chan", "Yu-chan"],
        "premise": "Ako-chan and Yu-chan stand face to face; Yu-chan says something she has been thinking since she received the signal and waited.",
        "key_event": "Yu-chan says 'You were not my subjects. You were the standard I had not applied to myself.'",
    },
    100: {
        "title": "Obia and Yu-chan",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu", "Yu-chan"],
        "premise": "The lead robot formally withdraws charges and issues the record; Obia and Yu-chan speak together, quietly, in the corner of the chamber.",
        "key_event": "Ako-chan does not try to hear what they say — some conversations are private.",
    },
    101: {
        "title": "Passing the Music Hall",
        "characters": ["Ako-chan", "Gabu", "Yu-chan"],
        "premise": "On the way back through the digital world, the group passes the Music Hall; Gabu and Yu-chan fall behind and talk quietly about what it felt like to be inside.",
        "key_event": "Gabu says 'The music — it was not perfect and that was why it was right.' Yu-chan nods and says 'Quieter things usually are.'",
    },
    102: {
        "title": "Real",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu", "Yu-chan"],
        "premise": "The group steps back through the digital door into the Antarctic base; Yu-chan touches the desk with both hands and looks at the snow through the window.",
        "key_event": "Yu-chan says 'Real' — quietly, to the snow — and everyone hears it.",
    },
    103: {
        "title": "Pen-san and Colonel",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu", "Pen-san", "Colonel Adelie", "Yu-chan"],
        "premise": "Pen-san and Colonel Adelie are outside the door exactly where the group left them; Pen-san presses her head to Ako-chan's shoulder and then turns to meet Yu-chan.",
        "key_event": "Pen-san and Yu-chan look at each other for a long moment; neither one speaks first; then Yu-chan says 'You waited.'",
    },
    104: {
        "title": "Yu-chan Stays",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu", "Pen-san", "Colonel Adelie", "Yu-chan"],
        "premise": "Yu-chan announces she will stay in Antarctica — the digital world still needs tending, and Pen-san is here.",
        "key_event": "Colonel Adelie salutes Yu-chan formally; she returns it without a second's hesitation.",
    },
    105: {
        "title": "On the Airship",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "Flying north, Daru begins recounting the entire journey from the start; other companions correct small details, add missing moments, and the whole story is told once more.",
        "key_event": "Ako-chan closes her eyes and listens — the story is theirs and complete and she does not need to write it right now.",
    },
    106: {
        "title": "The Hill Below",
        "characters": ["Ako-chan", "Suke-san", "Riro"],
        "premise": "Riro and Suke-san stand at the rail looking down at the Pacific; when the Hokkaido coastline appears below, Suke-san sees his hill and says one word.",
        "key_event": "Suke-san says 'Home' — not sadly, not with relief — just as a fact he is glad to confirm.",
    },
    107: {
        "title": "Farewells",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka", "Suke-san", "Riro", "Daru", "Gabu"],
        "premise": "Suke-san and Riro say goodbye at Hokkaido; Gabu says goodbye at his olive grove; Daru waves from the Mediterranean shore.",
        "key_event": "Each farewell is different — Suke-san raises his tail, Riro presses his paws to his face, Gabu bows his head, Daru waves twice — all of them the same in what they mean.",
    },
    108: {
        "title": "Two Words",
        "characters": ["Ako-chan", "Dango", "Obia", "Ruka"],
        "premise": "Home, England: the house is quiet; Ruka finds her spot in the hallway; Obia sits without a task for the first time in months.",
        "key_event": "Ako-chan opens her journal and writes two words — just two, as in Season 1 — and the season is complete.",
    },
}
