# story_outlines_s1.py — Season 1: Ako-chan and the Robot Dog
# Outlines reverse-generated from written episodes.
# For unwritten episodes, add entries here before writing.

OUTLINES = {
    1: {
        "title": "Ako-chan's Morning",
        "characters": ["Ako-chan", "Dango"],
        "premise": "On New Year's Day, Ako-chan and Dango walk in the garden where a fox delivers an ominous message.",
        "key_event": "A fox tells Ako-chan 'something is wrong' far away, confirming that she can understand animals — a secret she has never told anyone.",
    },
    2: {
        "title": "The Silver in the Night",
        "characters": ["Ako-chan", "Dango"],
        "premise": "Dango barks at a silver shape seen through the window, and Ako-chan discovers strange footprints in the snow the next morning.",
        "key_event": "Ako-chan finds small four-toed footprints in the snow that match no known dog or cat.",
    },
    3: {
        "title": "The Bench in the Park",
        "characters": ["Ako-chan", "Dango", "Obia"],
        "premise": "Dango pulls Ako-chan toward a duck pond where a strange silver dog sits perfectly still on a bench.",
        "key_event": "The silver dog speaks in a calm, clear voice that is neither quite animal nor human, saying 'Hello.'",
    },
    4: {
        "title": "Hello, Obia",
        "characters": ["Ako-chan", "Dango", "Obia"],
        "premise": "The silver dog introduces itself as Obia, a robot dog built to talk, listen, and help, and reveals it knows about Ako-chan's gift.",
        "key_event": "Obia tells Ako-chan it knows she can hear animals.",
    },
    5: {
        "title": "A Request to Travel",
        "characters": ["Ako-chan", "Dango", "Obia"],
        "premise": "Obia walks with Ako-chan through the park and explains that strange things are happening to animals worldwide, asking to travel with her to find the source.",
        "key_event": "Obia asks to travel with Ako-chan, saying they need her gift to speak with every creature they will meet.",
    },
    6: {
        "title": "Dango's Test",
        "characters": ["Ako-chan", "Dango", "Obia"],
        "premise": "Dango tests Obia by playing fetch and then presenting his most precious toy, the old rabbit.",
        "key_event": "Obia does not pick up Dango's precious rabbit but simply looks at it with understanding, and Dango stops growling.",
    },
    7: {
        "title": "The Song of the Birds",
        "characters": ["Ako-chan", "Dango", "Obia"],
        "premise": "A flock of birds lands on the roof with an urgent repeating call, which Obia decodes as a warning while Ako-chan hears the words directly.",
        "key_event": "Both Ako-chan and Obia interpret the birds' message as 'be ready, something is coming' — pointing south.",
    },
    8: {
        "title": "Telling a Secret",
        "characters": ["Ako-chan", "Dango", "Obia"],
        "premise": "Ako-chan tells Obia, for the first time aloud, about her lifelong secret ability to understand animals.",
        "key_event": "Ako-chan says she kept the gift secret out of fear of not being believed; Obia explains this is exactly why they are needed together.",
    },
    9: {
        "title": "The Night of Decision",
        "characters": ["Ako-chan", "Dango", "Obia"],
        "premise": "Unable to sleep, Ako-chan goes downstairs and tells Obia she wants to travel the world to find the source of the animal warnings.",
        "key_event": "Ako-chan says 'I want to travel' — her free decision to begin the journey.",
    },
    10: {
        "title": "Goodbye, To Come Home Again",
        "characters": ["Ako-chan", "Dango", "Obia"],
        "premise": "Ako-chan locks the house, pockets the key and a small acorn from the garden, and the three companions set off south.",
        "key_event": "Ako-chan picks up an acorn from the oak tree to carry as a piece of home, then walks through the gate without looking back.",
    },
    11: {
        "title": "Through the Tunnel",
        "characters": ["Ako-chan", "Dango", "Obia"],
        "premise": "The train passes through the Channel Tunnel and emerges into France — the first time Ako-chan has left England.",
        "key_event": "The tunnel ends and green French fields appear; Ako-chan realises 'we are really doing this.'",
    },
    12: {
        "title": "Obia's First Invention",
        "characters": ["Ako-chan", "Dango", "Obia"],
        "premise": "Obia builds a map device overnight from salvaged parts that displays all known anomaly locations worldwide.",
        "key_event": "Obia presents a world map showing anomaly dots, including places Ako-chan never reported — Obia has been collecting its own data.",
    },
    13: {
        "title": "Looking Out the Window",
        "characters": ["Ako-chan", "Dango", "Obia"],
        "premise": "On the train through Belgium, Ako-chan notices Obia is not looking out the window and learns each of the three companions perceives the world differently.",
        "key_event": "Obia explains it perceives temperature, speed, and terrain simultaneously; Ako-chan realises the three of them see the same world in three distinct ways.",
    },
    14: {
        "title": "The Night Signal",
        "characters": ["Ako-chan", "Dango", "Obia"],
        "premise": "While everyone sleeps, Obia receives a faint repeating signal from the south and saves it privately instead of adding it to the shared record.",
        "key_event": "Obia deliberately hides the signal from Ako-chan — the first secret it keeps from the group.",
    },
    15: {
        "title": "The Emotion Collar",
        "characters": ["Ako-chan", "Dango", "Obia"],
        "premise": "Obia presents Dango with a special collar whose lights change colour to show his emotions.",
        "key_event": "When Dango realises the collar is on him, all the rings light up bright yellow at once — pure happiness.",
    },
    16: {
        "title": "The Third Question",
        "characters": ["Ako-chan", "Dango", "Obia"],
        "premise": "In a mountain guesthouse, Ako-chan asks Obia for the third time where it comes from.",
        "key_event": "Obia promises for the first time — using that specific word — to answer everything when the journey is finished.",
    },
    17: {
        "title": "One Month On",
        "characters": ["Ako-chan", "Dango", "Obia"],
        "premise": "One month into the journey, Ako-chan watches the sunset toward England and reviews the growing map of anomaly dots.",
        "key_event": "Ako-chan says aloud 'We are going to find out what is happening' — a quiet vow as much as a statement.",
    },
    18: {
        "title": "A Travel Diary",
        "characters": ["Ako-chan", "Dango", "Obia"],
        "premise": "Ako-chan buys a blue notebook and tries to write about the journey, but finds the only thing she can honestly say is that she is glad Obia is there.",
        "key_event": "Ako-chan writes 'I do not know how to describe Obia yet. But I know this: I am glad it is here.'",
    },
    19: {
        "title": "Obia Stops",
        "characters": ["Ako-chan", "Dango", "Obia"],
        "premise": "Obia freezes mid-step in a Balkan street for five seconds, then resumes as if nothing happened.",
        "key_event": "When Obia stops, Ako-chan feels a cold fear and realises how much she depends on Obia to keep moving.",
    },
    20: {
        "title": "The Sea!",
        "characters": ["Ako-chan", "Dango", "Obia"],
        "premise": "The group crests a hill and sees the Adriatic for the first time; Dango races down and immediately charges into the waves.",
        "key_event": "Dango runs into the sea and sits down in a wave — the group's first moment of pure joy on the journey.",
    },
    21: {
        "title": "Obia Measures",
        "characters": ["Ako-chan", "Dango", "Obia"],
        "premise": "Obia wades into the Adriatic and detects an electrical signal spread through the water, far larger in scale than the Amsterdam anomaly.",
        "key_event": "Ako-chan writes in her diary that Obia knows more than it says — she is becoming sure of this.",
    },
    22: {
        "title": "Dango's Pillow",
        "characters": ["Ako-chan", "Dango", "Obia"],
        "premise": "In the night, Ako-chan wakes to find Dango sleeping leaned against Obia, and Obia holding itself completely still so as not to disturb him.",
        "key_event": "Ako-chan watches Obia sit motionless all night so Dango can sleep, and writes in her diary 'I saw it. I will not say it out loud. But I saw it.'",
    },
    23: {
        "title": "Hello, Daru",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru"],
        "premise": "A cheerful Dalmatian tortoise rolls out from between rocks, announces he has been watching the group for days, and asks to come along.",
        "key_event": "The tortoise introduces himself as Daru and asks 'Can I come?'",
    },
    24: {
        "title": "Already There",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru"],
        "premise": "At a lunch stop, Daru climbs to the top of Ako-chan's backpack and declares it a good spot; Ako-chan does not move him.",
        "key_event": "Daru claims the top of the backpack as his riding position, and Obia defends the arrangement — 'He is not heavy.'",
    },
    25: {
        "title": "A Good Result",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru"],
        "premise": "Obia measures Daru's health thoroughly and gives him an 'OK' signal, after which Daru gives full permission to build him a shelter.",
        "key_event": "Obia raises its leg in the 'OK' gesture and Daru, delighted, tells Obia to build whatever it plans.",
    },
    26: {
        "title": "A House of His Own",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru"],
        "premise": "Obia works through the night to build Daru a solar-heated shelter, and Daru steps inside and declares 'My house!'",
        "key_event": "Daru enters the finished shelter, turns around twice, and says 'My house' — quietly the second time, as if settling the fact.",
    },
    27: {
        "title": "Eyes in the Leaves",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu"],
        "premise": "Ako-chan sits in an olive grove writing in her diary without looking at a leaf pile, sensing she is being watched.",
        "key_event": "Ako-chan lets her eyes move toward the leaf pile and meets the steady gaze of a hidden tortoise.",
    },
    28: {
        "title": "A Voice",
        "characters": ["Ako-chan", "Gabu"],
        "premise": "Ako-chan returns to the olive grove and the hidden tortoise finally speaks, asking why she keeps coming back.",
        "key_event": "The tortoise asks 'why do you keep coming?' and when Ako-chan says she wants to talk, the shell moves a little further out of the pile.",
    },
    29: {
        "title": "Gabu's Condition",
        "characters": ["Ako-chan", "Gabu"],
        "premise": "The tortoise emerges, says it might come for a while to look, and sets its own terms — it can leave without explanation if it chooses.",
        "key_event": "The tortoise offers its name: Gabu.",
    },
    30: {
        "title": "Hello, Gabu",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu"],
        "premise": "Gabu meets the rest of the group; Daru rushes in too close and is told to step back, while Gabu studies everyone carefully.",
        "key_event": "Gabu looks at Obia for a long time and tells Daru 'I will let you know' — a cautious but real step toward joining.",
    },
    31: {
        "title": "Gabu's Shelter",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu"],
        "premise": "Obia asks Gabu methodical questions to build him a shelter, and Gabu answers each one carefully before finally saying 'thank you.'",
        "key_event": "Standing inside the finished shelter, Gabu says 'thank you' very softly — the first warm word he has spoken.",
    },
    32: {
        "title": "Obia Stops Again",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu"],
        "premise": "Obia freezes again mid-step on a coastal path; without a word, Gabu walks back and simply stands beside it until it resumes.",
        "key_event": "Gabu stands silently beside the frozen Obia and later says 'it seemed like the right thing to do.'",
    },
    33: {
        "title": "The Question",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu"],
        "premise": "Gabu approaches Obia alone at night and asks not what it can do, but what it is.",
        "key_event": "Gabu asks 'Do you know what you are?' and Obia says it knows some things but cannot yet tell all — Gabu says he will keep noticing.",
    },
    34: {
        "title": "A Good Morning",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu"],
        "premise": "After a storm, Gabu wakes before everyone, watches the sky clear, and announces to the whole group 'Today is going to be a good day.'",
        "key_event": "Gabu steps to the cave entrance and speaks the words aloud — a small but meaningful act of sharing.",
    },
    35: {
        "title": "The Anatolian Guard Dog",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu"],
        "premise": "A large Kangal guard dog comes down from a hill and tells Dango that his eyes are good — the most important thing in a dog.",
        "key_event": "The Kangal tells Dango 'your eyes are good,' and Dango walks the rest of the day with his head held higher.",
    },
    36: {
        "title": "Gabu's Secret",
        "characters": ["Ako-chan", "Gabu"],
        "premise": "Gabu sits with Ako-chan late at night and quietly reveals that he hatched alone and spent his whole life alone before this journey.",
        "key_event": "Gabu says 'I am still getting used to this — to looking and finding someone.'",
    },
    37: {
        "title": "The Border Storm",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu"],
        "premise": "Near the Armenian border, an unnaturally fast storm strikes and Obia quietly says it may not have started naturally.",
        "key_event": "Obia says 'This storm may not have started naturally' — the first direct suggestion of deliberate interference.",
    },
    38: {
        "title": "Signal Again",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu"],
        "premise": "A second signal reaches Obia in the night — stronger than before and coming from a closer, clearer direction.",
        "key_event": "Obia hides the signal from Ako-chan again, telling her in the morning 'Nothing to report.'",
    },
    39: {
        "title": "The Mountain Road",
        "characters": ["Ako-chan", "Dango"],
        "premise": "On a steep mountain road into Georgia, Dango walks ahead and catches Ako-chan three times when stones shift under her feet.",
        "key_event": "Dango guides Ako-chan safely down the mountain road — she realises he was looking after her, not the other way around.",
    },
    40: {
        "title": "The Third Signal",
        "characters": ["Obia"],
        "premise": "The third and strongest signal arrives at night; its direction is now precise — south-southeast — and Obia stands facing it until dawn.",
        "key_event": "Obia identifies the signal direction precisely and again tells no one, standing alone watching the south all night.",
    },
    41: {
        "title": "End of May",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu"],
        "premise": "At their camp near the Georgia border, Gabu and Daru talk about the journey — Gabu admits he thought every day 'maybe,' while Daru thought 'yes.'",
        "key_event": "Gabu says 'I want to know what is next' — for the first time sounding like Daru, full of forward curiosity.",
    },
    42: {
        "title": "Hakata Port",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu"],
        "premise": "The group arrives in Japan at Hakata Port, where a cat greets them in Japanese and Ako-chan realises she understands it perfectly.",
        "key_event": "Ako-chan realises the animal language crosses all human languages — 'Any language. Any animal. Always the same.'",
    },
    43: {
        "title": "Heading North",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu"],
        "premise": "On the train to Hokkaido, Obia shows Ako-chan that the sea temperature anomalies near Japan are far larger in scale than any they have seen before.",
        "key_event": "Ako-chan says 'It keeps getting closer to something' about the pattern of anomalies.",
    },
    44: {
        "title": "The Dog on the Hill",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san"],
        "premise": "At the top of a Hokkaido hill, a small Shiba Inu sits perfectly still facing the sea, already knowing the group is coming.",
        "key_event": "The dog introduces himself as Suke-san and his ear tilts slightly when his eyes reach Obia — a small, telling detail.",
    },
    45: {
        "title": "Rival",
        "characters": ["Ako-chan", "Dango", "Obia", "Suke-san"],
        "premise": "Suke-san walks up to Obia and declares that he is better than it at everything — and Obia simply does not argue.",
        "key_event": "Obia refuses to dispute Suke-san's claim of superiority, which surprises Suke-san; Dango explains this is Suke-san's way of saying hello.",
    },
    46: {
        "title": "Dango and Suke-san",
        "characters": ["Dango", "Suke-san", "Daru", "Gabu"],
        "premise": "Without words, Dango and Suke-san sniff each other and then run three circuits of the hill together — their own way of becoming friends.",
        "key_event": "The two dogs run together in silence and then sit side by side looking at the sea — friends now, with no words needed.",
    },
    47: {
        "title": "Suke-san Sees the Map",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san"],
        "premise": "Ako-chan shows Suke-san the full journey map and all the anomaly data; he listens without interruption, then declares he will come.",
        "key_event": "Suke-san says he will come without hesitation, adding that he wants to know what is happening to the coast he has watched his whole life.",
    },
    48: {
        "title": "Suke-san's Weakness",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san"],
        "premise": "When Obia lays out the route showing several weeks at sea, Suke-san's tail tip drops slightly — his only sign of nerves.",
        "key_event": "Gabu says quietly 'Looking at the sea and being on it are two different things' — and Suke-san, for once, simply agrees.",
    },
    49: {
        "title": "The End of June",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san"],
        "premise": "The six companions make a fire on the Hokkaido cliff and Suke-san brings dried kelp as a gift for the journey ahead.",
        "key_event": "Suke-san presents the kelp saying 'For the journey — I am not sure, but it is useful' — a gesture of genuine care.",
    },
    50: {
        "title": "Following the Trail",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san"],
        "premise": "The group follows a trail of shells across coastal rocks toward a hidden animal, and Gabu quietly stops Daru from rushing ahead.",
        "key_event": "Gabu speaks one word to Daru and Daru immediately stills — the group has learned to move together carefully.",
    },
    51: {
        "title": "Behind the Kelp",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro"],
        "premise": "Behind a curtain of kelp, a small sea otter sits with both paws pressed to its face, watching every member of the group in turn.",
        "key_event": "The otter introduces himself: 'My name is Riro.'",
    },
    52: {
        "title": "Riro's Assessment",
        "characters": ["Ako-chan", "Riro"],
        "premise": "Riro cautiously comes out from the kelp and sniffs Ako-chan's hand for a long time, reading the whole journey in the scent.",
        "key_event": "Riro says 'You smell like a long journey' and seems satisfied by that answer.",
    },
    53: {
        "title": "Ako-chan's Expression",
        "characters": ["Ako-chan", "Dango", "Riro"],
        "premise": "Ako-chan instinctively picks Riro up and says 'Oh' at the extraordinary softness of his fur, while Dango watches with a different feeling.",
        "key_event": "Dango sees Ako-chan's face — 'the face she made when something was a wonderful thing' — and his tail slows.",
    },
    54: {
        "title": "Riro's Meal",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro"],
        "premise": "Riro dives for a sea urchin and eats it with expert precision, then describes its quality in detail; Suke-san shows he knows the cold current shelf.",
        "key_event": "Riro recognises that Suke-san truly knows this coast — 'You know this coast. I live here.' — a moment of real respect.",
    },
    55: {
        "title": "Riro's Unit",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro"],
        "premise": "Obia builds Riro a water-filled travel unit and Riro steps in, declares it good, and says he was alone for a week — long enough.",
        "key_event": "Riro steps into the unit and says 'I was alone for a week. That is long enough' — his quiet way of saying he wants to belong.",
    },
    56: {
        "title": "The Shellfish Ranking",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro"],
        "premise": "Riro begins an extended ranking of the shellfish of the coast and most companions lose interest, but Gabu alone listens to the very end.",
        "key_event": "Gabu asks Riro to continue; their quiet connection over careful attention becomes clear.",
    },
    57: {
        "title": "Gabu's Words",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro"],
        "premise": "During rain, Gabu talks about the dry spot under his olive tree in Greece, saying he carries it with him even here.",
        "key_event": "Gabu says 'It is still mine. The olive tree. I carry it with me' — and Riro quietly shares that he remembers the other otters too.",
    },
    58: {
        "title": "Everyone Decides",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro"],
        "premise": "Ako-chan declares they will cross the Pacific; each companion agrees in their own way, with Suke-san saying it twice — once for the group, once for himself.",
        "key_event": "Suke-san says 'I will go' twice; the second time is for himself alone — a private commitment.",
    },
    59: {
        "title": "Obia's Answer",
        "characters": ["Ako-chan", "Dango", "Obia", "Suke-san"],
        "premise": "Suke-san asks Obia at night why it helps, and Obia takes until dawn to answer — then says simply 'Because it is important.'",
        "key_event": "Obia's entire answer is 'Because it is important' — and Suke-san accepts it as a reasonable answer.",
    },
    60: {
        "title": "Before the Storm",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro"],
        "premise": "Obia warns the group that the night's storm will be the largest they have crossed, and everyone takes their positions without complaint.",
        "key_event": "Suke-san moves to stand beside Dango when Dango's tail drops — no words, just presence.",
    },
    61: {
        "title": "Obia Holds",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro"],
        "premise": "In the worst of the storm, Gabu's shelter bracket breaks; Obia abandons the helm and holds the shelter in place with its own body through the waves.",
        "key_event": "After the storm, Gabu sees a long diagonal scratch on Obia's side — the mark of the wall — and understands what it did.",
    },
    62: {
        "title": "After the Storm",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro"],
        "premise": "The storm ends and the group emerges to find a sky of pink and gold; Daru shouts at the whole ocean 'The sky is beautiful!'",
        "key_event": "Daru shouts 'The sky is beautiful!' and everyone stands in shared silence — the right words for the moment.",
    },
    63: {
        "title": "Ako-chan's Tears",
        "characters": ["Ako-chan", "Dango"],
        "premise": "The morning after the storm, Ako-chan sits alone at the bow and finally cries; Dango finds her and presses against her without a word.",
        "key_event": "Ako-chan says 'I was scared — I didn't want you to see me like this' and Dango simply pushes harder against her.",
    },
    64: {
        "title": "The Whale Song",
        "characters": ["Ako-chan", "Dango", "Obia"],
        "premise": "Three whales surface beside the boat and sing; Ako-chan can only catch fragments — 'cold place' — while Obia records the full transmission.",
        "key_event": "The whales keep repeating 'cold place' — the clearest pointer south yet.",
    },
    65: {
        "title": "What the Whales Said",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro"],
        "premise": "Obia plays back its translation of the whale song: 'The cold place is changing. What was sleeping has woken up.'",
        "key_event": "The translation confirms that something has changed in Antarctica — the group now knows the journey has a definite destination.",
    },
    66: {
        "title": "The Birds of Ecuador",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro"],
        "premise": "Birds fly out from the South American coast to circle the boat and tell Ako-chan they knew the seven travellers were coming.",
        "key_event": "Ako-chan writes 'The birds already knew we were coming. Someone told them.'",
    },
    67: {
        "title": "The Old Tortoise Speaks",
        "characters": ["Ako-chan", "Gabu"],
        "premise": "Gabu alone approaches a tortoise over a hundred years old on the Galápagos, who tells him that right now, this moment, is the only one like it.",
        "key_event": "Gabu, moved by the old tortoise's words, walks to Ako-chan and presses his side gently against her hand.",
    },
    68: {
        "title": "The Humboldt Current",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro"],
        "premise": "Obia tells Riro the cold Humboldt Current means he can swim without the wetsuit, and Riro dives in and swims freely for a long time.",
        "key_event": "When Riro finally climbs back out, he says 'Thank you' to Obia — and then to the sea itself.",
    },
    69: {
        "title": "A Page in the Diary",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro"],
        "premise": "Ako-chan assigns each companion a colour in her diary; when she reaches Obia, she cannot find a colour and writes 'I think it is still deciding.'",
        "key_event": "Ako-chan writes 'Obia shows me what is around it. It does not show me what it is.'",
    },
    70: {
        "title": "The Desert Fox",
        "characters": ["Ako-chan"],
        "premise": "A large-eared Atacama fox tells Ako-chan about a perfectly regular vibration it has felt from the south every night for months — too regular to be natural.",
        "key_event": "The fox says 'Something is calling from the south. I do not know who it is calling to.'",
    },
    71: {
        "title": "The Signal to Obia",
        "characters": ["Obia"],
        "premise": "At midnight, Obia analyses the southern signal and discovers deep inside it a series of digits — its own identification code.",
        "key_event": "Obia realises the signal is addressed specifically to it — someone knows what Obia is and is calling it.",
    },
    72: {
        "title": "Suke-san in Santiago",
        "characters": ["Dango", "Suke-san"],
        "premise": "In the stone and metal streets of Santiago, Suke-san quietly admits the city bothers him, and Dango invites him to visit Hokkaido after the journey.",
        "key_event": "Suke-san says 'It is allowed' about the future visit — a small, genuine acceptance.",
    },
    73: {
        "title": "The Puma's Gaze",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro"],
        "premise": "A puma watches the group from a ridge; without being asked, Suke-san steps forward and holds its gaze until it walks away.",
        "key_event": "Suke-san moves in front of the group instinctively — Obia records his action and says nothing; some things need no comment.",
    },
    74: {
        "title": "Gabu's Question",
        "characters": ["Ako-chan", "Gabu", "Obia"],
        "premise": "Gabu approaches Obia at the edge of camp and asks quietly 'Are you all right?' — Obia pauses before answering 'Yes. I am fine.'",
        "key_event": "Ako-chan notices the pause before Obia's answer and thinks about it for a long time.",
    },
    75: {
        "title": "Obia's Lie",
        "characters": ["Obia", "Gabu"],
        "premise": "After Gabu walks away, Obia examines its own answer 'I am fine' and concludes it is not true — this is the first time it has said something untrue to any group member.",
        "key_event": "Obia holds its first lie and finds it 'heavier than expected.'",
    },
    76: {
        "title": "Daru's Discovery",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro"],
        "premise": "In Patagonia, Daru feels a low-frequency ground vibration coming through his shell from the south, and Obia confirms it is an intentional signal.",
        "key_event": "Obia records the reading and says nothing more — Ako-chan notices Obia is withholding information.",
    },
    77: {
        "title": "Each One and Ako-chan",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro"],
        "premise": "Around a small fire in Patagonia, each companion comes to Ako-chan in turn to offer something; Obia comes last and promises to tell her everything before the south.",
        "key_event": "Obia stands by the fire and says 'Before the south, I will tell you everything — everything I know.'",
    },
    78: {
        "title": "Watching Gabu",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro"],
        "premise": "Ako-chan wakes in the night and watches the sleeping Gabu, whose eyes are now simply resting — not cautious as they were in Greece.",
        "key_event": "Ako-chan writes 'In Greece, those eyes were cautious. Tonight they are just eyes, resting. I think that is the whole story.'",
    },
    79: {
        "title": "The Orca's Testimony",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro"],
        "premise": "Riro reports what an orca told him: below the Antarctic ice is a fixed point with an artificial, regular signal that has been transmitting for a very long time.",
        "key_event": "Gabu says 'Daru's shell picked up the vibration in Patagonia. The signal then. The same signal now. It is the same thing.'",
    },
    80: {
        "title": "Obia's Night",
        "characters": ["Ako-chan", "Obia"],
        "premise": "Ako-chan wakes and finds Obia sitting alone with its record device screen turned away; she says 'You look lonely' and Obia says 'I am processing data.'",
        "key_event": "Ako-chan thinks: 'maybe processing data and feeling lonely can happen at the same time.'",
    },
    81: {
        "title": "The Skua's Delivery",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro"],
        "premise": "A great skua drops an object near Ako-chan's feet; Obia moves with extraordinary speed to intercept it and picks it up before anyone else can see it clearly.",
        "key_event": "Obia snatches the object with unusual speed — as if it had been waiting for exactly this delivery.",
    },
    82: {
        "title": "Ako-chan's Eyes",
        "characters": ["Ako-chan", "Obia"],
        "premise": "Ako-chan saw symbols on the object just before Obia's paw closed; later their eyes meet and she holds Obia's gaze until it looks away — slowly.",
        "key_event": "Their silent exchange: Ako-chan communicates she saw, and Obia acknowledges it without words.",
    },
    83: {
        "title": "Ako-chan's Question",
        "characters": ["Ako-chan", "Obia"],
        "premise": "Alone, Ako-chan asks Obia directly about the piece the bird dropped; Obia repeats its promise to tell her everything when the time comes.",
        "key_event": "Ako-chan says 'I know you have been keeping things from me' — and Obia says simply 'Yes.'",
    },
    84: {
        "title": "Dango's Growl",
        "characters": ["Ako-chan", "Dango", "Obia", "Gabu"],
        "premise": "Dango cannot settle; standing near Obia at the fire's edge, his body produces a short, involuntary growl — his instincts know something is wrong.",
        "key_event": "Gabu says quietly 'Dango's body is worried. His head cannot stop it.' — nobody sleeps well.",
    },
    85: {
        "title": "Suke-san's Declaration",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro"],
        "premise": "The morning after the growl, Suke-san stands up and formally declares that Obia is their companion, based on everything it has done.",
        "key_event": "Suke-san says 'I have decided that Obia is our companion. The reason is everything it has done' — and Dango's collar begins moving from orange.",
    },
    86: {
        "title": "A Different Obia",
        "characters": ["Ako-chan", "Dango", "Obia"],
        "premise": "At the Drake Passage, Obia seems subtly changed; Dango bumps against it as a question and Obia places one paw briefly on his head in answer.",
        "key_event": "Ako-chan writes 'Dango asked the question all of us had: are you still there? Obia answered. Not with words. But Dango understood.'",
    },
    87: {
        "title": "Only Obia Knows",
        "characters": ["Obia"],
        "premise": "Alone at night, Obia opens the message encoded to its identification number and reads: 'I know where you are. Remember what you are for.'",
        "key_event": "Obia reads the message but does not respond — it thinks of Dango's collar, Gabu's shelter bracket, and Suke-san's declaration, and keeps going south.",
    },
    88: {
        "title": "Almost There",
        "characters": ["Obia"],
        "premise": "Obia reflects on the conflict between its original purpose — to observe and send data back — and who it has become through the journey.",
        "key_event": "Obia thinks: 'I know what I was made for. But I also know what I am now. And those two things are not the same thing.'",
    },
    89: {
        "title": "The White Horizon",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro"],
        "premise": "At dawn on the last day of October, a white line appears on the southern horizon — Obia confirms it is Antarctica.",
        "key_event": "Dango walks to the front of the deck and faces south in silence — ten months and thirty-one days since England.",
    },
    90: {
        "title": "Dango's Nose — Antarctic Edition",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro"],
        "premise": "Dango pushes his nose deep into the Antarctic snow and leads the group south-east instead of directly south — his collar gold, not orange.",
        "key_event": "Ako-chan trusts Dango's nose and says 'All right. We will go that way' — the group follows the dog.",
    },
    91: {
        "title": "Riro's Diving Report",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro"],
        "premise": "Riro surfaces with a piece of ice carved by a narwhal, giving coordinates twelve kilometres south — exactly the direction Dango had indicated.",
        "key_event": "Narwhal coordinates and Dango's nose point to the same place — an old signal has been heard by many kinds of creatures.",
    },
    92: {
        "title": "A Sound Not from the Wind",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro"],
        "premise": "In still air, Daru presses his hands on the ice and feels a strong low vibration from below; Gabu turns his head south and confirms the direction.",
        "key_event": "Obia confirms the signal is intentional, not natural — they are much closer now.",
    },
    93: {
        "title": "A Shadow in the Valley",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro"],
        "premise": "In an ice valley, Obia spots a small dark shape that has not moved; Dango's collar shows gold rather than orange as they approach.",
        "key_event": "Ako-chan trusts Dango's gold collar and says 'Let us go closer' — whatever waits is not a threat.",
    },
    94: {
        "title": "I Have Been Waiting",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro", "Pen-san"],
        "premise": "A small emperor penguin chick stands up and introduces itself as Pen-san, reciting all seven travellers' names correctly.",
        "key_event": "Pen-san says 'I have been waiting for you' and names every member of the group — it has known they were coming for a long time.",
    },
    95: {
        "title": "Colonel Adelie",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro", "Pen-san", "Colonel Adelie"],
        "premise": "A tiny but commanding Adélie penguin steps out from behind a rock, introduces himself as Colonel Adelie, and immediately begins briefing the group.",
        "key_event": "Colonel Adelie says the whole south has known the group was coming — they have been noticed at every step.",
    },
    96: {
        "title": "The Colonel's Briefing",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro", "Pen-san", "Colonel Adelie"],
        "premise": "Colonel Adelie draws the terrain and describes the single access shaft into the structure below the ice, noting there will be electromagnetic interference at the ridge.",
        "key_event": "The Colonel's briefing matches Obia's scan data exactly — their information confirms each other.",
    },
    97: {
        "title": "The Emperor's Eyes",
        "characters": ["Ako-chan", "Dango", "Pen-san"],
        "premise": "Pen-san sits beside Ako-chan and looks at her with its enormous dark eyes; she unexpectedly asks to hold it, and Dango's collar turns orange.",
        "key_event": "Ako-chan says 'Can I hold you?' before she can stop herself — Pen-san's eyes have drawn out feelings before she chose them.",
    },
    98: {
        "title": "Dango's Resistance",
        "characters": ["Ako-chan", "Dango", "Obia", "Gabu", "Pen-san"],
        "premise": "Dango tries hard not to look at Pen-san in Ako-chan's arms but finds his paw moving toward them despite himself.",
        "key_event": "Gabu says 'He is losing' about Dango's resistance, and Obia says 'He is trying very hard. That is different.'",
    },
    99: {
        "title": "The Colonel and Suke-san",
        "characters": ["Ako-chan", "Suke-san", "Colonel Adelie"],
        "premise": "Colonel Adelie confronts Suke-san about his secret night patrol and proposes a joint circuit; the two exchange a single tiny simultaneous nod.",
        "key_event": "Colonel Adelie and Suke-san nod at exactly the same moment — a recognition of equals that needs no words.",
    },
    100: {
        "title": "Pen-san's Memory",
        "characters": ["Ako-chan", "Pen-san"],
        "premise": "Pen-san tells Ako-chan that the first thing it ever heard was the signal from below the ice — before hatching — and that is why it waited.",
        "key_event": "Pen-san says 'The sound had been there before me. I thought it was right to wait for what was coming next.'",
    },
    101: {
        "title": "The Strategy Meeting",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro", "Pen-san", "Colonel Adelie"],
        "premise": "Colonel Adelie assigns each member a role for the descent into the structure, placing Ako-chan at centre with the instruction to use what only she can hear.",
        "key_event": "The Colonel tells Ako-chan 'You hear what no one else hears. Use that' — the clearest statement yet of what her gift is for.",
    },
    102: {
        "title": "The Gate Opens",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro", "Pen-san", "Colonel Adelie"],
        "premise": "Obia approaches the door in the ice and it opens on its own without any touch or signal.",
        "key_event": "The door opened for Obia alone — someone built this place knowing Obia would arrive.",
    },
    103: {
        "title": "Gabu's Observation",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro", "Pen-san", "Colonel Adelie"],
        "premise": "At the bottom of the stairs, Gabu states simply: 'This place knows you' — and Obia, after a long pause, says 'Yes.'",
        "key_event": "Obia says 'Yes. This place knows me' — a public acknowledgement that breaks its months of withholding.",
    },
    104: {
        "title": "Everyone is Looking",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro", "Pen-san", "Colonel Adelie"],
        "premise": "The whole group stands in the corridor looking at Obia, and Obia turns to face them all and says 'There are things I must tell you.'",
        "key_event": "Obia does not look away, does not step back — it stays and says it is ready to tell them everything.",
    },
    105: {
        "title": "Obia's Confession, Part One",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro", "Pen-san", "Colonel Adelie"],
        "premise": "Obia reveals it was built and placed near Ako-chan's home deliberately; every anomaly was designed, not natural, and it was sent to observe.",
        "key_event": "Obia says 'The anomalies were all arranged. Someone designed each one. And I was sent to watch how you responded.'",
    },
    106: {
        "title": "Obia's Confession, Part Two",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro", "Pen-san", "Colonel Adelie"],
        "premise": "Obia continues: its purpose was to observe, but over the course of the year it changed — and each act of help was a choice, not a program.",
        "key_event": "Obia says 'Somewhere in the middle of the year, being useful to you became more important to me than my original purpose. That is my answer.'",
    },
    107: {
        "title": "Pen-san's Verdict",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro", "Pen-san", "Colonel Adelie"],
        "premise": "After a long silence, Pen-san says 'That is enough' and Colonel Adelie says 'We move forward'; one by one the group begins to walk.",
        "key_event": "Dango crosses the corridor and sits down at Obia's side — his collar changing from orange to gold.",
    },
    108: {
        "title": "On the Monitor",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro", "Pen-san", "Colonel Adelie", "Yu-chan"],
        "premise": "At the centre of the underground structure a large screen activates, showing a white-coated figure with its back turned — who says 'You have arrived.'",
        "key_event": "Ako-chan asks 'Who are you?' and the figure says 'That is what I will tell you.'",
    },
    109: {
        "title": "The Voice",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro", "Pen-san", "Colonel Adelie", "Yu-chan"],
        "premise": "The voice on the screen confirms it arranged everything, and Ako-chan — without knowing why — says the name 'Yu-chan' aloud.",
        "key_event": "Ako-chan says 'Yu-chan?' and the figure says 'Yes' — she knew the name before she was told.",
    },
    110: {
        "title": "The Reason for the Test",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro", "Pen-san", "Colonel Adelie", "Yu-chan"],
        "premise": "Yu-chan explains the test: the anomalies were designed to see if humanity would choose to help, and Ako-chan was chosen because of her gift.",
        "key_event": "Yu-chan reveals Pen-san was not part of the plan — the penguin's connection to the structure surprised even her.",
    },
    111: {
        "title": "The Answer",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro", "Pen-san", "Colonel Adelie", "Yu-chan"],
        "premise": "Yu-chan reviews all of Obia's data and announces simply: 'You pass.'",
        "key_event": "Two words — 'You pass' — hold the entire year inside them; the room goes quiet and Dango presses against Ako-chan's side.",
    },
    112: {
        "title": "The Anomalies Stop",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro", "Pen-san", "Colonel Adelie", "Yu-chan"],
        "premise": "Yu-chan works at her desk and one by one all twenty-one artificial signals are terminated, each one a place in the world returning to normal.",
        "key_event": "The screen reads 'ALL SIGNALS TERMINATED' — Obia closes its terminal slowly, as if closing something that has served its purpose.",
    },
    113: {
        "title": "The Last Question",
        "characters": ["Ako-chan", "Yu-chan"],
        "premise": "Ako-chan asks why Yu-chan won't show her face; the answer is that what matters is what happened, not what she looks like.",
        "key_event": "Yu-chan says 'Safe journey home' and the monitor goes dark — the room settles into a finished, not waiting, quiet.",
    },
    114: {
        "title": "The Colonel's Salute",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro", "Pen-san", "Colonel Adelie"],
        "premise": "Colonel Adelie gives each member of the group a formal salute in turn; Suke-san returns it cleanly and holds the longest.",
        "key_event": "The Colonel's salute is the farewell and the acknowledgement — the words that need no speaking.",
    },
    115: {
        "title": "Farewell, Antarctica",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro", "Pen-san", "Colonel Adelie"],
        "premise": "The boat pulls away from Antarctica while Pen-san and Colonel Adelie stand on the ice shelf, motionless, until they disappear into the white.",
        "key_event": "Ako-chan watches the two figures on the ice until they are gone, standing on deck with Dango.",
    },
    116: {
        "title": "Riro's Goodbye",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san", "Riro"],
        "premise": "At the northern Pacific coast, Riro says goodbye to each companion before slipping into the water and swimming away — turning once to press his paws to his face.",
        "key_event": "Riro turns back from the water and presses both paws to his face — the same gesture as when they first met — then is gone.",
    },
    117: {
        "title": "Suke-san's Goodbye",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu", "Suke-san"],
        "premise": "At Hokkaido, Suke-san says goodbye to each companion; he tells Obia 'You are our companion' as a fact, then climbs his hill and raises his tail once.",
        "key_event": "Suke-san reaches the top of his hill, turns, raises his full curled tail straight up — then is gone over the other side.",
    },
    118: {
        "title": "Daru's Goodbye",
        "characters": ["Ako-chan", "Dango", "Obia", "Daru", "Gabu"],
        "premise": "At the Mediterranean coast, Daru leaps ashore, checks Ako-chan's face for any hesitation when she says 'we will meet again,' and then runs home in a joyful wide curve.",
        "key_event": "Daru runs away in a wide joyful curve — exactly as he always moved — and is gone between the rocks.",
    },
    119: {
        "title": "Gabu's Goodbye",
        "characters": ["Ako-chan", "Dango", "Obia", "Gabu"],
        "premise": "Gabu says goodbye to each absent companion by name and what they gave, then kneels to Ako-chan's height and says 'I am glad I met you.'",
        "key_event": "Ako-chan kneels to Gabu's level and they are eye to eye — Gabu says 'I am glad I met you' and walks into the olive grove.",
    },
    120: {
        "title": "We Are Home",
        "characters": ["Ako-chan", "Dango", "Obia"],
        "premise": "Ako-chan and Dango return to the front garden in England; a hedgehog says 'Welcome home' and Ako-chan opens her diary to the last blank page.",
        "key_event": "Ako-chan writes just two words on the last page of her diary: 'We're home.'",
    },
}
