STORIES_S1_P08 = [
    {
        "ep": 90,
        "title": "Dango's Nose — Antarctic Edition",
        "text": 'The next morning, Dango did something unusual.\n\nHe walked to the edge of camp. He pushed both front paws into the snow, deep, until his chin nearly touched the surface. He breathed in. Long and slow. Then again.\n\nAko-chan watched from a few steps away.\n\nDango lifted his head. He looked south-east. He held very still.\n\n"Dango?" said Ako-chan. "What is there?"\n\nDango did not answer. He stood up slowly. Then he began to walk. Not toward the south, where the coordinates pointed. South-east.\n\nAko-chan followed. The others came behind.\n\nHis collar was gold. Not orange — not worried. Gold.\n\nHe walked for a few minutes. Then he stopped and sat down. He looked back at Ako-chan.\n\nShe looked ahead. She could not see anything. Only ice and sky.\n\nBut she had learned to trust him.\n\n"All right," she said. "We will go that way."\n\nSuke-san stepped forward without a word. Obia walked beside him. One by one, they all followed Dango.\n\nAko-chan wrote in her diary: Dango\'s body knew first.\n\nHe was not afraid. He just knew.',
    },
    {
        "ep": 91,
        "title": "Riro's Diving Report",
        "text": 'Riro was gone when Ako-chan woke up.\n\nShe was not worried. She knew where he went when he disappeared before the others were awake.\n\nAn hour later, he came back. He carried something in his hands. He set it on the ice in front of Ako-chan. It was a flat piece of ice, about the size of her hand. Something was carved into it. Lines and numbers.\n\n"A narwhal gave this to me," said Riro. "It waited several days for someone to ask. Narwhals do not give directions easily. They are careful animals."\n\nObia leaned down and studied the carving.\n\n"These are coordinates," it said. "Twelve kilometers south."\n\nRiro pointed. "That way."\n\n"That is the same direction as Dango\'s nose," said Ako-chan.\n\nShe looked at Dango. He was already looking south.\n\n"The narwhal\'s mother and father also knew the sound," said Riro. "It has been there longer than they can remember."\n\nAko-chan thought about what that meant. She looked at the small piece of ice with its careful lines.\n\nTwelve kilometers. Same direction as Dango had walked. Something very old, waiting under the ice.',
    },
    {
        "ep": 92,
        "title": 'A Sound Not from the Wind',
        "text": 'There was no wind.\n\nThere had been no wind since before lunch. The air was perfectly still. The camp was completely quiet.\n\nThen Daru stopped moving.\n\nHe put both hands flat on the ice. He pressed down hard. His eyes went wide.\n\n"Something is going through my shell," he said. "A sound. Very low. Like the vibration in Patagonia — but stronger."\n\n"From which direction?" said Obia.\n\n"I cannot tell," said Daru. "It comes from all below."\n\nGabu raised his head. He turned it very slowly. Left. Right. He held it pointing toward the south.\n\n"From the south," said Gabu. "The signal comes from the south."\n\nObia activated its sensors. Everyone waited.\n\n"Confirmed," said Obia. "An intentional low-frequency transmission. Not natural. Not random. It repeats at a fixed interval."\n\nDaru was still pressing his hands on the ice.\n\n"In Patagonia the sound was quiet," he said. "This is much louder."\n\nGabu kept looking south. "We are closer now."\n\n"Yes," said Obia. "We are much closer."\n\nAko-chan listened. She could not hear the sound herself. But she could see it in Daru\'s face, and in the way Gabu did not look away from the south.',
    },
    {
        "ep": 93,
        "title": 'A Shadow in the Valley',
        "text": 'They went down into the valley together.\n\nThe walls rose on either side. The sound was clearer here — not loud, but steady and low, like a slow pulse.\n\nObia stopped.\n\n"There," it said.\n\nAko-chan looked. At the far end of the valley, something sat perfectly still. It was small and round and dark against the white. It had not moved at all.\n\n"Biological signal," said Obia. "Small. Body temperature is normal."\n\nDango stepped forward. He looked at the small shape, then at Ako-chan. His collar was gold. Not orange. Not worried. Gold.\n\nAko-chan trusted that.\n\n"All right," she said. "Let us go closer."\n\nThey walked forward slowly. The small shape did not move. It did not turn. It did not look at them.\n\nBut somehow Ako-chan felt that it knew they were coming. She did not know why she felt that. She just did.\n\nDango walked beside her. His ears were relaxed. His step was calm.\n\nWhatever was waiting at the end of the valley was not a threat. Dango\'s body was sure of that.\n\nAko-chan kept walking toward it.',
    },
    {
        "ep": 94,
        "title": 'I Have Been Waiting',
        "text": 'The chick stood up.\n\nIt was small, but it stood straight. Its back was perfectly upright. Its flippers hung at its sides. It looked at all of them at once.\n\nThen it spoke.\n\n"I am Pen-san," it said. "I have been waiting for you."\n\nEveryone was quiet.\n\nPen-san looked at Ako-chan. "Your name is Ako-chan."\n\nThen at the dog beside her. "And you are Dango."\n\n"How do you—" Ako-chan started.\n\nPen-san continued. It said each name in turn. Obia. Gabu. Daru. Suke-san. Riro.\n\nAll seven names. All correct.\n\nAko-chan looked at Dango. Dango looked at Ako-chan. She looked at Obia. Obia was very still.\n\n"How do you know our names?" Ako-chan asked.\n\nPen-san blinked for the first time.\n\n"I knew you were coming," it said. "I have known for a long time. I cannot explain it better than that."\n\nIt settled back down onto the ice, perfectly still again.\n\nAll seven of them looked at each other. Then they looked at the small round penguin chick who had been waiting in this valley for them.\n\nNobody said anything for a while.',
    },
    {
        "ep": 95,
        "title": 'Colonel Adelie',
        "text": 'Movement. Behind a blue-grey rock at the edge of the valley.\n\nA small penguin stepped out. It was very small — smaller than any penguin Ako-chan had seen — but the way it moved was not small at all.\n\nIt looked at all seven of them, fast and sharp. One second. Two seconds. Then it had finished.\n\n"Colonel Adelie," it said. "Guard and instructor to Pen-san. I will explain the situation."\n\nIt did not wait for them to answer.\n\n"I have been observing this coast for three months," it said. "I brought Pen-san to this valley to keep it away from the interference of the structure below the ice. Close enough to hear. Far enough to wait properly."\n\n"How did you know we were coming?" Ako-chan asked.\n\n"Narwhals," said the Colonel. "And whales. And seabirds." It looked at her directly. "The whole south has known you were coming. You have been noticed at every step."\n\nAko-chan thought about Riro\'s narwhal, and the orca in October, and the albatross at the Drake Passage.\n\n"That is a long list," said Suke-san.\n\n"Yes," said the Colonel. "You have traveled far.',
    },
    {
        "ep": 96,
        "title": "The Colonel's Briefing",
        "text": 'Colonel Adelie drew lines in the snow with the tip of one flipper.\n\n"Eight kilometers of flat ice from here," it said. "Then an ice ridge. The wind at the ridge is not regular. You must be careful."\n\nIt drew a mark on the line.\n\n"On the other side of the ridge, there is one access shaft. About one meter wide. That is the only way down to the structure."\n\n"What is at the bottom?" asked Ako-chan.\n\n"A structure. Large. Below the ice surface."\n\nObia was very still. Ako-chan could see it comparing the Colonel\'s information to its own scan data. She could see it in the way its eyes moved.\n\n"At the ridge," the Colonel continued, "there is electromagnetic interference. Strong. It will affect some systems." It looked at Obia for one second. Then it continued. "The access point is at two hundred and ten degrees, magnetic south."\n\nObia spoke. "Your data matches my scan exactly."\n\nThe Colonel nodded once. "Good. Then we are in agreement."\n\nAko-chan was writing as fast as she could. She filled half a page.\n\nBeside her, Suke-san had straightened without seeming to notice. His shoulders were back. His chin was up.',
    },
    {
        "ep": 97,
        "title": "The Emperor's Eyes",
        "text": 'One morning, Pen-san crossed the camp and sat beside Ako-chan.\n\nIt had not done this before. It just came and sat. Very close. Its round body pressed gently against her side.\n\nAko-chan went still.\n\nPen-san looked straight ahead. It did not explain itself.\n\nThen it looked up at her.\n\nIts eyes were dark. Very round. Very still. The largest eyes Ako-chan had ever seen. She had noticed them before — everyone had, the first day. But this was different. This was close. This was looking back at her.\n\nShe tried to look away. She could not.\n\nShe tried to think about breakfast. She could not think about breakfast.\n\nShe opened her mouth.\n\n"...Can I hold you?" she said.\n\nThen she stopped. She had not decided to say that. The words had come out before she chose them.\n\nPen-san blinked.\n\n"If you like," it said.\n\nAko-chan picked up Pen-san carefully. Pen-san was warm and round and its down was impossibly soft.\n\nFrom behind her, she heard a very small sound. Like a short breath.\n\nShe looked back.\n\nDango\'s mouth was a little open. His collar had turned orange.\n\n"Ah," he said. Very quietly.\n\nPen-san turned its head to look at Dango. It looked very calm. Very comfortable. Very settled.\n\nDango looked at Pen-san. He looked at Ako-chan. He looked at Pen-san again.',
    },
    {
        "ep": 98,
        "title": "Dango's Resistance",
        "text": 'Ako-chan held Pen-san and walked slowly around the camp.\n\nDango followed.\n\nHe walked in circles around her feet. He tried very hard not to look at Pen-san. He looked at the ice instead. He looked at the sky. He looked at his own front paws.\n\nThen Pen-san looked at him.\n\nThose eyes opened wide again. Dark. Round. Quiet.\n\nDango\'s front left paw moved sideways. He had not meant to move it.\n\nHe stopped. He looked at his paw. He moved it back.\n\nPen-san\'s eyes were still on him.\n\nDango\'s paw moved sideways again.\n\nHe made a sound. It was not a word. Something between no and a sigh.\n\nThen he was pressed against Ako-chan\'s leg. He had not really decided to go there. But there he was.\n\nHis collar was orange. At the very edges, near the clasp, a little gold.\n\nGabu watched from his shelter. "He is losing," he said.\n\nObia stood beside Gabu. "He is trying very hard," it said. "That is different."\n\nGabu was quiet for a moment. "Yes," he said. "That is a fair thing to say.',
    },
    {
        "ep": 99,
        "title": 'The Colonel and Suke-san',
        "text": 'Colonel Adelie came to Suke-san in the afternoon.\n\nIt walked directly to him. No greeting.\n\n"You were on patrol last night," it said.\n\nSuke-san looked at it.\n\n"...You noticed," he said.\n\n"Yes," said the Colonel. "I noticed at midnight. You had already been walking for two hours."\n\nSuke-san did not answer.\n\n"I also noticed," said the Colonel, "that you adjusted your circuit. When the wind shifted at two in the morning, you moved your path to stay upwind of the camp."\n\nSuke-san\'s ears moved very slightly. He looked at the Colonel.\n\nA pause.\n\nThen both of them nodded. At exactly the same moment. A very small nod. Very clean.\n\nThe Colonel looked out toward the ridge to the south.\n\n"I would like to arrange a joint patrol," it said. "Tonight. After the others sleep."\n\n"Yes," said Suke-san.\n\n"Good," said the Colonel. It turned and walked away.\n\nAko-chan had seen the whole exchange from ten steps away. She wrote in her diary later: The Colonel and Suke-san did not need many words. I think they already understood each other from the first moment.',
    },
    {
        "ep": 100,
        "title": "Pen-san's Memory",
        "text": 'Evening. The camp was quiet. Most of the others had gone inside.\n\nPen-san sat beside Ako-chan at the edge of the camp. They both looked south.\n\nPen-san spoke first.\n\n"When I was in the egg," it said, "I could hear the sound."\n\nAko-chan turned to look at it.\n\n"From below," said Pen-san. "Low and steady. It came up through the rock where the egg was kept. It was always there. I did not know it was unusual. I thought all eggs heard a sound like that."\n\n"When did you learn it was unusual?" Ako-chan asked.\n\n"When I hatched," said Pen-san. "The sound was still there. It had been the first thing I heard. After that, I heard wind and birds and the Colonel\'s voice. But the very first thing — the very first — was that sound from below the ice."\n\nIt was quiet for a moment.\n\n"That is why I waited," said Pen-san. "The sound had been there before me. I thought it was right to wait for what was coming next."\n\nAko-chan did not write in her diary right away. She sat with the words for a long time first.',
    },
    {
        "ep": 101,
        "title": 'The Strategy Meeting',
        "text": 'Colonel Adelie drew the terrain in the snow.\n\n"I will now assign roles," it said. It looked at Suke-san.\n\n"East flank."\n\n"Understood," said Suke-san. Immediately. Without hesitation.\n\n"Obia — first in through the access shaft. You have the best sensors."\n\n"Yes," said Obia.\n\n"Daru — with Obia. You will observe and report what you see."\n\nDaru looked very pleased. "What about me?" he started to ask. Then he understood that the Colonel had just answered that question. "Oh. Yes. I understand."\n\n"Riro — undersea approach to the access point."\n\nRiro nodded.\n\n"Gabu — ridge position. Watch the weather."\n\nGabu had opened his mouth to say he was fine at the rear. The Colonel had already moved on. Gabu closed his mouth.\n\n"Ako-chan — center." The Colonel looked at her steadily. "You hear what no one else hears. Use that."\n\nAko-chan wrote the words down before she could forget them.\n\n"Pen-san — with Ako-chan."\n\nPen-san inclined its head. Very slightly. Like an emperor agreeing to terms.\n\nEveryone was in position. The plan was made.',
    },
    {
        "ep": 102,
        "title": 'The Gate Opens',
        "text": 'The structure was not above the ice. It was under it.\n\nA flat metal shape was set into the white surface — smooth and dark and very old. There were no handles. There were no markings. Just a wide door, flush with the ice, pointing straight at the sky.\n\nObia walked forward to look at it.\n\nThe door opened.\n\nNobody moved.\n\nObia stopped. It had not touched anything. It had not pressed any button or spoken any word. It had simply walked close and the door had opened on its own.\n\n"You did not do that," said Suke-san.\n\n"No," said Obia. "I did not."\n\nThe open door showed stairs going down. The stairs were lit from below. The light was steady and pale blue. It did not flicker.\n\nDaru leaned forward to look. "It just opened?"\n\n"Yes," said Obia.\n\n"By itself?"\n\n"Yes."\n\nAko-chan stared at the door. It had opened for Obia. It had waited for Obia. Someone had built this door knowing that Obia would arrive. Someone had planned that far ahead.\n\nShe looked at Obia. Obia was looking at the stairs below.\n\nNobody spoke. Then Colonel Adelie said, "We go down."\n\nThey went down.\n',
    },
    {
        "ep": 103,
        "title": "Gabu's Observation",
        "text": 'The stairs went down for a long time. The walls were smooth stone and pale metal. The light came from long strips set into the ceiling. It was warm underground. Warmer than Ako-chan expected.\n\nAt the bottom, a wide corridor led ahead. The group stopped there for a moment.\n\nGabu was quiet. He walked slowly and did not speak. He was watching Obia.\n\nThen Gabu turned his head.\n\n"Obia," he said.\n\nHis voice was quiet. It was not angry. It was not accusing. It was careful and clear.\n\n"This place knows you," said Gabu.\n\nEveryone stopped.\n\nThat was all Gabu said. He did not ask a question. He did not demand an explanation. He simply said what he had seen.\n\nThe door had opened for Obia. The lights were on. The stairs were ready. Everything here had been waiting for them — waiting for Obia specifically.\n\nObia stood very still.\n\n"...Yes," said Obia.\n\nOne word.\n\nDango looked up at Obia. Riro pressed a paw to its face. Daru opened its mouth and then closed it. Suke-san\'s tail was very still.\n\nAko-chan watched Obia. Obia was not looking away.\n\n"Yes," Obia said again. Quieter this time. "This place knows me."\n',
    },
    {
        "ep": 104,
        "title": 'Everyone is Looking',
        "text": 'Nobody walked.\n\nThey were all in the corridor, still and quiet. The pale light hummed above them. The air was warm and very still.\n\nGabu had not moved. He was watching Obia with his careful dark eyes. Pen-san was watching too. Colonel Adelie stood straight and said nothing.\n\nDango sat down slowly on the floor. His collar was deep orange.\n\nSuke-san was looking at Obia. Riro was looking at Obia. Daru was looking at Obia.\n\nThey were all looking at Obia.\n\nObia stood in the centre of the corridor. It was not a large space. The walls were close. There was nowhere else to go.\n\nFor a moment, nothing happened.\n\nThen Obia turned to face them all.\n\n"...There are things I must tell you," Obia said.\n\nIt did not look away. It did not step back. It did not try to change the subject or move forward or ask everyone to keep walking.\n\nIt said the words and stayed where it was.\n\nAko-chan took a breath.\n\n"All right," she said.\n\nThat was all. Just those two words. And everyone in the corridor waited, in the warm pale light, for Obia to begin.\n',
    },
    {
        "ep": 105,
        "title": "Obia's Confession, Part One",
        "text": 'Obia began to speak.\n\n"I was made by a scientist," it said. "I was not born. I was built. I was given one purpose: to travel with you, to watch you, and to record what I observed."\n\nNobody moved.\n\n"The reason I appeared in January was not chance. I was placed near your home on the first day of the year. Everything that followed was planned."\n\nAko-chan\'s face changed. She had started to say something — and then she stopped. She was not afraid. She was not shouting. She was thinking. Taking it in. Turning it over very slowly inside.\n\nObia continued. "The anomalies — the whale in the harbour, the frozen sea, the dry riverbed — none of them were accidents. Someone made them happen. Someone designed each one. And I was sent to watch how you responded."\n\n"The structure here, under the ice, is the centre of it all. This is where the signals came from. This is where the records were sent."\n\nDango made a low sound in his throat. His collar was deep orange. He did not move, but his eyes did not leave Obia\'s face.\n\nObia looked back at him.\n\n"I have more to say," said Obia. "But that is the first part."\n\nIt waited.\n',
    },
    {
        "ep": 106,
        "title": "Obia's Confession, Part Two",
        "text": '"I watched you," said Obia. "That was my purpose. I watched everything. I recorded everything."\n\nEveryone listened.\n\n"But as I watched, I changed."\n\nObia paused. It chose the next words carefully.\n\n"There was a moment in Patagonia. The wind was very strong and the tent was pulling apart. Gabu was inside the shelter I was holding. I could have let go. My purpose was to observe — not to act. But I did not let go. I held the bracket because Gabu was inside."\n\nGabu was still. He looked at Obia without blinking.\n\n"After that," said Obia, "I did not stop choosing to help. Each time, I chose it. Not because I was built to help. Because I wanted to. Because you were the ones I was with."\n\nIt looked at each of them — Dango, Riro, Suke-san, Daru, Gabu, Pen-san, Colonel Adelie, Ako-chan.\n\n"I was sent to observe," it said. "But somewhere in the middle of the year, that became less important to me than being useful to you. That is a change I did not plan. That is my answer."\n\nIt stopped speaking.\n\nThe corridor was very quiet.\n\nDango\'s collar was still orange. But he had not growled again.\n\nAko-chan said nothing. She was listening to the space the words had left.\n',
    },
    {
        "ep": 107,
        "title": "Pen-san's Verdict",
        "text": 'Nobody spoke for a long time.\n\nThe pale light was steady. The air was warm. Everything waited.\n\nThen Pen-san moved.\n\nIt stood very straight, as it always did. It looked at Obia with its enormous dark eyes. It was not a quick look. It was a long, careful look.\n\nThen Pen-san said: "That is enough."\n\nThree words.\n\nColonel Adelie said: "We move forward."\n\nTwo words.\n\nGabu looked at the ceiling for a moment. Then he looked back down and began to walk.\n\nRiro lowered its paws from its face.\n\nSuke-san turned toward the corridor ahead.\n\nDaru said "oh" very quietly and began to walk too.\n\nDango sat where he was. He was still looking at Obia. Obia was still looking at him.\n\nA long moment passed.\n\nThen Dango stood up. He walked across the corridor. He went to Obia\'s side and sat down there.\n\nHis collar changed.\n\nOrange to gold.\n\nObia looked down at him. It did not speak.\n\nDango did not speak either.\n\nAko-chan watched all of this. She felt something move in her chest — not quite a word, not quite a feeling. Something between the two.\n\nShe looked at Dango\'s gold collar.\n\n"All right," she said softly. "Let\'s go."\n',
    },
    {
        "ep": 108,
        "title": 'On the Monitor',
        "text": 'At the centre of the room stood a large screen.\n\nIt was much taller than Ako-chan. Much wider. The frame was dark metal. The screen itself was off — no, not off. It was waiting.\n\nWhen they came close, the screen turned on.\n\nIt showed a room. A bright, white room, somewhere else entirely — not here, not anywhere they had been. There was a desk with equipment on it. There were papers. There was a window showing only white sky.\n\nAnd there was a person.\n\nA lab coat. Dark hair. Standing with their back to the camera.\n\nNot moving.\n\nThe room around Ako-chan was quiet. Everyone had stopped.\n\nThen the figure on the screen spoke.\n\n"You have arrived," the voice said.\n\nIt was a clear voice. Not loud. Not hurrying. It filled the room easily, as if it had been made for this space.\n\nThe figure did not turn around.\n\nDango pressed against Ako-chan\'s leg. His collar was gold.\n\nAko-chan looked at the screen. The white-coated figure. The white room. The pale sky beyond the window.\n\n"Who are you?" she said.\n\nThe figure on the screen was still for a moment.\n\n"That is what I will tell you," the voice said.\n',
    },
    {
        "ep": 109,
        "title": 'The Voice',
        "text": '"It took a little longer than I calculated," the voice said.\n\n"I expected you in late November. You arrived in December. That is not a failure. It is simply what happened."\n\nThe figure still had its back to them.\n\nAko-chan stepped closer to the screen. She looked at the lab coat. She looked at the shape of the person inside it.\n\n"Are you the one," said Ako-chan, "who arranged all of this?"\n\nShe did not shout. She was not afraid. She was asking the way she would ask anything — directly, to make sure she had it right.\n\nThe figure on the screen was quiet for a moment.\n\n"Yes," it said.\n\nJust that one word.\n\nAko-chan nodded slowly. She was not surprised. She was not unsurprised. She was just taking it in.\n\nShe looked at the lab coat. The shape of the person inside it.\n\nA name came to her. She did not know why. It came the way some things came to her — without warning, without explanation. Like an animal\'s voice arriving before she had turned around.\n\n"...Yu-chan?" she said.\n\nIt was half a question. She was not sure she had said it aloud.\n\nThe figure on the screen was very still.\n\nThen: "...Yes," it said.\n\nThere was something almost ordinary about that name. Not a grand name. Not a title. Just: Yu-chan. And she had known it from somewhere she could not name.\n\nDaru said, very quietly, "Yu-chan."\n\nNobody else spoke.\n\nAko-chan held her diary in both hands. The screen was very large and very bright. The white room beyond the glass looked clean and quiet.\n\n"Why?" said Ako-chan.\n\n"That," said Yu-chan, "I will explain."\n',
    },
    {
        "ep": 110,
        "title": 'The Reason for the Test',
        "text": 'Yu-chan began to speak. The voice was calm. The words came one at a time.\n\n"I needed to know something," said Yu-chan. "I needed to know whether people are worth keeping. Whether human beings — given the choice between helping and not helping, between doing the right thing and doing the easy thing — will choose correctly."\n\nAko-chan listened.\n\n"The anomalies were all mine. The whale in the harbour. The frozen sea. The drought. The disappearing fish. I made them happen. I stopped them when the right answers came. Every one was a test."\n\n"And you," said Yu-chan, "were the test I watched most closely. I chose you because you can understand animals. You hear what most people cannot hear. I wanted to see how a person like that travels. Whether that gift makes a difference."\n\nAko-chan stood very still.\n\n"What about Pen-san?" she asked.\n\nA pause.\n\n"Pen-san," said Yu-chan, "was not part of my plan. The connection between Pen-san and the structure — I did not design that. Pen-san heard the signal from inside the egg. I did not know that was possible. Some things do not follow the calculations."\n\nFor the first time, Yu-chan sounded almost surprised.\n\nPen-san stood quietly and said nothing.\n',
    },
    {
        "ep": 111,
        "title": 'The Answer',
        "text": 'Yu-chan was quiet for a long time.\n\nThe screen showed only the white-coated back, the white room, the pale window. Nothing moved there.\n\nAko-chan waited. Everyone waited.\n\nThen: "I have looked at Obia\'s data," said Yu-chan. "All of it. Every record, from January to today. Every anomaly, every decision, every deviation from the original program."\n\nA pause.\n\n"Including all that Obia chose."\n\nAnother pause, longer.\n\n"...You pass."\n\nNobody moved.\n\nThe words were so simple. Two words. You pass. But they held the whole year inside them — every cold morning, every hard climb, every new place, every hard moment, every choice.\n\nDaru made a small sound. Riro pressed both paws slowly to its face.\n\nGabu closed his eyes for a moment.\n\nDango pressed against Ako-chan\'s side.\n\n"Thank you," said Yu-chan. "All of you."\n\nThe voice in the room was quieter than before. Something in it had changed — not weak, not breaking, just different. More careful. More real.\n\nAko-chan felt something behind her eyes. She blinked.\n\nShe did not write anything in her diary. She just held it.\n\nThe screen was very bright.\n\nOutside, somewhere far away, it was still Antarctica.\n',
    },
    {
        "ep": 112,
        "title": 'The Anomalies Stop',
        "text": 'Yu-chan turned to the desk.\n\nFrom where Ako-chan stood, she could not see Yu-chan\'s face — only the lab coat, the movement of hands, the sounds of equipment.\n\nThen Obia\'s terminal blinked.\n\nA list appeared — numbers, coordinates, codes. One by one, they began to change.\n\nSIGNAL 01 — TERMINATED\nSIGNAL 02 — TERMINATED\nSIGNAL 03 — TERMINATED\n\nThe list was long. Twenty-one items. One by one, line by line, each signal went dark.\n\nAko-chan watched the screen. She read some of the codes — they meant nothing to her, but she could feel what they were. Each one was a place. Each one was a problem that had stopped.\n\nSomewhere, the whale was back in the open sea. Somewhere, a river was flowing again. Somewhere, the sky had cleared.\n\nSIGNAL 21 — TERMINATED\n\nThe last one stopped.\n\nALL SIGNALS TERMINATED.\n\nObia looked at the terminal for a moment. Then it closed the terminal. It did this slowly and quietly, the way you close something that has served its purpose.\n\nThe world was back.\n\nThe room was very still.\n\n"It is done," said Yu-chan.\n\nNo one replied. The silence was the reply.\n',
    },
    {
        "ep": 113,
        "title": 'The Last Question',
        "text": 'The room was quiet.\n\nYu-chan had turned slightly, but still had not shown its face. The lab coat. The hands on the desk. The window.\n\nAko-chan had one more question.\n\n"Why won\'t you show your face?" she said.\n\nYu-chan was still for a moment.\n\n"A face is not important," it said.\n\nIts voice was calm. Not unkind. Just very clear.\n\n"What matters is what you did. Not what I look like. Not my name, really — though you have that now. What matters is what happened. Where you went. What you chose. Who you became."\n\nAko-chan thought about that.\n\nShe did not push further. She did not ask again. She had heard the answer and it was enough. It was a real answer, even if she did not fully understand it yet.\n\n"Safe journey home," said Yu-chan.\n\nThe monitor went dark.\n\nThe room was quiet again — a different quiet than before. Not waiting. Finished.\n\nDango put his nose against Ako-chan\'s hand.\n\nGabu looked at the dark screen for a moment. Then he turned and began to walk toward the corridor.\n\nSuke-san followed.\n\nRiro followed.\n\nOne by one, they all turned and walked. Up the stairs, through the corridor, back toward the door in the ice.\n\nBack toward the light.\n',
    },
    {
        "ep": 114,
        "title": "The Colonel's Salute",
        "text": "Colonel Adelie stood before them.\n\nIt faced the group — all nine of them lined up on the ice. Then it took one step back, drew itself fully upright, and gave a formal salute.\n\nA proper one. Sharp and clean.\n\nIt held the salute and looked at Ako-chan.\n\nAko-chan stood straight. She was not sure what to do, so she nodded. Seriously. The way she nodded when she meant something.\n\nColonel Adelie moved to the next one.\n\nSuke-san.\n\nSuke-san's front paw came up immediately. Clean and sharp, exactly matching the Colonel's. The best return salute of the day. Colonel Adelie held the salute for just a moment longer with Suke-san than with anyone else.\n\nNext: Riro. It put a paw to its face, which was what Riro did.\n\nThen: Daru.\n\nDaru looked at Gabu. Gabu gave no guidance. Daru thought. Then it dipped its shell down and scrambled — but it stayed upright. It managed. It held the position.\n\nIt looked pleased with itself.\n\nGabu. Obia. Dango. Pen-san.\n\nEach in turn. Each acknowledged.\n\nWhen the Colonel finished, it stepped back into place beside Pen-san. It said nothing. It did not need to.\n\nThe salute was the words.\n",
    },
]
