STORIES_S1_P07 = [
    {
        "ep": 58,
        "title": "The Last Port",
        "text": "The port was small and cold. The buildings were low. The water was dark grey.\n\nThis was the last port before the south. There was no land after this — only ice.\n\nAko-chan stood on the dock and looked at the town behind her. The others stood beside her.\n\n\"Ready?\" she said.\n\nDango's collar glowed orange. He was ready.\n\nGabu looked at the town for a long time without speaking. \"We are leaving the last streets,\" he said.\n\n\"Yes,\" Ako-chan said.\n\nDaru was already on top of the backpack. He spread all four legs wide. \"This is a very good position for the view.\"\n\nRiro was in the harbour water. Suke-san stood at the edge of the dock, looking south.\n\nThey walked onto the new boat. It was larger than the last one, built for cold water.\n\nObia checked the ropes and the hull and the engine. \"Everything is ready.\"\n\nThe boat moved out. The port grew smaller. Ako-chan watched until she could not see it clearly anymore.\n\n\"What is next?\" Daru asked.\n\n\"Ice,\" Obia said. \"And after the ice, what we came for.\"\n\nThe sea was flat and grey. Everyone faced south.",
    },
    {
        "ep": 59,
        "title": "Drake Passage",
        "text": "The Drake Passage began with no warning.\n\nOne hour the sea was flat. The next, the waves were as tall as the sides of the boat. The wind hit like something solid.\n\nGabu went to his shelter and closed it from inside.\n\nDaru tucked his head into his shell.\n\nRiro pressed against the inside wall of the water unit.\n\nDango lay flat on the floor with all four legs stretched wide. His collar was red.\n\nSuke-san sat with his tail down. He did not say anything.\n\nEach morning of the trip so far, Gabu had stepped out of his shelter and said: \"Today will be a good day.\"\n\nHe did not say it today.\n\nHe did not say it the next day either.\n\nNo one mentioned this. But everyone noticed.\n\nAko-chan held the side of the boat and looked out. Rain came in hard against her face. She did not go inside.\n\nObia stood at the helm. No matter how much the boat moved, Obia did not move. Just watched the sea and the waves.\n\nThe Drake Passage lasted three days.\n\nNo one talked much. They just waited, and held on.",
    },
    {
        "ep": 60,
        "title": "No Turning Back",
        "text": "On the fourth day, the waves became small.\n\nThe wind dropped. The sky went from dark grey to pale and clear.\n\nGabu pushed open his shelter and stepped out slowly. He looked at the sky for a long time.\n\nHe did not say \"Today will be a good day.\" He just looked.\n\nAko-chan looked at the southern sky. The blue here was different from any blue she had seen before. It was deeper. Very still.\n\nSuke-san stood at the side of the boat. His tail was up again. He looked south for a while, then said: \"We cannot go back now.\"\n\nNo one answered.\n\nBut Dango moved closer to Ako-chan. Riro pressed both paws to its face and looked south. Daru stretched one leg out from his shell, then pulled it back in.\n\nGabu said, \"I know.\"\n\nThat was all.\n\nAko-chan took out her notebook. She sat with it for a while without writing. Then she wrote:\n\n*We passed through the Drake Passage. The sky is a different blue now. We cannot go back. I do not think any of us wants to.*\n\nShe closed the notebook. The boat moved on.",
    },
    {
        "ep": 61,
        "title": "White Mountain",
        "text": "Something white was floating in the water ahead.\n\nAt first, Ako-chan thought it was a cloud sitting on the sea. Then it grew larger as they came closer. And larger still.\n\nIt was made of ice. It rose up from the water like a mountain. Its sides were blue-white. It was very quiet.\n\nDango stood at the front of the boat and pointed his nose toward it. He did not bark.\n\nDaru stretched out his neck as far as it would go and stared.\n\nRiro came up beside the boat and looked for a long time. \"I have not seen one this large,\" Riro said.\n\nGabu did not move. He just looked. His eyes were steady and wide.\n\nSuke-san said quietly: \"It is real.\"\n\nAko-chan opened her notebook. She wrote:\n\n*I saw it. It was really there.*\n\nThen she looked up again. The iceberg was already passing on the left side of the boat. It moved very slowly.\n\nObia watched it but said nothing.\n\nAfter it was gone, no one spoke for a long time.\n\n\"How many more are there?\" Daru asked.\n\n\"Many,\" Obia said.\n\nEveryone went quiet again.",
    },
    {
        "ep": 62,
        "title": "Something Under the Ice",
        "text": "Late that night, Riro slipped into the water.\n\nThe sea was very cold. Riro did not come back up for a long time.\n\nWhen Riro returned to the side of the boat, something was different. Still.\n\n\"What happened?\" Ako-chan asked.\n\n\"Something spoke to me down there,\" Riro said. \"An orca. It swam up from very deep.\"\n\n\"What did it say?\"\n\n\"There is something under the ice,\" Riro said. \"Not a natural thing. Something made. It has been there for a very long time.\"\n\nObia came to the side of the boat. \"Where?\"\n\n\"South. Deep under the ice. The orca would not go closer. It said the sound from it travels for many kilometres.\"\n\nEveryone was quiet.\n\nAko-chan looked at Obia. Obia was looking at the dark water.\n\n\"Did you know?\" Ako-chan asked.\n\n\"I thought there might be something,\" Obia said. \"Now I know.\"\n\n\"Is it what we came for?\" Suke-san asked.\n\nObia did not answer for a moment.\n\n\"Yes,\" Obia said. \"I think it is.\"\n\nThe boat moved on. Ice floated around them in the dark. No one went back to sleep for a long time.",
    },
    {
        "ep": 63,
        "title": "The Fragment",
        "text": "A hawk appeared above the boat the next morning.\n\nIt circled once, twice. Then as it turned, something fell from above. A small, dark thing. It hit the deck with a faint sound.\n\nAko-chan bent toward it.\n\nBut Obia was already there.\n\nObia picked up the object before Ako-chan could reach it. It was a small piece of metal. Dark, with rough edges. Not big — about the size of a thumbnail.\n\n\"What is it?\" Ako-chan asked.\n\n\"A piece of something,\" Obia said. \"Metal.\"\n\n\"Can I see?\"\n\nObia held it out. Ako-chan looked at the surface. There were numbers on it. Engraved small and very neat.\n\nShe looked up at Obia.\n\nObia's face had not changed. But the pause before handing it over — it had been very quick. Almost too quick.\n\nAko-chan gave the fragment back.\n\nObia put it away carefully.\n\nAko-chan watched where Obia put it. Then she opened her notebook and wrote one line:\n\n*Obia moved before I did.*\n\nShe did not write anything more. The hawk was gone. The sky was pale and empty.",
    },
    {
        "ep": 64,
        "title": "Why",
        "text": "In the evening, Suke-san walked over to Obia. He sat beside the rail and looked at the sea for a while without speaking.\n\nThen he said: \"Why do you help us?\"\n\nObia turned to look at him.\n\n\"We do not know where you came from,\" Suke-san said. \"We do not know who made you. But you built the shelters. You fixed the boat. You stood beside us in the storm.\" He paused. \"Why?\"\n\nObia looked at the sea for a moment.\n\n\"Because it is important,\" Obia said.\n\n\"That is all?\"\n\n\"That is all.\"\n\nSuke-san was quiet. He looked at Obia for a long time. His tail moved — not fast, just once.\n\n\"I do not understand it,\" he said at last. \"But I believe you.\"\n\nHe stood up and walked away.\n\nObia watched him go. Then turned back to the sea.\n\nDango had been sitting a little way off. He had heard everything. He did not say anything. But his collar changed slowly — from red to blue.",
    },
    {
        "ep": 65,
        "title": "Do Not Forget",
        "text": "After midnight, everyone was asleep.\n\nObia stood at the front of the boat. The sky was clear and very dark. The stars here were brighter than anywhere Obia had seen them.\n\nThen the signal came.\n\nIt was short. Very short. A code that only Obia knew.\n\n*We know where you are.*\n\nAnd then:\n\n*Do not forget what you are for.*\n\nObia stood still.\n\nThe stars moved slowly. The sea moved under the boat. Everything moved except Obia.\n\nAko-chan was asleep, her notebook still open near her hand. Dango was curled beside her, his collar a quiet blue. Suke-san had one ear up, even in sleep. Gabu had pulled into his shell completely. Daru was on top of the backpack.\n\nRiro floated in the water unit, very still.\n\nObia looked at all of them.\n\nThen Obia turned back to the south.\n\nThe signal did not come again. Obia did not reply. It stayed inside, like all the signals before it.\n\nThe boat kept moving south.\n\nNo one else woke up.",
    },
]
