STORIES_S1_P09 = [
    {
        "ep": 102,
        "title": 'The Gate Opens',
        "text": 'The structure was not above the ice. It was under it.\n\nA flat metal shape was set into the white surface — smooth and dark and very old. There were no handles. There were no markings. Just a wide door, flush with the ice, pointing straight at the sky.\n\nObia walked forward to look at it.\n\nThe door opened.\n\nNobody moved.\n\nObia stopped. It had not touched anything. It had not pressed any button or spoken any word. It had simply walked close and the door had opened on its own.\n\n"You did not do that," said Suke-san.\n\n"No," said Obia. "I did not."\n\nThe open door showed stairs going down. The stairs were lit from below. The light was steady and pale blue. It did not flicker.\n\nDaru leaned forward to look. "It just opened?"\n\n"Yes," said Obia.\n\n"By itself?"\n\n"Yes."\n\nAko-chan stared at the door. It had opened for Obia. It had waited for Obia. Someone had built this door knowing that Obia would arrive. Someone had planned that far ahead.\n\nShe looked at Obia. Obia was looking at the stairs below.\n\nNobody spoke. Then Colonel Adelie said, "We go down."\n\nThey went down.\n',
    },
    {
        "ep": 103,
        "title": "Gabu's Observation",
        "text": 'The stairs went down for a long time. The walls were smooth stone and pale metal. The light came from long strips set into the ceiling. It was warm underground. Warmer than Ako-chan expected.\n\nAt the bottom, a wide corridor led ahead. The group stopped there for a moment.\n\nGabu was quiet. He walked slowly and did not speak. He was watching Obia.\n\nThen Gabu turned his head.\n\n"Obia," he said.\n\nHis voice was quiet. It was not angry. It was not accusing. It was careful and clear.\n\n"This place knows you," said Gabu.\n\nEveryone stopped.\n\nThat was all Gabu said. He did not ask a question. He did not demand an explanation. He simply said what he had seen.\n\nThe door had opened for Obia. The lights were on. The stairs were ready. Everything here had been waiting for them — waiting for Obia specifically.\n\nObia stood very still.\n\n"...Yes," said Obia.\n\nOne word.\n\nDango looked up at Obia. Riro pressed a paw to its face. Daru opened its mouth and then closed it. Suke-san\'s tail was very still.\n\nAko-chan watched Obia. Obia was not looking away.\n\n"Yes," Obia said again. Quieter this time. "This place knows me."\n',
    },
    {
        "ep": 104,
        "title": 'Everyone is Looking',
        "text": 'Nobody walked.\n\nThey were all in the corridor, still and quiet. The pale light hummed above them. The air was warm and very still.\n\nGabu had not moved. He was watching Obia with his careful dark eyes. Pen-san was watching too. Colonel Adelie stood straight and said nothing.\n\nDango sat down slowly on the floor. His collar was deep orange.\n\nSuke-san was looking at Obia. Riro was looking at Obia. Daru was looking at Obia.\n\nThey were all looking at Obia.\n\nObia stood in the centre of the corridor. It was not a large space. The walls were close. There was nowhere else to go.\n\nFor a moment, nothing happened.\n\nThen Obia turned to face them all.\n\n"...There are things I must tell you," Obia said.\n\nIt did not look away. It did not step back. It did not try to change the subject or move forward or ask everyone to keep walking.\n\nIt said the words and stayed where it was.\n\nAko-chan took a breath.\n\n"All right," she said.\n\nThat was all. Just those two words. And everyone in the corridor waited, in the warm pale light, for Obia to begin.\n',
    },
    {
        "ep": 105,
        "title": "Obia's Confession, Part One",
        "text": 'Obia began to speak.\n\n"I was made by a scientist," it said. "I was not born. I was built. I was given one purpose: to travel with you, to watch you, and to record what I observed."\n\nNobody moved.\n\n"The reason I appeared in January was not chance. I was placed near your home on the first day of the year. Everything that followed was planned."\n\nAko-chan\'s face changed. She had started to say something — and then she stopped. She was not afraid. She was not shouting. She was thinking. Taking it in. Turning it over very slowly inside.\n\nObia continued. "The anomalies — the whale in the harbour, the frozen sea, the dry riverbed — none of them were accidents. Someone made them happen. Someone designed each one. And I was sent to watch how you responded."\n\n"The structure here, under the ice, is the centre of it all. This is where the signals came from. This is where the records were sent."\n\nDango made a low sound in his throat. His collar was deep orange. He did not move, but his eyes did not leave Obia\'s face.\n\nObia looked back at him.\n\n"I have more to say," said Obia. "But that is the first part."\n\nIt waited.\n',
    },
    {
        "ep": 106,
        "title": "Obia's Confession, Part Two",
        "text": '"I watched you," said Obia. "That was my purpose. I watched everything. I recorded everything."\n\nEveryone listened.\n\n"But as I watched, I changed."\n\nObia paused. It chose the next words carefully.\n\n"There was a moment in Patagonia. The wind was very strong and the tent was pulling apart. Gabu was inside the shelter I was holding. I could have let go. My purpose was to observe — not to act. But I did not let go. I held the bracket because Gabu was inside."\n\nGabu was still. He looked at Obia without blinking.\n\n"After that," said Obia, "I did not stop choosing to help. Each time, I chose it. Not because I was built to help. Because I wanted to. Because you were the ones I was with."\n\nIt looked at each of them — Dango, Riro, Suke-san, Daru, Gabu, Pen-san, Colonel Adelie, Ako-chan.\n\n"I was sent to observe," it said. "But somewhere in the middle of the year, that became less important to me than being useful to you. That is a change I did not plan. That is my answer."\n\nIt stopped speaking.\n\nThe corridor was very quiet.\n\nDango\'s collar was still orange. But he had not growled again.\n\nAko-chan said nothing. She was listening to the space the words had left.\n',
    },
    {
        "ep": 107,
        "title": "Pen-san's Verdict",
        "text": 'Nobody spoke for a long time.\n\nThe pale light was steady. The air was warm. Everything waited.\n\nThen Pen-san moved.\n\nIt stood very straight, as it always did. It looked at Obia with its enormous dark eyes. It was not a quick look. It was a long, careful look.\n\nThen Pen-san said: "That is enough."\n\nThree words.\n\nColonel Adelie said: "We move forward."\n\nTwo words.\n\nGabu looked at the ceiling for a moment. Then he looked back down and began to walk.\n\nRiro lowered its paws from its face.\n\nSuke-san turned toward the corridor ahead.\n\nDaru said "oh" very quietly and began to walk too.\n\nDango sat where he was. He was still looking at Obia. Obia was still looking at him.\n\nA long moment passed.\n\nThen Dango stood up. He walked across the corridor. He went to Obia\'s side and sat down there.\n\nHis collar changed.\n\nOrange to gold.\n\nObia looked down at him. It did not speak.\n\nDango did not speak either.\n\nAko-chan watched all of this. She felt something move in her chest — not quite a word, not quite a feeling. Something between the two.\n\nShe looked at Dango\'s gold collar.\n\n"All right," she said softly. "Let\'s go."\n',
    },
    {
        "ep": 108,
        "title": 'On the Monitor',
        "text": 'At the centre of the room stood a large screen.\n\nIt was much taller than Ako-chan. Much wider. The frame was dark metal. The screen itself was off — no, not off. It was waiting.\n\nWhen they came close, the screen turned on.\n\nIt showed a room. A bright, white room, somewhere else entirely — not here, not anywhere they had been. There was a desk with equipment on it. There were papers. There was a window showing only white sky.\n\nAnd there was a person.\n\nA lab coat. Dark hair. Standing with their back to the camera.\n\nNot moving.\n\nThe room around Ako-chan was quiet. Everyone had stopped.\n\nThen the figure on the screen spoke.\n\n"You have arrived," the voice said.\n\nIt was a clear voice. Not loud. Not hurrying. It filled the room easily, as if it had been made for this space.\n\nThe figure did not turn around.\n\nDango pressed against Ako-chan\'s leg. His collar was gold.\n\nAko-chan looked at the screen. The white-coated figure. The white room. The pale sky beyond the window.\n\n"Who are you?" she said.\n\nThe figure on the screen was still for a moment.\n\n"That is what I will tell you," the voice said.\n',
    },
    {
        "ep": 109,
        "title": 'The Voice',
        "text": '"It took a little longer than I calculated," the voice said.\n\n"I expected you in late November. You arrived in December. That is not a failure. It is simply what happened."\n\nThe figure still had its back to them.\n\nAko-chan stepped closer to the screen. She looked at the lab coat. She looked at the shape of the person inside it.\n\n"Are you the one," said Ako-chan, "who arranged all of this?"\n\nShe did not shout. She was not afraid. She was asking the way she would ask anything — directly, to make sure she had it right.\n\nThe figure on the screen was quiet for a moment.\n\n"Yes," it said.\n\nJust that one word.\n\nAko-chan nodded slowly. She was not surprised. She was not unsurprised. She was just taking it in.\n\nShe looked at the lab coat. The shape of the person inside it.\n\nA name came to her. She did not know why. It came the way some things came to her — without warning, without explanation. Like an animal\'s voice arriving before she had turned around.\n\n"...Yu-chan?" she said.\n\nIt was half a question. She was not sure she had said it aloud.\n\nThe figure on the screen was very still.\n\nThen: "...Yes," it said.\n\nThere was something almost ordinary about that name. Not a grand name. Not a title. Just: Yu-chan. And she had known it from somewhere she could not name.\n\nDaru said, very quietly, "Yu-chan."\n\nNobody else spoke.\n\nAko-chan held her diary in both hands. The screen was very large and very bright. The white room beyond the glass looked clean and quiet.\n\n"Why?" said Ako-chan.\n\n"That," said Yu-chan, "I will explain."\n',
    },
    {
        "ep": 110,
        "title": 'The Reason for the Test',
        "text": 'Yu-chan began to speak. The voice was calm. The words came one at a time.\n\n"I needed to know something," said Yu-chan. "I needed to know whether people are worth keeping. Whether human beings — given the choice between helping and not helping, between doing the right thing and doing the easy thing — will choose correctly."\n\nAko-chan listened.\n\n"The anomalies were all mine. The whale in the harbour. The frozen sea. The drought. The disappearing fish. I made them happen. I stopped them when the right answers came. Every one was a test."\n\n"And you," said Yu-chan, "were the test I watched most closely. I chose you because you can understand animals. You hear what most people cannot hear. I wanted to see how a person like that travels. Whether that gift makes a difference."\n\nAko-chan stood very still.\n\n"What about Pen-san?" she asked.\n\nA pause.\n\n"Pen-san," said Yu-chan, "was not part of my plan. The connection between Pen-san and the structure — I did not design that. Pen-san heard the signal from inside the egg. I did not know that was possible. Some things do not follow the calculations."\n\nFor the first time, Yu-chan sounded almost surprised.\n\nPen-san stood quietly and said nothing.\n',
    },
    {
        "ep": 111,
        "title": 'The Answer',
        "text": 'Yu-chan was quiet for a long time.\n\nThe screen showed only the white-coated back, the white room, the pale window. Nothing moved there.\n\nAko-chan waited. Everyone waited.\n\nThen: "I have looked at Obia\'s data," said Yu-chan. "All of it. Every record, from January to today. Every anomaly, every decision, every deviation from the original program."\n\nA pause.\n\n"Including all that Obia chose."\n\nAnother pause, longer.\n\n"...You pass."\n\nNobody moved.\n\nThe words were so simple. Two words. You pass. But they held the whole year inside them — every cold morning, every hard climb, every new place, every hard moment, every choice.\n\nDaru made a small sound. Riro pressed both paws slowly to its face.\n\nGabu closed his eyes for a moment.\n\nDango pressed against Ako-chan\'s side.\n\n"Thank you," said Yu-chan. "All of you."\n\nThe voice in the room was quieter than before. Something in it had changed — not weak, not breaking, just different. More careful. More real.\n\nAko-chan felt something behind her eyes. She blinked.\n\nShe did not write anything in her diary. She just held it.\n\nThe screen was very bright.\n\nOutside, somewhere far away, it was still Antarctica.\n',
    },
    {
        "ep": 112,
        "title": 'The Anomalies Stop',
        "text": 'Yu-chan turned to the desk.\n\nFrom where Ako-chan stood, she could not see Yu-chan\'s face — only the lab coat, the movement of hands, the sounds of equipment.\n\nThen Obia\'s terminal blinked.\n\nA list appeared — numbers, coordinates, codes. One by one, they began to change.\n\nSIGNAL 01 — TERMINATED\nSIGNAL 02 — TERMINATED\nSIGNAL 03 — TERMINATED\n\nThe list was long. Twenty-one items. One by one, line by line, each signal went dark.\n\nAko-chan watched the screen. She read some of the codes — they meant nothing to her, but she could feel what they were. Each one was a place. Each one was a problem that had stopped.\n\nSomewhere, the whale was back in the open sea. Somewhere, a river was flowing again. Somewhere, the sky had cleared.\n\nSIGNAL 21 — TERMINATED\n\nThe last one stopped.\n\nALL SIGNALS TERMINATED.\n\nObia looked at the terminal for a moment. Then it closed the terminal. It did this slowly and quietly, the way you close something that has served its purpose.\n\nThe world was back.\n\nThe room was very still.\n\n"It is done," said Yu-chan.\n\nNo one replied. The silence was the reply.\n',
    },
    {
        "ep": 113,
        "title": 'The Last Question',
        "text": 'The room was quiet.\n\nYu-chan had turned slightly, but still had not shown its face. The lab coat. The hands on the desk. The window.\n\nAko-chan had one more question.\n\n"Why won\'t you show your face?" she said.\n\nYu-chan was still for a moment.\n\n"A face is not important," it said.\n\nIts voice was calm. Not unkind. Just very clear.\n\n"What matters is what you did. Not what I look like. Not my name, really — though you have that now. What matters is what happened. Where you went. What you chose. Who you became."\n\nAko-chan thought about that.\n\nShe did not push further. She did not ask again. She had heard the answer and it was enough. It was a real answer, even if she did not fully understand it yet.\n\n"Safe journey home," said Yu-chan.\n\nThe monitor went dark.\n\nThe room was quiet again — a different quiet than before. Not waiting. Finished.\n\nDango put his nose against Ako-chan\'s hand.\n\nGabu looked at the dark screen for a moment. Then he turned and began to walk toward the corridor.\n\nSuke-san followed.\n\nRiro followed.\n\nOne by one, they all turned and walked. Up the stairs, through the corridor, back toward the door in the ice.\n\nBack toward the light.\n',
    },
    {
        "ep": 114,
        "title": "The Colonel's Salute",
        "text": "Colonel Adelie stood before them.\n\nIt faced the group — all nine of them lined up on the ice. Then it took one step back, drew itself fully upright, and gave a formal salute.\n\nA proper one. Sharp and clean.\n\nIt held the salute and looked at Ako-chan.\n\nAko-chan stood straight. She was not sure what to do, so she nodded. Seriously. The way she nodded when she meant something.\n\nColonel Adelie moved to the next one.\n\nSuke-san.\n\nSuke-san's front paw came up immediately. Clean and sharp, exactly matching the Colonel's. The best return salute of the day. Colonel Adelie held the salute for just a moment longer with Suke-san than with anyone else.\n\nNext: Riro. It put a paw to its face, which was what Riro did.\n\nThen: Daru.\n\nDaru looked at Gabu. Gabu gave no guidance. Daru thought. Then it dipped its shell down and scrambled — but it stayed upright. It managed. It held the position.\n\nIt looked pleased with itself.\n\nGabu. Obia. Dango. Pen-san.\n\nEach in turn. Each acknowledged.\n\nWhen the Colonel finished, it stepped back into place beside Pen-san. It said nothing. It did not need to.\n\nThe salute was the words.\n",
    },
]
