STORIES_S1_P08 = [
    {
        "ep": 66,
        "title": "White",
        "text": "The coast of Antarctica appeared through the mist.\n\nAko-chan stood at the front of the boat and said nothing.\n\nShe had seen snow before. She had seen ice before. But not like this. There was so much white that it did not feel like a colour. It felt like the end of all colours.\n\nDango stood beside her. His nose went up into the air. He kept it there for a long time.\n\n\"What do you smell?\" Ako-chan asked.\n\nDango did not answer. He kept his nose in the air.\n\nGabu stepped out of his shelter and looked at the white land. He said nothing. His eyes were very steady.\n\nDaru stretched his neck out as far as it would go. \"It is bigger than I thought,\" he said.\n\nRiro pressed both paws to his face and looked over them at the white continent.\n\nSuke-san stood perfectly still. His tail was up. He faced the land.\n\nObia looked at it too. Something inside Obia made a very small sound. Then it stopped.\n\nNo one told anyone else what they felt. But everyone felt something.\n\nThe boat moved toward the white land.",
    },
    {
        "ep": 67,
        "title": "Dango Knows",
        "text": "On the ice, nothing worked the way it should.\n\nThe record device showed no signals. The map was empty. There were no landmarks. Every direction looked the same — white and flat and cold.\n\nObia turned the device in a slow circle. Then stopped. \"I cannot locate the source from here.\"\n\nAko-chan looked around. \"Which way?\"\n\nNo one answered.\n\nThen Dango began to walk. He did not run. He put his nose low and walked south-east. He stopped. Moved a little left. Then kept going.\n\nObia watched.\n\n\"Dango,\" Ako-chan said.\n\n\"Don't,\" Obia said quietly.\n\nAko-chan looked at Obia.\n\n\"Follow him,\" Obia said.\n\nThey followed. Dango walked slowly. Sometimes he stopped and checked with his nose. Then he walked again.\n\nSuke-san walked beside him for a while without speaking.\n\nObia activated all sensors at once. The device made a very faint sound — a signal. South-east.\n\nExactly where Dango had been going.\n\nDango's collar was gold.\n\nAko-chan opened her notebook and wrote: _Dango's body knew first._\n\nObia said nothing. But it had known too. Dango had been right before Obia's sensors confirmed it.",
    },
    {
        "ep": 68,
        "title": "Coordinates",
        "text": "Riro found a hole in the ice.\n\nIt was not large — just wide enough for a sea otter. The water below was very dark and very cold.\n\nRiro looked into the hole for a long time. Then looked at Ako-chan.\n\n\"May I go in?\"\n\n\"Is it safe?\"\n\n\"Cold water is always safer for me,\" Riro said.\n\nAko-chan looked at Obia. Obia said: \"It connects to open water below. Riro can swim there.\"\n\nRiro went in.\n\nIt was a long time before he came back.\n\nWhen he surfaced, he was holding something. A small piece of carved ice. He held it out toward Obia.\n\n\"A narwhal gave this to me,\" Riro said. \"It swam up from very deep. It pressed this into my paw and then swam away.\"\n\nObia took it and looked at it carefully.\n\n\"Coordinates,\" Obia said.\n\n\"The narwhal said twelve kilometres south. It did not say more. Narwhals do not give directions easily. They are careful animals.\"\n\nObia looked at the carved ice. Then looked at the direction Dango had been walking.\n\n\"It is the same direction,\" Obia said.\n\nEveryone was quiet.\n\nDango's collar stayed gold.",
    },
    {
        "ep": 69,
        "title": "Shells Know",
        "text": "The next morning, the ground trembled.\n\nIt was not a large trembling. Most people would not have noticed it. But Daru stopped walking immediately. He spread all four legs wide and pressed close to the ice.\n\nGabu stopped too. He turned his head slowly.\n\n\"Left,\" Daru said.\n\n\"More left,\" Gabu said. \"Forty-five degrees.\"\n\nObia turned to face that direction and held up the record device.\n\nThe signal was there. Stronger than before. Very clear.\n\n\"That is it,\" Obia said.\n\nAko-chan looked at Daru and Gabu. \"You both felt it?\"\n\n\"Through the shell,\" Daru said. \"Like Patagonia. But much stronger.\"\n\n\"It is the same signal,\" Gabu said. \"All of them — the storms, the water, the sound in Patagonia. They are all the same thing.\"\n\nNobody spoke.\n\nDango sat beside Ako-chan. His collar was gold and steady.\n\nSuke-san looked in the direction they had found. \"How far?\"\n\n\"Twelve kilometres,\" Obia said.\n\nObia did not say how it knew this.\n\nGabu noticed. He said nothing. But he noticed.",
    },
    {
        "ep": 70,
        "title": "I Have Been Waiting",
        "text": "The ice valley was narrow and very quiet.\n\nAko-chan did not know why she had come this way. There was no signal here. But she had turned, and the others had followed.\n\nThen she saw it.\n\nA small shape stood very still in the middle of the valley. Round and grey-white. It had not moved for a long time.\n\nDango's collar stayed gold.\n\nThey came closer. It was a very small penguin — a chick, covered in thick soft feathers. It had very large round eyes.\n\nThe penguin looked at all of them. It did not move.\n\n\"I am Pen-san,\" it said. \"I have been waiting for you.\"\n\n\"For us?\" Ako-chan said.\n\n\"Yes. I knew you were coming.\" Pen-san looked at each of them in turn. \"Ako-chan. Dango. Obia. Gabu. Daru. Suke-san. Riro.\" Every name, correct.\n\nNo one spoke.\n\nThen Ako-chan said: \"Can I hold you?\"\n\nShe had not decided to say it. It came out before she thought.\n\nPen-san looked up at her. \"If you like.\"\n\nShe picked Pen-san up.\n\nDango's collar turned slowly from gold to orange.",
    },
    {
        "ep": 71,
        "title": "The Colonel",
        "text": "A smaller penguin stepped out from behind a blue-grey rock.\n\nIt moved fast. It looked at all seven of them in a single sweep.\n\n\"Colonel Adelie,\" it said. \"Guard and instructor to Pen-san. I will explain the situation.\"\n\nIt did not wait for a reply.\n\n\"There is a structure twelve kilometres south, under the ice. It has been there for a very long time. It pulls things toward it — signals, animals, anyone who is looking for something.\"\n\n\"How did you find us?\" Ako-chan asked.\n\n\"Narwhals. Whales. Birds. The whole south has known you were coming.\"\n\nSuke-san's tail flicked once.\n\nColonel Adelie looked at Obia. \"I believe you open the door.\"\n\nObia did not confirm or deny this.\n\n\"Eight kilometres flat, then an ice ridge with strong wind. One entry shaft, about one metre wide. Metal door at the bottom.\" Colonel Adelie turned to face the group. \"Roles.\"\n\nEach one received a task. Suke-san: east flank. Obia: first through the shaft. Daru: with Obia, reporting. Riro: undersea approach. Gabu: weather watch at the ridge. Pen-san: with Ako-chan.\n\nColonel Adelie stopped in front of Ako-chan. \"You hear what no one else hears. Use that.\"",
    },
    {
        "ep": 72,
        "title": "No More Signals",
        "text": "The camp was quiet. Everyone was asleep.\n\nObia sat at the far edge of the camp and looked at the small device it had carried since the beginning of the journey.\n\nFor many months, Obia had sent signals with this device. Short and regular. The same code, again and again. A report. A record. _We are here. Here is what has happened._\n\nNo one in the group knew about these signals.\n\nThe last message received had said: _Do not forget what you are for._\n\nObia looked at the device for a long time.\n\nThen Obia looked at the camp.\n\nDango was curled beside Ako-chan, his collar a quiet gold. Gabu's shelter was closed. Daru was on top of the backpack. Riro was still in the water unit. Suke-san had one ear up, even in sleep.\n\nObia put the device down.\n\nThen picked it up again. Turned off the send function. Set it to receive only.\n\nNo signal went out that night. Or the next night.\n\nObia did not explain this to anyone. There was nothing to explain — not yet.\n\nThe ice was very quiet.\n\nThe stars over Antarctica were very bright.",
    },
    {
        "ep": 73,
        "title": "The Break",
        "text": "Suke-san walked to where Obia stood.\n\n\"I want to ask you something,\" Suke-san said.\n\nObia turned to face him.\n\n\"The signals that have come toward us from the south. You knew about them before we did. You have always known.\" Suke-san paused. \"Do you know who is sending them?\"\n\nObia was quiet.\n\n\"Do you know?\" Ako-chan said. She had been nearby. She came closer.\n\nObia still did not answer.\n\nDango stood up. He looked at Obia for a long moment. Then he walked away. He went to Ako-chan's side and sat down there — not Obia's side.\n\nHis collar was orange.\n\nGabu looked at the ice. Daru looked at Obia. Neither spoke.\n\nRiro went to the edge of the water and looked in.\n\nSuke-san waited. His tail was down.\n\n\"Obia,\" Ako-chan said. Her voice was quiet. \"I am not angry. I just want to know. Do you know who it is?\"\n\nObia looked at her.\n\nThen looked away.\n\nNo one moved.\n\nThe wind came across the ice. It was very cold.",
    },
    {
        "ep": 74,
        "title": "Alone",
        "text": "That night, Obia moved to the edge of the camp.\n\nEveryone else stayed on the other side. No one told them to. They just did.\n\nThe gap between Obia and the others was not large. But it was there.\n\nObia sat and looked at the dark ice.\n\nAfter a long time, a small shape came and stood nearby.\n\nIt was Pen-san.\n\nPen-san did not say anything. Pen-san just stood there, round and very still in the dark.\n\nObia looked at Pen-san.\n\n\"There is something I need to say,\" Obia said. \"But I cannot say it yet.\"\n\nPen-san did not reply.\n\n\"I will say it. I promise.\"\n\nPen-san looked up at the sky. The stars were bright and very far away.\n\nAfter a while, Pen-san said: \"I am going to stand here for a while.\"\n\n\"You do not have to,\" Obia said.\n\n\"I know,\" Pen-san said.\n\nAnd stayed.\n\nThe cold came in from the south. Obia and Pen-san stood at the edge of the camp and waited — for different things, in the same dark.",
    },
    {
        "ep": 75,
        "title": "Everything Obia Has Done",
        "text": "The next morning was clear.\n\nSuke-san stood at the centre of the camp. He waited until everyone was there. Then he spoke.\n\n\"I have something to say about Obia.\"\n\nNo one moved.\n\n\"Obia has not answered our question. I do not know why. I do not like it.\" Suke-san's tail was up, but just barely. \"But I have decided something.\"\n\nHe looked at Obia.\n\n\"Obia is our companion. I have decided this.\"\n\nAko-chan looked at Suke-san.\n\n\"What is the reason?\" Gabu asked.\n\n\"The reason is everything Obia has done. Not what Obia has said. Not the answer Obia did not give. Everything it has done — from England to here.\" Suke-san paused. \"That is the reason.\"\n\nNo one argued.\n\nDango stood up. He walked across the camp to Obia's side. He sat down there.\n\nHis collar turned from orange to gold.\n\nGabu watched. Daru watched. Riro pressed both paws to his face and said nothing.\n\nAko-chan looked at Obia. Obia was looking at Dango.\n\n\"Thank you,\" Obia said. Very quietly.\n\nSuke-san turned and walked away.",
    },
]
