STORIES_S1_P01 = [
    {
        "ep": 1,
        "title": "Ako-chan's Morning",
        "text": 'Ako-chan woke up early. It was New Year\'s Day. The sky outside was pale grey.\n\nShe put on her glasses and looked out of the window. The garden was quiet. The old oak tree stood still in the cold air. Snow had fallen in the night.\n\nDango was asleep on the floor by her bed. He was a small red and white dog with a long fluffy tail. When she moved, his ears went up.\n\n"Wake up," she said softly. "It is a new day."\n\nDango opened both eyes. He wagged his tail.\n\nThey went outside together. The garden smelled of cold earth and frost. Dango ran to the oak tree and sniffed the roots.\n\nA fox was sitting near the garden gate. It looked at Ako-chan with bright eyes.\n\n"Something is wrong," said the fox. "Somewhere far away. The animals all feel it."\n\nThe fox turned and walked away.\n\nDango did not hear the words. He was still sniffing the tree roots. But Ako-chan had heard every word. She could always understand what animals said. She had never told anyone this. It was her quiet secret.\n\nShe looked at the grey sky.\n\n"Something is wrong," she said softly, to no one.',
    },
    {
        "ep": 2,
        "title": 'The Silver in the Night',
        "text": 'Ako-chan was reading in bed when Dango jumped up.\n\nHis ears went flat. He stared at the window. Then he barked. Loud and sharp.\n\nAko-chan looked up. Through the glass she saw something. A silver shape. Moving fast. Then it was gone.\n\nShe got up and went to the window. She pressed her face close to the glass. The street was empty. The garden was dark and still. The snow on the ground was white and smooth.\n\nNothing was there.\n\n"It\'s all right," she told Dango. "There\'s nothing."\n\nDango did not stop looking at the window. His tail was low. His nose was against the glass.\n\nHe barked one more time. Then he sat down. But his eyes never moved from the window.\n\nIn the morning, Ako-chan went out to the garden. She found small footprints in the snow. They went from the fence to the path and then away.\n\nShe crouched down and looked at them. They were small. Four toes. But the shape was not like any dog or cat she knew.\n\nShe stood up and looked down the empty street.',
    },
    {
        "ep": 3,
        "title": 'The Bench in the Park',
        "text": 'Dango pulled hard on his lead.\n\nHe had caught something. A scent. He pulled Ako-chan off the main path and down toward the duck pond.\n\n"Dango, slow down," she said. But he did not slow down.\n\nHe stopped.\n\nAt the far end of the pond, there was a wooden bench. A small dog sat on it. Very still. It was watching the ducks on the water.\n\nThe dog was silver. Its body was smooth and neat. No fur. No collar. Its eyes were pale and clear, almost like glass.\n\nDango made a sound. Not a bark. Something lower. Uncertain.\n\nAko-chan stood very still and looked. The dog did not move. It just watched the ducks.\n\nThen it turned its head.\n\nIt looked at Ako-chan. Then at Dango. Then back at Ako-chan.\n\n"Hello," it said.\n\nIts voice was calm and clear. Not quite like an animal voice. Not quite like a human voice either.\n\nAko-chan could not speak. She could always speak to animals. But this was different. She had never seen anything like this before.\n\nDango growled. Soft and low.\n\nThe silver dog did not blink. It just waited.',
    },
    {
        "ep": 4,
        "title": 'Hello, Obia',
        "text": '"My name is Obia," said the silver dog.\n\nDango growled again. Obia did not move.\n\n"What are you?" said Ako-chan.\n\n"I am a robot dog," said Obia. "I know that this is unusual."\n\n"Yes," said Ako-chan. "It is."\n\nShe took one step closer. Dango stayed behind her.\n\n"How do you know how to talk?" she said.\n\n"I was built to talk," said Obia. "And to listen. And to help."\n\n"Who built you?"\n\n"I will answer that question later," said Obia. "There is a great deal to explain. It may take some time."\n\nAko-chan looked at its eyes. They were calm and still. It did not look away. It did not look nervous. It just waited.\n\n"You know my name," said Ako-chan. "You knew I was coming."\n\n"Yes," said Obia.\n\n"How?"\n\n"I know a lot about you, Ako-chan," it said. "I know about your gift."\n\nDango had stopped growling. He stood very close to Ako-chan\'s leg. His tail was low, but he was watching Obia closely.\n\n"What gift?" she said.\n\nObia looked at her. "The animals," it said. "You can hear them."',
    },
    {
        "ep": 5,
        "title": 'A Request to Travel',
        "text": 'They walked back through the park together. Obia walked beside Ako-chan. Dango walked on the other side. He did not growl anymore, but he kept one eye on Obia at all times.\n\n"What do you want?" said Ako-chan.\n\n"I would like to travel with you," said Obia.\n\n"I\'m not going anywhere."\n\n"Not yet," said Obia. "But you will."\n\nAko-chan stopped. "What do you mean?"\n\n"Something is happening in the world," said Obia. "Strange things are happening to animals. To the sea. To the weather. You have heard the reports. The pigeons told you. The hedgehog. The fox."\n\nAko-chan said nothing.\n\n"I have been watching this for a long time," said Obia. "I know more than the animals do. But I need you. You can speak to every creature we meet. That is something I cannot do."\n\n"Why do you need to travel?" said Ako-chan.\n\n"To find where these things are coming from," said Obia. "To find the source."\n\nAko-chan looked at it for a long moment. Then she looked at Dango. Dango looked back at her.\n\n"I have not said yes," she said.\n\n"I know," said Obia. "I will wait."',
    },
    {
        "ep": 6,
        "title": "Dango's Test",
        "text": 'Dango had decided to test Obia.\n\nHe went to his toy box and picked up his blue ball. He dropped it at Obia\'s feet and stepped back.\n\nObia picked up the ball. It threw the ball down the hallway. Not too hard. Not too soft. Just right.\n\nDango ran after it and brought it back. He dropped it again.\n\nObia threw it again.\n\nThey did this for a while.\n\nThen Dango went to his corner and came back with his rabbit. It was old and soft, with one button eye missing and one torn ear. It was his most special thing. He had kept it since he was very small.\n\nHe put it down in front of Obia.\n\nObia looked at it. It did not pick it up. It just looked at it carefully, as if it understood that this was something important.\n\nDango picked up the rabbit again and went to sit by Ako-chan.\n\n"I think he was testing you," said Ako-chan.\n\n"I think so too," said Obia.\n\n"Did you pass?"\n\nObia looked at Dango. Dango was looking at the rabbit. He had not growled even once in the last hour.\n\n"I think that depends on Dango," said Obia.',
    },
    {
        "ep": 7,
        "title": 'The Song of the Birds',
        "text": 'A flock of birds landed on the roof.\n\nAko-chan could hear them from inside. Their calls were loud and fast. They went on and on, the same pattern over and over.\n\nDango stood at the bottom of the stairs and looked up at the ceiling.\n\nAko-chan went to the window. The roof was full of birds. Small brown ones. More than she had ever seen at once.\n\n"What are they saying?" she asked.\n\n"They are saying: be ready, something is coming," said Obia from across the room.\n\nAko-chan turned. "You can understand them?"\n\n"Not the way you do," said Obia. "I hear patterns in the sounds. Structures. The way messages are passed between birds is more like code."\n\n"And you can read code."\n\n"Yes."\n\nAko-chan looked back at the birds. They were still calling. The same rhythm. Over and over.\n\n"Be ready. Something is coming," she said quietly.\n\n"It has been getting stronger," said Obia. "The warnings. There are more of them now. And they are all pointing the same way."\n\n"South," said Ako-chan.\n\nObia said nothing. But it did not disagree.',
    },
    {
        "ep": 8,
        "title": 'Telling a Secret',
        "text": 'Ako-chan told Obia after dinner.\n\nThey were sitting in the kitchen. Dango was asleep by the radiator. The house was quiet.\n\n"I have never told anyone," she said. "About the animals. That I can hear them."\n\n"I know," said Obia.\n\n"It is strange. I have had this my whole life. But I never said a word. Not to any person."\n\n"Why not?" said Obia.\n\nAko-chan thought about it. "I was afraid they would not believe me. Or they would think I was very strange." She looked at her hands. "It felt safer to keep it secret."\n\n"You told me," said Obia.\n\n"Yes." Ako-chan looked up. "You already knew. So it felt different."\n\n"That is fair," said Obia.\n\n"How did you know?" she said. "About me. About my gift."\n\n"I learned," said Obia. It did not say more.\n\n"Is that why you came? Because of what I can do?"\n\n"It is one reason," said Obia. "Yes. The animals will speak to you. They will not speak to me the same way. What you hear is different from what I can detect. We need both."\n\nAko-chan nodded slowly. She was glad she had said it out loud. It felt lighter now.',
    },
    {
        "ep": 9,
        "title": 'The Night of Decision',
        "text": 'Ako-chan could not sleep.\n\nShe lay in the dark for a long time. Dango was beside her. Obia was downstairs, still and quiet.\n\nShe thought about the map. The pins in the south. The fox and the hedgehog and the pigeons. The birds on the roof. The fish in the rivers. The before-a-storm feeling that animals all over the world were carrying.\n\nShe thought: someone should go and find out.\n\nShe thought: who is going to go?\n\nShe got up and went downstairs.\n\nObia was sitting in the dark room. It turned when she came in.\n\n"I want to travel," said Ako-chan. "Around the world. To look at these things. To find where they are coming from."\n\nObia was quiet for a moment.\n\n"I have been waiting for that," it said.\n\n"How long?"\n\n"Since before I came here."\n\nAko-chan stood in the doorway. "You knew I would decide this."\n\n"I thought you would," said Obia. "But I could not be sure. It had to be your choice."\n\nAko-chan nodded. "When do we start?"\n\n"When you are ready," said Obia. "There is no rush. But there is a reason."\n\n"All right," said Ako-chan. "We start soon."',
    },
    {
        "ep": 10,
        "title": 'Goodbye, To Come Home Again',
        "text": 'The day was grey. The air was still.\n\nAko-chan stood at the front door with her rucksack on her back. Dango was beside her. Obia was on the path outside, already waiting.\n\nShe looked back into the house.\n\nThe rooms were empty and quiet. The fireplace was cold. The kitchen table was clean. No cups, no books, nothing left out. It looked like a house no one lived in.\n\nShe looked for a moment. Just one moment.\n\nShe could hear the oak tree moving in the small wind. She walked to it and crouched down. An acorn lay in the snow at its roots, dark and smooth. She picked it up and held it in her palm. Then she put it in her coat pocket. A small piece of home.\n\nShe walked back and pulled the front door shut.\n\nShe put the key in the lock. She turned it. She heard the click.\n\nDango had not looked back. He stood on the path and faced the road ahead. His tail was up. He was ready.\n\nAko-chan put the key in her pocket, next to the acorn.\n\nObia turned and looked at her.\n\n"Ready?" it said.\n\n"Yes," said Ako-chan.\n\nThey walked down the path. Through the gate. Onto the street.\n\nAko-chan did not look back again. But she touched the acorn in her pocket as she walked.\n\nAhead of her, Obia moved in silence. And the road went south.',
    },
]
