STORIES_S1_P04 = [
    {
        "ep": 42,
        "title": 'Hakata Port',
        "text": 'The ferry docked at Hakata. They walked off the ramp and onto the ground of Japan.\n\nThe port was busy. There were people and cars and the sound of the sea still close by.\n\nA cat was sitting on a low wall near the exit. It was black and white, with bright eyes. It looked at Ako-chan and spoke.\n\n"Welcome," said the cat. In Japanese.\n\nAko-chan answered. In Japanese. "Thank you. We just arrived."\n\n"From China?" said the cat.\n\n"Yes," said Ako-chan.\n\n"Long way," said the cat. "You look tired but all right."\n\nObia paused behind Ako-chan. It had noticed what just happened.\n\nAko-chan turned to the others. "The cat gave us directions to a good resting spot," she said. "It is not far."\n\nDango looked at the cat. The cat looked at Dango. They said nothing to each other. This was the usual way.\n\nAs they walked through the port, Ako-chan realised something. She had not thought even once about whether she could understand the cat. She had just understood.\n\nEnglish. German. French. Hungarian. Turkish. Kazakh. And now Japanese.\n\nThe language did not matter. It never had.\n\nShe wrote a short line in her diary that evening: *Any language. Any animal. Always the same.*\n\nObia read the note over her shoulder and said nothing. But it did not look away quickly.',
    },
    {
        "ep": 43,
        "title": 'Heading North',
        "text": 'They were on a train heading north toward Hokkaido. Outside, the forests were getting thicker. The light was lower and greener.\n\nObia came and sat beside Ako-chan.\n\n"I want to show you something," it said.\n\nIt opened a small panel on its side and connected to the record device. A map appeared. It showed the coast of Hokkaido.\n\n"The sea temperature here," said Obia. "It has been changing."\n\nAko-chan looked at the data. There were numbers and colours showing temperature zones.\n\n"Is that the same as the Adriatic?" she said.\n\n"Similar in structure," said Obia. "But larger in scale."\n\nAko-chan felt something settle in her chest. Not fear exactly. Recognition.\n\n"The same kind of signal," she said. "Just bigger."\n\n"Yes," said Obia.\n\nShe looked at the map for a long time. Turkey. Armenia. Kazakhstan. Shanghai. The Pacific. And now Hokkaido.\n\n"It keeps getting closer to something," she said.\n\nObia did not answer that. It closed the panel.\n\nDango had been watching from her feet. He looked at the map and then at Obia.\n\n"Is it bad?" said Dango.\n\n"We do not know yet," said Obia. "That is why we are going."\n\nDango accepted this. He put his head back on his paws and watched the dark trees move past the window.\n\nThe train kept going north.',
    },
    {
        "ep": 44,
        "title": 'The Dog on the Hill',
        "text": 'The hill looked out over the sea. The grass was short and green and the wind moved through it in slow waves.\n\nAt the top of the hill, a small dog sat perfectly still. He faced the sea. His back was to them as they came up the path.\n\nHe did not turn.\n\nThey came closer. The dog was a Shiba Inu. Small and neat. His tail was curled tight. His posture was very correct.\n\nThey stopped a few steps behind him.\n\nThe dog spoke. He did not turn his head.\n\n"I knew you were coming," he said.\n\nAko-chan looked at Obia. Obia looked at the dog.\n\n"How?" said Ako-chan.\n\n"The birds," said the dog. "Also the fox. Also the wind, a little." A pause. "I have been watching this coast for a long time. I know when something new arrives."\n\nHe turned then. He was smaller than Dango. His face was calm and precise. His eyes went around the group.\n\nWhen his eyes reached Obia, one ear moved. Just a little. It tilted back. Then it went straight again.\n\nThe dog\'s expression did not change.\n\n"My name is Suke-san," he said.\n\n"I am Ako-chan," she said. She introduced everyone in order.\n\nSuke-san nodded once for each name. He looked at the sea again.\n\n"You are going further east," he said. It was not a question.\n\n"Yes," said Ako-chan.\n\nSuke-san said nothing for a moment.\n\n"Good hill," said Daru cheerfully, from on top of the backpack.\n\n"Yes," said Suke-san. "It is."\n\nThe wind came off the sea and pushed through the grass around them.',
    },
    {
        "ep": 45,
        "title": 'Rival',
        "text": 'The next morning, Suke-san walked up to Obia.\n\nHe stood straight. His tail was perfectly curled.\n\n"I want to say something," said Suke-san.\n\n"Yes," said Obia.\n\n"You believe you are the most useful member of this group," said Suke-san. "I have seen how you work. You are good. But I am better."\n\nObia looked at him. "Is that so," it said. This was not a question.\n\n"Yes," said Suke-san. "I have lived on this coast for a long time. I know the currents. I know the paths. I know the weather before it comes. I know where to shelter. I know where the dangerous rocks are in the water."\n\n"That is useful," said Obia.\n\n"I know," said Suke-san.\n\n"I was not disagreeing," said Obia.\n\nSuke-san looked at Obia carefully.\n\n"You are not going to argue," he said.\n\n"No," said Obia.\n\nSuke-san waited a moment. Then he turned and walked back to his spot on the hill.\n\nAko-chan had heard the whole thing. She said nothing.\n\nDango came and sat beside Obia.\n\n"That was Suke-san saying hello," said Dango.\n\n"I understand," said Obia.\n\n"He does that," said Dango. "I think."\n\n"I think so too," said Obia.\n\nThe wind came off the sea. Suke-san sat at the top of the hill and looked at it, and said nothing more.',
    },
    {
        "ep": 46,
        "title": 'Dango and Suke-san',
        "text": 'Dango walked toward Suke-san slowly.\n\nSuke-san watched him come without moving.\n\nThey stopped nose to nose. Then Suke-san walked around Dango carefully, smelling as he went. Dango stood still. Then Dango walked around Suke-san in the same way.\n\nThen they both stood facing each other.\n\nThere was a pause.\n\nThen Suke-san started to run. Not at Dango. Just along the edge of the hill. He ran easily, not fast, not slow.\n\nDango ran after him.\n\nThey ran along the hill. Then across the top. Then around and back.\n\nThey did not speak. They did not bump into each other. They just ran.\n\nOnce. Twice. Three times around the same wide circuit.\n\nGabu watched from his shelter door.\n\nDaru watched from the backpack.\n\n"They are getting along," said Daru.\n\n"Yes," said Gabu.\n\n"They did not even say anything to each other," said Daru.\n\n"No," said Gabu.\n\n"I think that is how dogs do it," said Daru.\n\n"I think so," said Gabu.\n\nAfter the third circuit, Dango and Suke-san came back to where Ako-chan was sitting. They both sat down, a little apart, and looked out at the sea.\n\nThey were both slightly out of breath. They both looked pleased.\n\nNeither said a word about the run. That seemed to be the point.',
    },
    {
        "ep": 47,
        "title": 'Suke-san Sees the Map',
        "text": 'Ako-chan sat down beside Suke-san on the grass. She had the record device.\n\n"Can I show you something?" she said.\n\nSuke-san looked at the device. He said nothing, which meant yes.\n\nShe showed him the map. She showed him the path they had taken: England, France, the Netherlands, Germany, the Balkans, Turkey, Armenia, Georgia, Kazakhstan, China, Japan.\n\nThen she showed him the anomaly points. The marks on water. The temperature readings. The signal data.\n\nShe told him about the fox in the mountains of China. The otter in Shanghai. The signals Obia had received.\n\nSuke-san listened without speaking.\n\nWhen she was done, he looked at the map for a long time.\n\n"You are going further," he said. "Across the Pacific."\n\n"Yes," said Ako-chan.\n\n"To find the source."\n\n"Yes. We think so."\n\nSuke-san was quiet for a moment. He looked at the sea below the hill. Then he looked at the map again.\n\nThen he looked at Ako-chan.\n\n"I will come," he said.\n\nHe did not pause before saying it. He did not hesitate. His tail was curled tight and perfect.\n\n"Thank you," said Ako-chan.\n\n"Don\'t thank me," said Suke-san. "I have been watching this coast for a long time. I want to know what is happening to it."\n\nHe looked at the sea again. His voice was the same as always.\n\nBut his tail had not uncurled even slightly.',
    },
    {
        "ep": 48,
        "title": "Suke-san's Weakness",
        "text": 'Obia spread the route map on the ground. Everyone gathered around it.\n\n"From here we cross to the Pacific," said Obia. "Then south and east across the open ocean."\n\nDaru looked at the blue on the map. "That is a lot of blue," he said.\n\n"Yes," said Obia. "Several weeks at sea."\n\nDango looked at the route. He had been at sea before, on the ferry. That was one night. Several weeks was different.\n\nGabu said nothing. He was looking at the part of the map that showed land ending.\n\nAko-chan looked at Suke-san.\n\nSuke-san was looking at the map. His face was perfectly still.\n\nBut his tail tip was moving. Very slowly. It was going down. Just the tip.\n\nHe noticed her looking. His tail went back up.\n\n"That is not a problem," said Suke-san.\n\n"Of course not," said Ako-chan.\n\n"I have looked at the sea my whole life," said Suke-san.\n\n"I know," said Ako-chan.\n\n"Looking at it and being on it are two different things," said Gabu quietly, from his spot near the shelter.\n\nSuke-san turned to look at Gabu.\n\n"Yes," said Suke-san, after a pause. "They are."\n\nNobody said anything more about it.\n\nObia began to explain the route in detail. The wind came off the sea. Suke-san\'s tail stayed mostly up.\n\nMostly.',
    },
    {
        "ep": 49,
        "title": 'The End of June',
        "text": 'They made a fire on the flat ground near the cliff. The smoke went straight up in the still air. The stars were bright.\n\nSix of them sat around the fire. Ako-chan, Dango, Obia, Daru, Gabu, Suke-san.\n\nDaru was telling a story about the market in China. He was on the part where he was sitting on the shelf between the stone rabbit and the clay pot.\n\n"The light really was excellent," he said. "Very warm. Very even."\n\n"You always say that," said Dango.\n\n"Because it was true," said Daru.\n\nGabu was watching the fire. Suke-san was sitting straight with his tail curled behind him.\n\nAfter a while, Suke-san got up. He walked to the edge of the firelight. There was a bundle of dried kelp near the rocks. He had put it there earlier. He picked it up in his mouth and carried it back to the fire.\n\nHe set it down in the middle of the group.\n\nEveryone looked at it.\n\n"For the journey," said Suke-san.\n\n"What is it for?" said Daru.\n\n"I am not sure," said Suke-san. "But it is useful."\n\nAko-chan looked at the kelp. She was not sure what they would do with dried kelp. But she picked it up and put it carefully into the pack.\n\n"Thank you," she said.\n\n"You are welcome," said Suke-san.\n\nHe sat back down. The fire burned.\n\nBelow the cliff, the sea moved quietly in the dark. Tomorrow they would go down to the rocks. Something was waiting for them there.',
    },
]
