STORIES_S1_P10 = [
    {
        "ep": 115,
        "title": 'Farewell, Antarctica',
        "text": 'The boat came.\n\nThey carried their bags down the ramp. Riro went first, then Suke-san, then Daru and Gabu, then Obia. Dango trotted down carefully. Ako-chan went last.\n\nShe stopped at the top of the ramp and looked back.\n\nPen-san and Colonel Adelie were standing at the edge of the ice shelf. They were side by side and perfectly still.\n\nThe boat began to move.\n\nAko-chan watched. She did not go inside. She stood on the deck and watched.\n\nThe two shapes on the ice grew smaller. The white ice grew wider around them, and they grew smaller inside it. But they did not move. They stayed exactly where they were.\n\nThe boat was farther now. Much farther. Ako-chan could still see them — two small dark shapes on the bright white.\n\nShe kept watching.\n\nAnd then, at some distance she could not measure, the two shapes seemed to overlap. To become one. And then there was nothing — just ice and sky, white and pale blue, the same as always.\n\nShe stood on the deck for a long time after that.\n\nDango came and sat beside her.\n\nShe did not write in her diary. Not yet. She just stood with Dango and watched the horizon until there was nothing left to see.\n',
    },
    {
        "ep": 116,
        "title": "Riro's Goodbye",
        "text": 'The northern Pacific coast appeared in the morning.\n\nThey were sailing near a rocky shoreline — dark rocks, cold water, the smell of deep sea. Seabirds called from somewhere above.\n\nRiro came to the railing.\n\nIt stood there and looked at the water below.\n\n"This is my place," said Riro.\n\nIt was not sad. It was simply true.\n\nIt turned to say goodbye. To Daru — a nod. To Gabu — both of them bowed slightly. To Suke-san — Riro said "not bad at all," which meant the wetsuit Obia had made; Suke-san said nothing, but dipped his head once. Obia said quietly, "The wetsuit was good." Riro looked at it and said, "Yes. It was."\n\nIt said goodbye to Dango, and to Ako-chan.\n\nThen it went to the railing.\n\nIt did not hesitate. It slipped over the side and entered the water below without a splash — smooth and quick, the way it always moved in the sea.\n\nAko-chan watched from above.\n\nRiro swam away from the boat. Strong and fast and easy. This was what Riro was built for.\n\nThen, a little way out, Riro stopped.\n\nIt turned.\n\nIt pressed both paws to its face — that gesture, the very first one, the way it had always looked at the world.\n\nIt looked at them.\n\nThen it turned and was gone.\n',
    },
    {
        "ep": 117,
        "title": "Suke-san's Goodbye",
        "text": 'The port in Hokkaido was small and quiet.\n\nThe boat pulled in and Suke-san came to the gangway with his bag. He was neat and straight, the way he always was.\n\nDango went to him.\n\n"Hokkaido hill," said Dango. "You said you\'d come."\n\n"I said it was allowed," said Suke-san. "In September."\n\n"Yes," said Dango.\n\nSuke-san looked at him for a moment. Then he looked at Ako-chan. "Come to Hokkaido," he said. "Also."\n\n"I will," said Ako-chan.\n\nHe turned to Obia.\n\n"You are our companion," said Suke-san. "The reason is everything you have done."\n\nHe said it simply, as a fact.\n\nThen he walked down the gangway.\n\nHe walked toward the hill above the harbour. He did not look back. His tail was down, his head was forward, and he walked.\n\nEveryone on the boat watched.\n\nHe reached the bottom of the hill. He began to climb. One third of the way up, he stopped.\n\nHe turned.\n\nHe raised his tail — his full curly tail, straight up, unmistakeable.\n\nThen he turned again and walked on, over the hill, and out of sight.\n\nDango watched the hill for a long time after Suke-san had gone.\n\nThen he sat down.\n\nHis collar was gold.\n',
    },
    {
        "ep": 118,
        "title": "Daru's Goodbye",
        "text": 'The Mediterranean coast smelled of salt and dry grass and warm rock.\n\nEven before the boat stopped, Daru was at the railing. Its head was up and its nostrils were moving.\n\n"I can smell it," said Daru.\n\nIt inhaled again.\n\n"My smell. I can smell mine."\n\nThe boat pulled close to the shore. Daru looked at the land — the rocks, the low bushes, the pale yellow ground.\n\n"That is it," said Daru. "That is right there."\n\nIt turned to Ako-chan.\n\n"Will we meet again?"\n\n"Yes," said Ako-chan. "We will."\n\nDaru looked at her face. It was checking. Searching for hesitation. There was none.\n\n"All right," said Daru. It was satisfied.\n\nIt said goodbye to Gabu — they had been together a long time, and the goodbye took longer than the others, though neither of them spoke much.\n\nThen Daru went to the railing and dropped to the shore below. A short drop. It landed well.\n\nIt began to run immediately.\n\nIt ran toward the rocks, toward the grass, toward whatever smell it had found. It did not run in a straight line — it ran the way it always did, in a wide joyful curve, like it was very glad to have all this space.\n\nThen it was gone, between the rocks.\n\nGone home.\n',
    },
    {
        "ep": 119,
        "title": "Gabu's Goodbye",
        "text": 'After Daru disappeared between the rocks, the shore was quiet.\n\nGabu was still on the boat.\n\nHe stepped down to the shore carefully, on his small legs, and walked to where Dango stood. He stopped in front of Dango.\n\n"Dango," he said. "You are a good companion."\n\nHe waited for Dango to take that in. Then he moved on.\n\nSuke-san was gone. He stood in front of where Suke-san had been and said: "Suke-san was reliable."\n\nTo Riro\'s empty place at the railing: "Riro cooked well and swam better."\n\nTo Obia: "Thank you for the bracket in the storm. And for everything after."\n\nObia said, "Thank you for noticing."\n\nGabu nodded.\n\nThen he came to Ako-chan.\n\nHe stood in front of her. He was small — he had always been small — and she was tall. She looked down at him. He looked up at her.\n\nShe bent her knees and knelt down to his height.\n\nThey were the same height.\n\nGabu looked at her, very directly, with his careful dark eyes.\n\n"I am glad I met you," he said.\n\nAko-chan could not speak for a moment. She nodded.\n\nGabu turned. He walked toward the olive grove on the hill. He did not rush. He walked at his usual speed, steady and unhurried.\n\nUntil the trees closed around him.\n',
    },
    {
        "ep": 120,
        "title": 'We Are Home',
        "text": 'The front garden looked exactly the same.\n\nThe gate, the path, the low stone wall. The bare winter tree. The brown grass. The house with its familiar windows and the chimney at the top.\n\nDango walked up the path ahead of her. He stopped at the front door and looked back.\n\n"Go on," said Ako-chan.\n\nShe opened the door. Dango went in. She heard his claws on the floor inside, and then the sound of him looking at things — sniffing the rug, going to the kitchen, coming back.\n\nThen: a sound in the garden.\n\nAko-chan turned. Something small was moving near the wall. A hedgehog — small and round, pushing through the dead leaves.\n\nIt stopped. It looked up at her.\n\n"Welcome home," said the hedgehog.\n\nAko-chan looked at it for a long time.\n\n"Thank you," she said.\n\nShe sat down on the doorstep. She opened her diary to the very last page.\n\nIt was blank.\n\nShe thought for a moment. Ten months. Eleven countries. Nine companions. Every hard morning, every beautiful place, every word she had tried to write and couldn\'t.\n\nShe picked up her pen.\n\nShe wrote two words.\n\nWe\'re home.\n\nShe looked at them. Then she closed the diary and sat in the cold winter garden and listened to Dango moving around inside the house, and the hedgehog, and the quiet.\n',
    },
]
