STORIES_S1_P09 = [
    {
        "ep": 76,
        "title": "Getting Close",
        "text": "The base appeared through the white.\n\nIt was not very large. Metal walls. A low shape under the ice, half buried. A door.\n\nNo one said anything.\n\nDango did not run. He walked beside Ako-chan, his collar a quiet gold — not the bright gold of happiness, but a steady gold, like something held very carefully.\n\nSuke-san walked to the right. Gabu moved slowly and said nothing. Daru was on the backpack but was not talking.\n\nRiro swam in the ice channel beside them, both paws pressed to his face.\n\nPen-san walked close to Ako-chan. Colonel Adelie stayed three steps behind, watching everything.\n\nObia went first.\n\nAko-chan put her hand in her pocket. The acorn was there. Small and hard and smooth. She had not thought about it in a long time. But her hand had found it anyway.\n\nThey stopped in front of the door.\n\nObia placed one paw against the metal. Something clicked. Something opened.\n\nThe door was cold and thick. Inside was a long, dark corridor.\n\nAko-chan looked at Dango. He looked at her.\n\nThey went in.",
    },
    {
        "ep": 77,
        "title": "Inside",
        "text": "The corridor was narrow. Their breath made small clouds in the cold air.\n\nObia went first. Then Ako-chan and Dango. Then Suke-san, then Gabu and Daru. Riro came through a smaller shaft from the water. Pen-san and Colonel Adelie came last.\n\nThey came out into a large room.\n\nThe walls were metal. The floor was metal. It was very cold, but there was no wind.\n\nAt the far end of the room was a screen. Very large — bigger than a door.\n\nSomeone was on the screen.\n\nA person. Tall. Wearing a white coat. Their back was turned. They were not moving.\n\nAko-chan stopped.\n\nNo one spoke.\n\nThen Obia said, quietly: \"This place knows you.\"\n\nNo one asked what it meant.\n\nThen the voice came from the screen. It was not loud. But it filled the room.\n\n\"You have arrived.\"\n\nDango's collar was gold. Not moving. Just steady.\n\nAko-chan looked at the turned figure on the screen. She had never seen this person before. She had never heard that voice.\n\nBut it did not feel entirely new.\n\nShe could not explain why.\n\nShe stood still and waited.",
    },
    {
        "ep": 78,
        "title": "The Test",
        "text": "Ako-chan stepped forward.\n\n\"Are you the one who arranged all of this?\" she said. \"The storms. The signals. Everything.\"\n\nThe figure on the screen was quiet for a moment. Then: \"Yes.\"\n\n\"Why?\"\n\n\"I wanted to know,\" the voice said, \"whether humans and animals can trust each other. Whether they would protect each other when things were hard. Whether they are worth being kept. Your journey was my question. Everything you did was the answer.\"\n\nNobody moved.\n\nGabu looked at the floor. Then at Ako-chan. Then back at the floor.\n\nDaru's head was stretched out as far as it would go.\n\nSuke-san's tail was very still.\n\n\"I chose you,\" the voice said to Ako-chan, \"because you can hear what no one else can hear. I wanted to see how someone like you would travel.\"\n\nThen the voice was quiet.\n\nAfter a moment, it spoke again.\n\n\"Some things were outside my calculations. Pen-san was one of them.\"\n\nAko-chan did not feel angry. She felt something else. Like when you find the last piece of a puzzle and the picture finally makes sense.\n\nShe looked at the turned figure.\n\nShe was still thinking.",
    },
    {
        "ep": 79,
        "title": "A Name",
        "text": "The room was quiet after those words.\n\nThen Obia stepped forward.\n\nJust one step. But it was Obia's step — deliberate, chosen.\n\nBefore the figure on the screen could speak again, Obia said: \"I was sent as an observer. But I became Obia.\"\n\nSomething moved inside Ako-chan.\n\nAll at once, many things connected. The signal in the night, hidden away. The freeze in the mountains. The promise. The fragment the hawk had dropped, which Obia picked up before she could reach it. The message: *do not forget what you are for.*\n\nShe looked at the screen. At the still, turned figure.\n\n\"Yu-chan...?\"\n\nThe name came out before she thought. She had not decided to say it. It was simply there.\n\nDango looked at her.\n\nThe figure on the screen was very still. Then it made a small movement — not turning, just a small tilt of the head.\n\nAko-chan did not know where the name had come from. It had simply been there, waiting, somewhere she had not looked.\n\nShe said it again, quietly, to herself.\n\n\"Yu-chan.\"\n\nThe room was silent.\n\nObia had not moved from that one step forward.",
    },
    {
        "ep": 80,
        "title": "The Truth",
        "text": "Everyone was looking at Obia.\n\nObia looked at the floor. Then at Ako-chan. Then at the screen.\n\n\"I was sent,\" Obia said. \"By this person. To watch you. To record everything — every day, every place, every decision. To send it all back. That was the plan.\"\n\nThe room was very quiet.\n\n\"You knew about the signals from the beginning,\" Suke-san said. His voice was flat. Not angry. Just stating the fact.\n\n\"Yes,\" Obia said.\n\n\"You knew who was sending them.\"\n\n\"Yes.\"\n\nGabu looked at Daru. Daru looked at Gabu. Neither spoke.\n\n\"But,\" Obia said.\n\nEveryone waited.\n\n\"I also stayed up all night when Dango could not sleep. I held the shelter bracket in the storm because Gabu was inside. I built things — not because the plan said to, but because it needed doing.\" Obia's voice did not change. \"None of that was in the plan. But all of it happened.\"\n\nObia looked at Ako-chan.\n\n\"I am still what I was sent to be. And I am Obia. Both of those things are true.\"\n\nAko-chan was looking at Obia.\n\nThe room was very quiet again.",
    },
    {
        "ep": 81,
        "title": "Dango Steps Away",
        "text": "When Obia finished speaking, the room was still.\n\nThen Dango made a sound. Low and short. He had never made that sound at Obia before.\n\n\"Dango,\" Ako-chan said.\n\nHe stopped. But he did not look away.\n\nSuke-san took one step forward — just one — placing himself between the center of the room and the others. Not toward Obia. Not against it. Just there.\n\nThen Dango stood up slowly. He did not shake himself or stretch. He just stood.\n\nHe looked at Obia for a long moment.\n\nThen he turned and walked. Not far. Just to the far side of the room. He sat down there.\n\nHis collar was deep orange.\n\nAko-chan did not call him back.\n\nGabu looked at the floor. Daru looked at his own feet. Riro pressed both paws to his face and said nothing.\n\nObia stayed where it was. It did not move toward Dango. It did not speak.\n\nThe only sound was the quiet hum of the metal walls.\n\nDango did not look at Obia.\n\nHis collar did not change.",
    },
    {
        "ep": 82,
        "title": "After the Words",
        "text": "A long time passed.\n\nNo one said anything.\n\nGabu had not moved from his spot. He was looking at a small point on the metal floor — not sleeping, just waiting, the way a tortoise can be still.\n\nDaru had come down from the backpack. He stood on the ground, four feet spread wide, head low.\n\nRiro had not moved his paws from his face. He was sitting with his back against the wall.\n\nSuke-san was looking at the wall. Not the screen. Just the wall. His tail was down.\n\nPen-san stood at Ako-chan's side and watched everything.\n\nColonel Adelie stayed at the back of the room and said nothing.\n\nObia was looking straight ahead — not at anyone, just at the air in front of it.\n\nAko-chan looked at Obia.\n\nShe thought about the night when Dango could not sleep and Obia sat beside him until morning. She thought about the scratch on Obia's silver side from the storm. She thought about the shelter bracket and Gabu inside.\n\nShe thought about the acorn in her pocket.\n\nShe had not decided anything yet.\n\nBut she was thinking.",
    },
    {
        "ep": 83,
        "title": "That's Enough",
        "text": "Pen-san moved.\n\nSmall steps, very quiet. He came across the room to where Dango was sitting.\n\nDango looked up.\n\nPen-san looked at him. Not with the eyes that made everyone obey. Just a look — simple and direct.\n\n\"That is enough,\" Pen-san said.\n\nDango looked at Pen-san for a moment.\n\nThen at Obia.\n\nObia had not moved.\n\nDango stood up slowly. He walked across the room. He sat down beside Obia.\n\nHe did not lean against Obia. But he sat close.\n\nNo one said anything.\n\nThen, very slowly, Dango's collar began to change. It moved from deep orange — toward gold. Not all at once. Slowly, the way light changes in the morning.\n\nIt reached gold.\n\nIt stayed there.\n\nObia looked down at Dango. Dango looked forward.\n\n\"Thank you,\" Obia said. Very quietly.\n\nNo one answered.\n\nBut Gabu lifted his head from the floor.\n\nAnd Daru straightened his four feet.\n\nAnd Suke-san's tail began, very slowly, to lift.",
    },
    {
        "ep": 84,
        "title": "The Verdict",
        "text": "The room was still.\n\nThen the figure on the screen spoke again.\n\n\"I have been watching all of this,\" the voice said. \"From the beginning. Every day. Every decision.\"\n\nNo one answered.\n\n\"You have answered the question.\" The voice was quiet. \"Whether humans and animals can trust each other. Whether they would protect each other.\" A long pause. \"You pass.\"\n\nAko-chan looked at the screen.\n\n\"What do we pass?\" she said.\n\n\"The question I could not answer myself. You answered it by living it.\"\n\nSilence.\n\n\"Why won't you show your face?\" Ako-chan said.\n\n\"A face is not important,\" the voice said. \"What matters is what you did.\"\n\nA small electronic sound came from the screen. Something ending.\n\nText appeared: *SIGNAL TERMINATED.*\n\nThen, one by one, all the red points on the record device went dark. The signals from the south — the storms, the currents, all of it — stopping.\n\nThe figure on the screen said one more thing.\n\n\"Safe journey home.\"\n\nThe screen went dark.",
    },
    {
        "ep": 85,
        "title": "One More Moment",
        "text": "They stood in the room for a while after the screen went dark.\n\nThen Pen-san walked to the door and looked out.\n\n\"The weather is good,\" Pen-san said.\n\nAko-chan almost laughed. She did not quite laugh. But almost.\n\nThen Gabu said: \"Today will be a good day.\"\n\nEveryone looked at him.\n\nIt had been a long time since he had said that.\n\nGabu did not explain. He walked toward the door.\n\n\"Yes,\" Daru said. \"Today will be a good day.\"\n\nOne by one, they moved toward the door.\n\nAko-chan stood still for a moment.\n\nShe put her hand in her pocket and held the acorn. It was small and smooth and it had been with her since England — since the hedgehog in the garden who had said *three people* and placed it in her hand.\n\nShe held it for a moment.\n\nThen she walked to the door.\n\nObia was already outside. Dango was beside Obia, his collar gold and steady. Suke-san stood with his tail up. Riro was in the water channel, both paws pressed to his face, watching.\n\nThey all looked at her when she came out.\n\n\"Let's go,\" Ako-chan said.",
    },
]
