STORIES_S1_P03 = [
    {
        "ep": 23,
        "title": 'Hello, Daru',
        "text": 'The morning sun was bright on the rocks.\n\nAko-chan was packing her bag. Dango was sniffing at the base of a large flat stone. Obia stood and waited.\n\nThen, between two rocks, something moved.\n\nA small round dome appeared. It was brown and tan, with dark markings. It rolled — rather than walked — forward over the edge of the rock and landed with a soft thud on the path.\n\nA head came out. Two small eyes blinked in the sunlight.\n\n"Hello," said the tortoise.\n\nDango froze.\n\n"I have been watching you," the tortoise said cheerfully. "Since yesterday. And the day before. You are a very interesting group." It looked at Ako-chan. "Where are you going?"\n\n"South," said Ako-chan.\n\n"How far south?"\n\n"Very far."\n\nThe tortoise looked at each of them in turn. It looked at Dango. At Obia. At the backpack. At the path leading south. Then it looked at Ako-chan again.\n\n"Can I come?"\n\nAko-chan crouched down to its level. The tortoise had bright, direct eyes.\n\n"What is your name?" she asked.\n\nThe tortoise stretched up a little. "Daru," it said.\n\nAko-chan smiled. "Hello, Daru."',
    },
    {
        "ep": 24,
        "title": 'Already There',
        "text": 'They stopped for lunch at a wide, flat place beside the path. Ako-chan took off her backpack and set it on the ground.\n\nDango went to find water. Obia stood and checked the afternoon route.\n\nAko-chan opened her notebook and began to write.\n\nDaru looked at the backpack. He walked around it once. He looked at the top. It was exactly the right height. There was a flat strap across the top, with just enough room.\n\nHe put his front feet up. He pulled with his back feet. He scrambled, tilted, scrambled again, and finally got himself on top.\n\nHe spread his legs out and sat there, looking pleased.\n\nAko-chan looked up from her notebook.\n\nDaru was already on top — tail pointing upward, eyes bright.\n\n"That is my bag," said Ako-chan.\n\n"Yes," said Daru. "Good spot."\n\nAko-chan looked at Obia. Obia looked at the backpack. Then at Daru. Then it said, very calmly, "He is not heavy."\n\n"That is not the point," said Ako-chan.\n\nBut she did not take Daru off the bag. She put her notebook away, lifted the backpack, and Daru held on without complaint.\n\nHe rode the rest of the afternoon on top.',
    },
    {
        "ep": 25,
        "title": 'A Good Result',
        "text": 'Obia asked Daru to stay still. Daru stayed still — for about ten seconds. Then he looked down to see what Obia was holding.\n\n"What is that?"\n\n"A thermometer," said Obia. "Do not move, please."\n\nDaru stayed still again. Mostly.\n\nObia checked his shell from every angle. It measured the length and width of his plastron — the flat underside. It pressed a sensor lightly to the back of his neck and waited.\n\n"Body temperature," said Daru. "Right?"\n\n"Yes."\n\n"And?"\n\n"Good. Shell in good condition. No soft spots. Water level balanced. Weight appropriate for your age."\n\nDaru looked very pleased. "Does that mean I pass?"\n\nObia paused. Then it raised one front leg, flat, all digits extended. It was something between a wave and a signal.\n\nDaru stared at it. "Is that a yes?"\n\n"That is an OK," said Obia.\n\nDaru\'s eyes lit up. He sat up very straight. "Then build it! Whatever you are going to build — I trust you. Build it."\n\nObia lowered its leg. "Very well," it said. It took out its tools.\n\nDaru climbed back onto the backpack and watched from above with great authority.',
    },
    {
        "ep": 26,
        "title": 'A House of His Own',
        "text": 'Obia worked through most of the night. By morning, a new object sat beside the path.\n\nIt was a small shelter — a low frame of light metal, with a dark panel on the top. Inside, there was a soft warm floor. The walls held in heat. The whole thing was exactly the right size.\n\nAko-chan watched Obia make the last adjustment. "A solar panel?" she asked, looking at the dark top.\n\n"Yes. It collects heat in the day. An element inside releases it through the night."\n\nDaru had been watching from the backpack. He had not said anything for almost ten minutes, which was unusual.\n\nNow he climbed down. He walked to the shelter and looked in through the front.\n\nThe inside smelled warm and dry. The floor was the right temperature. There was just enough room to turn around.\n\nDaru stepped in.\n\nHe looked at the walls. He looked at the ceiling. He looked at the warm floor under his feet.\n\n"My house!" he said. He turned around twice. He sat down. "This is my house."\n\nObia said, "The temperature can be adjusted with this switch."\n\n"My house," said Daru again, more quietly this time.\n\nHe rode on the top of the backpack for the rest of the day, but that evening he slept inside the shelter.',
    },
    {
        "ep": 27,
        "title": 'Eyes in the Leaves',
        "text": 'Ako-chan went to the olive grove alone one morning. Dango and Daru stayed further back with Obia.\n\nShe sat down a little way from the leaf pile. She took out her diary and opened it.\n\nShe did not look at the pile. She wrote.\n\nThe olive grove was quiet. A breeze moved the leaves overhead. Somewhere above the hill, a bird called once, then went silent.\n\nAko-chan kept writing. She did not look up.\n\nAfter a while she had a feeling she sometimes got near animals — a weight of attention from a direction, the sense that something was watching. She did not move.\n\nShe kept her eyes on her page. She wrote slowly.\n\nThen, without turning her head, she let her eyes move — just a little — toward the left edge of the leaf pile.\n\nTwo small eyes were looking at her.\n\nThey were pale and steady and very careful. They watched without blinking.\n\nAko-chan looked back at her diary. She wrote one more line. Then she closed the diary, stood up slowly, and walked back to the others.\n\n"It is there," she said quietly. "And it is watching."\n\nShe looked back once. The leaf pile was still. But she knew.',
    },
    {
        "ep": 28,
        "title": 'A Voice',
        "text": 'The next morning Ako-chan sat down in the same spot. She did not look at the leaf pile. She opened her diary.\n\nThe grove was very quiet. The leaves overhead were still.\n\nShe wrote for a while. She thought about the road, and the smell of the olive trees, and what Daru had said about the soil.\n\nShe was about to turn a page when she heard it.\n\nA small voice. Very quiet. Not quite a question — more like someone thinking out loud.\n\n"...why do you keep coming?"\n\nAko-chan did not move quickly. She looked up slowly and turned, the way she would with a shy dog.\n\nThe leaf pile was still. But now she could see the edge of a shell — pale yellow, small — just at the front of the pile.\n\n"Because I want to talk with you," she said. Quietly, without urgency.\n\nA pause.\n\n"I don\'t talk much," said the voice.\n\n"That is all right," said Ako-chan. "I can be quiet too."\n\nShe opened her diary again and went on writing.\n\nNeither of them said anything more. But the shell moved a little further out of the pile.',
    },
    {
        "ep": 29,
        "title": "Gabu's Condition",
        "text": 'The next morning, Ako-chan came back. She sat down. She opened her diary. She waited.\n\nShe did not have to wait long.\n\nThe shell moved forward through the leaves, slowly, until the whole head was visible. The tortoise was small. Its shell was flatter than Daru\'s — pale yellow with soft blotches of a darker colour. It looked at Ako-chan with steady eyes.\n\n"I have been thinking," it said.\n\nAko-chan said nothing.\n\n"I could come. For a while. To look."\n\n"Yes," said Ako-chan.\n\n"But I want to be clear." The tortoise took one careful step forward. "I will watch. If I do not like what I see, I go home. No explanations needed."\n\n"Of course," said Ako-chan. She said it simply. No pressure, no promises.\n\nThe tortoise was quiet for a moment. It looked at her.\n\n"You have not asked my name yet," it said.\n\n"I was waiting for you to offer it."\n\nAnother pause. "Gabu," it said.\n\n"Hello, Gabu." Ako-chan closed her diary. "Would you like to meet the others today, or tomorrow?"\n\nGabu looked at the grove around them. "Tomorrow," it said. Then, after a moment: "...today."\n\nAko-chan stood. She did not reach for him or hurry. She walked toward the others. Gabu followed, slowly, behind her.',
    },
    {
        "ep": 30,
        "title": 'Hello, Gabu',
        "text": 'Gabu came forward.\n\nThe group was at the edge of the grove. Obia stood to one side. Dango sat with ears forward. Daru was on the ground, for once not on the backpack.\n\nGabu walked slowly out of the shadow and stopped. He looked at each of them in turn.\n\nThen Daru took three fast steps forward. "You are here! I knew you would come! I could smell you from the backpack but I didn\'t say anything because —"\n\n"Too close," said Gabu.\n\nDaru stopped. He was about thirty centimetres from Gabu\'s nose.\n\nHe looked down at himself. Then he stepped back one pace. "Sorry," he said.\n\nGabu looked at him. "You are a Hermann\'s tortoise."\n\n"Dalmatian," said Daru. "From further north."\n\n"I see." Gabu looked at Dango, who was sitting very still. "Are you going to run at me also?"\n\n"No," said Dango.\n\nGabu looked at Obia. Obia looked back without speaking.\n\n"What is that?" said Gabu.\n\n"Obia," said Ako-chan. "It travels with us."\n\nGabu watched Obia for a long moment. Then he looked at Daru, who had been waiting.\n\n"You said you would let me know," said Daru.\n\n"...I will let you know," said Gabu.',
    },
    {
        "ep": 31,
        "title": "Gabu's Shelter",
        "text": 'Obia came to Gabu the next morning.\n\n"I would like to take some measurements," Obia said. "To build you a shelter. For the cold nights and the hot days."\n\nGabu looked at the tools on the ground. "What is that for?" he asked. He pointed with his head.\n\n"A temperature sensor. It reads your surface and core warmth."\n\n"And that?"\n\n"A calliper. It measures the length and curve of your shell."\n\n"And that?"\n\nObia answered each question precisely. Gabu listened to each answer. He took his time. When Obia finished, Gabu said, "All right. You may begin."\n\nThe measurements took a while. Gabu stayed still and asked two or three more questions during the process.\n\nBy evening, Obia had built the shelter. A frame of light metal. A panel on top. A warm, dry floor inside.\n\nGabu looked at it from the outside for a long time.\n\nThen he walked in.\n\nHe walked to the back. He turned around. He stood in the middle. He put his head down and felt the warmth of the floor.\n\nHe said nothing for several minutes.\n\nDaru was watching. He was very quiet, which was unusual.\n\nThen Gabu said, very softly, "...thank you."\n\nObia tilted its head. "You are welcome," it said.',
    },
    {
        "ep": 32,
        "title": 'Obia Stops Again',
        "text": 'They were walking along a wide path above the sea when Obia stopped.\n\nNot a slow stop. A sudden one. Mid-step, with one foot in the air.\n\nFive seconds passed.\n\nDango reacted first. He trotted back and pressed his front paw firmly against Obia\'s leg. "Are you okay?"\n\nNo answer.\n\n"Obia," said Dango. "Obia."\n\nDaru leaned forward from the top of the backpack. "Is it broken?" he asked.\n\n"It is not broken," said Ako-chan quickly. She had seen this before.\n\nOn the path ahead, Gabu had stopped too. He turned and looked. Then, without saying anything, he walked slowly back to where Obia stood. He walked to Obia\'s side. He stood there.\n\nThat was all. He did not touch anything. He did not speak.\n\nObia came back. One blink. Then normal movement returned. It set its foot down and straightened.\n\n"A minor adjustment," it said.\n\nDango stepped back. "Same as before?"\n\n"Same as before."\n\nDango looked at Gabu. Gabu was already walking back to his place at the rear of the group. He had not said a word.\n\nLater, Ako-chan asked him why he had done it.\n\nGabu looked at her. "It seemed like the right thing to do," he said.',
    },
    {
        "ep": 33,
        "title": 'The Question',
        "text": 'Evening. The others were asleep or resting. Gabu was awake.\n\nHe walked to where Obia stood, a little apart from the group, facing the dark.\n\n"I want to ask you something," Gabu said.\n\n"Yes," said Obia.\n\nGabu thought for a moment. His way of beginning — always the pause, always the thought first. "Do you know what you are?"\n\nObia was quiet.\n\n"Not what you can do," said Gabu. "What you are."\n\nObia looked at him. "I know some things," it said at last. "There are others I cannot tell you. Not yet."\n\nGabu considered this. A tortoise can hold a thought for a very long time. He stood still with it.\n\n"Who made you?" he asked.\n\n"I cannot tell you that either."\n\n"Why not?"\n\n"Because the moment is not right. When it is, I will."\n\nGabu looked up at the stars for a while. "I understand," he said. "I am patient. It is one of the useful things about being a tortoise."\n\n"I have noticed," said Obia.\n\nGabu looked at Obia. "I have noticed things about you too," he said. "I will keep noticing."\n\n"Yes," said Obia. "I expect you will."\n\nGabu turned and walked back to his shelter. Obia watched him go.',
    },
    {
        "ep": 34,
        "title": 'A Good Morning',
        "text": 'The storm ended before dawn. By the time the sky began to lighten, the air was clean and cool. A smell of wet stone and new leaves came up from the valley.\n\nDango was still asleep. Daru was asleep. Ako-chan was half-asleep, her diary open on her lap.\n\nGabu was not asleep.\n\nHe had been awake for some time. He had watched the rain slow and stop. He had watched the first grey light come into the sky. He had watched the water drip from the edge of the overhang into a bright line below.\n\nWhen the light was strong enough to see the road, Gabu walked to the entrance of the cave.\n\nHe looked out.\n\nWet rock. Clean sky. A bird crossing far above, very fast. Drops falling from the leaves of an olive tree below the path.\n\nHe stood there for a moment.\n\nThen he turned and said, in a voice loud enough for everyone to hear:\n\n"Today is going to be a good day."\n\nDango opened one eye. Daru twitched in his sleep. Ako-chan looked up.\n\nGabu walked back to his shelter.\n\nNobody said anything. Nobody laughed. They just took in the words.\n\nAnd outside, the sky continued to lighten.',
    },
    {
        "ep": 35,
        "title": 'The Anatolian Guard Dog',
        "text": 'The road passed through a wide valley. On a hill above them, a very large dog sat and watched. Its coat was thick and pale. Its eyes were calm. It was a Kangal dog — the kind that guards flocks in the mountains of Anatolia.\n\nThe dog came down slowly. It walked to where the group had stopped. It looked at each of them in turn.\n\nThen it looked at Dango.\n\n"You are very small," it said.\n\nDango stood still.\n\n"But you have good eyes," the Kangal dog continued. "That is what matters in a dog. The eyes. Your eyes are good."\n\nThe Kangal dog looked at the hills for a moment. Then it turned and walked back up.\n\nDango watched it go. His collar turned a steady deep gold.\n\nFor the rest of that day, he walked a little ahead of the group. Not far — just enough to be first. He held his head up. He glanced back once to check that everyone was still there.\n\nThat evening, Ako-chan scratched his ear. "Good day?" she said.\n\nDango pressed his nose against her hand. "Yes," he said. "A very good day."',
    },
    {
        "ep": 36,
        "title": "Gabu's Secret",
        "text": 'The night was quiet. The fire was low. Daru was asleep. Dango was asleep. Obia stood at the far edge of the camp, facing the dark.\n\nGabu came out of his shelter slowly. He walked to where Ako-chan was writing in her diary.\n\n"May I sit with you?" he said.\n\n"Of course," said Ako-chan.\n\nHe sat. For a while, neither of them spoke.\n\nThen Gabu said: "When I came out of my egg, the first thing I saw was sky. Just sky. No one was there."\n\nAko-chan put down her pen.\n\n"I thought that was how things were," he said. "I thought being alone was normal. It was the only way I knew." He looked at his feet. "I am still getting used to this."\n\n"To what?" said Ako-chan.\n\n"To there being others," he said. "To looking and finding someone."\n\nHe was quiet for a moment. "Please don\'t tell Daru," he said. "Not yet."\n\n"I won\'t," said Ako-chan.\n\nShe did not tell him it would be all right. She just sat beside him.\n\nAfter a while, Gabu said: "Thank you for listening."\n\n"Always," said Ako-chan.\n\nThey sat together until the fire went out.',
    },
    {
        "ep": 37,
        "title": 'The Border Storm',
        "text": 'The sky had been clear all day. Then, near the Armenian border, it changed.\n\nClouds came fast — faster than clouds should move. The wind turned cold in minutes. Then rain hit the ground hard and sideways.\n\n"This way," said Obia. It moved quickly and the others followed. A rock overhang gave just enough shelter for all five. They pressed in. Outside, rain came down in white sheets.\n\nDango\'s collar went orange. He pressed against Ako-chan\'s leg.\n\nDaru pulled into his shell. Gabu was already inside his shelter.\n\nObia stood at the edge of the overhang. It watched the storm.\n\n"Obia," said Ako-chan. "Is this a normal storm?"\n\nObia did not turn around. "I do not know," it said.\n\nThe wind pushed rain under the rock. Ako-chan pulled her coat tighter.\n\nObia said, very quietly: "This storm may not have started naturally."\n\nNo one spoke. The rain was very loud.\n\nWhen the storm passed and the night was still again, Ako-chan wrote in her diary: Obia said: this storm may not have started naturally. I wrote it down exactly as it said it.',
    },
    {
        "ep": 38,
        "title": 'Signal Again',
        "text": 'Everyone was asleep. The fire was out. The stars were bright.\n\nObia was awake.\n\nAt two in the morning, something reached its receivers. A signal. The same frequency it had received once before, in February, in the middle of the night when everyone slept. The same pattern. But this time it was stronger. And it felt closer.\n\nObia stood still and received it. The signal lasted a few seconds. Then it stopped.\n\nObia stood looking south for a while.\n\nThen it turned and checked the camp. Dango was asleep with his nose tucked under his tail. Daru was inside his shelter, not moving. Gabu\'s shelter was dark and quiet. Ako-chan had her diary under one hand.\n\nObia did not add the signal to the shared record device.\n\nIt walked to the edge of the camp and stood there. The night was cold. The stars turned slowly. Obia did not move.\n\nWhen Ako-chan woke, Obia said: "Good morning."\n\n"You\'re already up," said Ako-chan.\n\n"Yes," said Obia.\n\nShe looked at it. "Did anything happen in the night?"\n\n"Nothing to report," said Obia.\n\nAko-chan looked at it a moment longer. Then she started the fire.',
    },
    {
        "ep": 39,
        "title": 'The Mountain Road',
        "text": 'The road into Georgia climbed high into the Caucasus mountains. It was steep and uneven. In places the path was very narrow, and on one side the ground dropped away sharply.\n\nDango went first.\n\nHe had always walked beside Ako-chan or behind her. This time he walked in front. When she stepped and the stone shifted under her foot, he was already there — pressing his side against her leg, giving her something to lean on.\n\nShe caught herself. She did not fall.\n\n"Thank you," she said.\n\nDango kept walking. He did not look back. His collar was a steady, calm gold.\n\nIt happened twice more on that road. Each time, Dango was there before she could think to ask.\n\nAt the top of the pass, where the road leveled out, Ako-chan sat and caught her breath. Dango sat beside her.\n\nShe said: "I didn\'t know you could do that."\n\nHe pressed his nose to her knee. He looked out at the valley below.\n\nAko-chan wrote in her diary that night: Dango walked ahead of me on the mountain. He kept me from falling three times. He knew the road. I didn\'t. He was looking after me.',
    },
    {
        "ep": 40,
        "title": 'The Third Signal',
        "text": 'It was late. Everyone was asleep.\n\nObia stood at the edge of the camp. It was still and quiet, the way it always was at night.\n\nThen the signal came.\n\nThe same frequency as before. The first time had been in February — faint, far away. The second time, in Armenia — stronger. Now it was much stronger still. And this time the direction was clear. Not just south. South-southeast. Precise.\n\nObia stood very still.\n\nFor two seconds it did not move at all. Its systems noted this pause. It was not a normal pause.\n\nThen its posture straightened.\n\nIt stood for a long time facing the direction of the signal. Then it turned and looked at the camp. Dango was asleep with his paws folded under him. Gabu\'s shelter was dark. Daru was inside his shelter, still. Ako-chan had one hand resting on her closed diary.\n\nObia did not add the signal to the shared record device.\n\nIt stood at the edge of the camp until dawn, facing south-southeast.\n\nWhen Ako-chan woke, Obia said: "Good morning."\n\nThe stars were still fading. Obia had been awake a long time.',
    },
    {
        "ep": 41,
        "title": 'End of May',
        "text": 'That evening, the mountains were closer. Tomorrow, they would reach the border.\n\nGabu came out of his shelter and sat at the edge of the camp. He looked east at the dark line of the mountains against the sky.\n\nAfter a while, he said: "I did not think we would come this far."\n\nDaru was nearby. He looked up. "I knew we would," he said.\n\nGabu turned to look at him. "Did you?"\n\n"Every day," said Daru. "I woke up and I thought: yes. Today we go further." He tilted his head. "Did you not think that?"\n\nGabu was quiet.\n\n"I thought: maybe," he said. "Every day, I thought maybe."\n\n"And here we are," said Daru.\n\n"Yes," said Gabu. "Here we are."\n\nThey were both quiet for a moment.\n\nThen Daru said: "You are louder than when we first met."\n\nGabu thought about this. "Am I?"\n\n"A little," said Daru.\n\nGabu looked at the mountains. The sky behind them was getting darker. Stars were beginning to show.\n\n"I want to know what is next," said Gabu.\n\nDaru registered surprise. He looked at Gabu for a moment.\n\nThen he grinned. "Now you sound like me," he said.',
    },
]
