STORIES_S1_P02 = [
    {
        "ep": 11,
        "title": 'Through the Tunnel',
        "text": 'The train went into the tunnel and the world went dark.\n\nDango pressed his nose against the window. He stared into the black. He did not bark. He did not move. He just looked.\n\nAko-chan watched him. She had never left England before. The tunnel felt very long. She could hear the train rushing through the dark.\n\nObia sat still on the seat beside her. Its silver head turned slowly toward the window.\n\nThen the dark was gone. Light came flooding in.\n\nGreen fields stretched out on both sides. The sky was a different grey. The trees had a different shape. The soil looked different.\n\nDango lifted his nose from the glass. He sniffed the air. His ears went very high.\n\n"That is France," said Obia quietly.\n\nAko-chan looked out at the rolling fields. Everything looked familiar and different at the same time. She reached into her coat pocket. She felt the small acorn there.\n\n"We are really doing this," she said.\n\nDango gave one short wag of his tail. He was still watching France go past.',
    },
    {
        "ep": 12,
        "title": "Obia's First Invention",
        "text": 'In the morning, Obia placed something on the table.\n\nIt was flat, about the size of a notebook. It had a screen that showed a map of the world. Small dots appeared on the map — each one a place where something strange had happened.\n\n"I made this last night," said Obia. "From parts I found. A broken torch. A cheap radio. Some wire."\n\nAko-chan looked at the dots. There were more than she expected. Some of them were places she had not reported.\n\n"How did you know about these ones?" she asked, pointing.\n\n"I have been collecting data of my own," said Obia. "In addition to what you hear from the animals."\n\nAko-chan studied the map for a long time. The dots were spread across the world. Some were near cities. Some were in the middle of the sea.\n\n"You should carry this," said Obia. "You will use it more than I will."\n\nAko-chan picked it up. It was light.\n\nDango leaned over to sniff it. He decided it was not food and walked away.\n\nAko-chan looked at the dots again. From here, they seemed random. But something about them felt like a pattern she could not yet name.',
    },
    {
        "ep": 13,
        "title": 'Looking Out the Window',
        "text": 'The train went north from Paris. Green-brown fields stretched wide on both sides.\n\nDango had his nose pressed against the glass again. His breath made a small cloud on the window.\n\nAko-chan looked at Obia. Obia was not looking at the window. Its eyes were moving, but not at the view outside.\n\n"Don\'t you want to look at the scenery?" Ako-chan asked.\n\n"I am looking," said Obia.\n\n"But your eyes are not on the window."\n\n"I see from many angles at the same time," said Obia. "The temperature of the air outside. The speed of the train. The shape of the hills. I see all of it. Just not the way you do."\n\nAko-chan thought about that.\n\nShe saw colour and shape. Dango smelled everything. Obia read the world as numbers and patterns.\n\n"So we all see the same things," she said slowly. "But in different ways."\n\n"Yes," said Obia. "That is why the three of us are useful together."\n\nDango pulled away from the window. He had spotted something on the seat. It was a small crumb. He ate it.\n\nOutside, Belgium began.',
    },
    {
        "ep": 14,
        "title": 'The Night Signal',
        "text": 'At two in the morning, the room was very quiet.\n\nAko-chan and Dango were both asleep. Dango made a small sound in his dream.\n\nObia was awake. It was always awake.\n\nSomething was arriving. A signal. Very faint. From far to the south. It came in a pattern: short, pause, long, pause, short, short.\n\nObia listened for a long time.\n\nThe signal was not from any station it knew. It was not from a ship. It was not a normal frequency. But it was regular. Very regular. Something was making it on purpose.\n\nObia opened the record device slowly, so the screen would not wake Ako-chan.\n\nThen it stopped.\n\nIt did not add the signal to the shared record. It saved it somewhere else instead. Somewhere only it could read.\n\nObia sat still in the dark room for a long time. It listened to the signal come and come and come from the south. It did not feel like nothing. It felt like something it could not yet name.\n\nDango made another small sound. His collar glowed orange for just a moment, then faded back to gold.\n\nObia watched him sleep. It did not tell Ako-chan about the signal in the morning.',
    },
    {
        "ep": 15,
        "title": 'The Emotion Collar',
        "text": 'Obia set something down in front of Dango.\n\nIt was a collar. Light and soft, with small rings all along it. The rings had tiny lights inside them.\n\n"This is for you," said Obia. "It shows how you are feeling. Yellow means happy. Gold means calm and content. Orange means worried or afraid."\n\nDango sniffed it. He sat back. He looked at Ako-chan.\n\n"I made it for you," said Obia. "Not for navigation. Just for you."\n\nAko-chan fastened it around his neck carefully.\n\nDango shook his head once. He tried to look at it. He could not see it. He turned in a circle. He still could not see it.\n\nThen something happened. All the rings lit up at once.\n\nYellow. Bright yellow. All of them together.\n\nAko-chan laughed. "I think you like it."\n\nDango stopped turning. He looked up at her with his ears straight.\n\n"Now I can tell when you are happy," she said, "and when you are worried. Even when you try to hide it."\n\nDango glanced at Obia. The collar stayed yellow.\n\nObia said, "You are welcome."\n\nDango turned away. The collar stayed yellow the whole evening.',
    },
    {
        "ep": 16,
        "title": 'The Third Question',
        "text": 'It was snowing. Not the blizzard kind. Just slow, soft flakes falling through still air.\n\nThey had stopped in a small mountain village. A fire was going in the guesthouse. Dango was asleep.\n\nAko-chan sat across from Obia.\n\nShe had asked this question twice before. She had not planned to ask it again. But the snow was quiet and the fire was warm, and the question came back.\n\n"Obia. Where do you come from?"\n\nObia was still for a moment.\n\n"I know you have asked this before," it said.\n\n"I know," said Ako-chan. "I am asking again."\n\nAnother pause.\n\n"When this journey is finished," said Obia, "I will answer that. All of it. Everything I know. I promise."\n\nAko-chan looked at Obia for a long time. The fire made small sounds. Snow touched the window and disappeared.\n\n"All right," she said at last. "I will wait."\n\n"Thank you," said Obia.\n\nShe had heard Obia say many things over the past weeks. But this was the first time it had used the word promise. It felt different from the other times. More certain. More like something it meant.',
    },
    {
        "ep": 17,
        "title": 'One Month On',
        "text": 'The guesthouse had a window that faced west.\n\nAko-chan sat on the window seat as the sun went down. The light was orange and long. The hills were dark.\n\nEngland was somewhere in that direction. Far away. She had been gone for one whole month.\n\nDango climbed up and settled in her lap. He was warm and heavy. She kept one hand on his back.\n\nObia sat across the room. It was not looking at the terminal. It was just sitting.\n\n"One month," said Ako-chan. "I didn\'t think about it until now."\n\n"The time has been full," said Obia.\n\nShe looked at the record device on the table. The dots on the map had multiplied since England. France. Belgium. Amsterdam. Germany. Austria. The Balkans. The south was closer now.\n\nDango made a small sound. He was already mostly asleep.\n\nAko-chan looked at him. Then at Obia.\n\n"We are going to find out what is happening," she said. It was not a question. It was a way of saying it out loud.\n\n"Yes," said Obia.\n\nThe sun finished setting. The room went dark. Three shapes sat in the last of the light: one sleeping dog, one quiet machine, and one girl who had come a long way from home and was not finished yet.',
    },
    {
        "ep": 18,
        "title": 'A Travel Diary',
        "text": 'In a small shop near the market, Ako-chan found a notebook. It was dark blue. The cover was smooth. The pages inside were blank and very white.\n\nShe bought it.\n\nThat evening, sitting on the bed in the guesthouse, she opened it to the first page.\n\nShe wanted to write about the journey. She wanted to write about the anomalies and the animals and the cities. But she found herself thinking about Obia.\n\nShe wrote: I am glad it is here.\n\nThen she stopped.\n\nWhat was Obia? A guide? A traveler? A protector? A mystery?\n\nShe tried again. Obia is like—\n\nNo. That was not right either.\n\nDango was asleep near her feet. Obia was sitting by the window, its silver shape quiet against the dark glass.\n\nAko-chan looked at it for a long time.\n\nShe wrote: I do not know how to describe Obia yet. But I know this: I am glad it is here.\n\nShe read it back. It was not a perfect sentence. But it felt true.\n\nShe closed the notebook. Obia did not turn from the window.\n\nOutside, the city was quiet. The Danube moved past in the dark below.',
    },
    {
        "ep": 19,
        "title": 'Obia Stops',
        "text": 'They were walking through a long street between old buildings. The morning was cold and grey. A cat watched them from a high window.\n\nThen Obia stopped.\n\nIt stopped completely. One foot was raised slightly off the ground. Its head was still. Its eyes did not move.\n\n"Obia?" said Ako-chan.\n\nNothing.\n\nDango looked at Obia. He tilted his head. He walked around it in a slow circle, sniffing.\n\n"Obia?" Ako-chan said again.\n\nStill nothing.\n\nShe counted. One. Two. Three. Four. Five.\n\nOn five, Obia began to walk again. Exactly as before. The raised foot came down. Its head turned slightly. It moved forward.\n\n"Are you all right?" said Ako-chan.\n\n"Yes," said Obia.\n\n"You stopped."\n\n"Yes."\n\nAko-chan walked beside it. She looked at the side of Obia\'s silver face. It looked the same as always.\n\nBut something had happened to her when it stopped. A cold feeling that had nothing to do with the grey morning air.\n\nShe had not known, until that moment, how much she needed Obia to keep walking.\n\nShe did not say this out loud. She put her hand in her coat pocket and felt the acorn there.\n\nThey kept walking.',
    },
    {
        "ep": 20,
        "title": 'The Sea!',
        "text": 'They came over a hill.\n\nBelow them, very blue and very wide, was the sea.\n\nDango saw it at the same moment Ako-chan did. He stopped. His whole body went rigid. His ears were up. His tail was up.\n\nThen he ran.\n\nAko-chan had never seen him run that fast. His short legs were a blur. He went straight down the hill without turning. He went across the flat road. He went across the pale stones.\n\nHe ran to the edge of the water.\n\nA wave came in.\n\nIt hit him in the chest. He sat down. He sat down in the water, which was not what he had planned.\n\nHe stood up. He shook. He looked at the wave. The wave had no feelings about any of this.\n\nDango barked. He barked at the wave. The wave came in again. He barked again.\n\nAko-chan reached the shore, still laughing. She had been laughing since the top of the hill.\n\n"He is very brave," said Obia.\n\nDango barked at the next wave. It was not clear he was winning.\n\nThe sea was the deepest blue Ako-chan had ever seen. Not a winter blue. A warm, clear, real blue.\n\nThey had reached the Adriatic.',
    },
    {
        "ep": 21,
        "title": 'Obia Measures',
        "text": 'The water was very clear close to the shore. Ako-chan could see the pale round pebbles below the surface.\n\nObia walked into the shallows. The water came up over its paws. It crouched down and pressed one paw flat against the surface.\n\nIt was still for a long time.\n\nAko-chan waited.\n\n"Well?" she said after a while.\n\n"Weak," said Obia. "But present. An electrical signal in the water. Below the normal threshold for any instrument."\n\n"Like Amsterdam?"\n\n"Yes. But much larger in scale. Amsterdam was a point. This is spread through the water."\n\nAko-chan crouched at the water\'s edge. "Is it connected? To the February signal? To what you heard at night?"\n\nObia stood up. Water dripped from its paw.\n\n"I am still gathering data," it said.\n\nAko-chan looked at it. She had noticed something over the past weeks. When Obia said I am still gathering data, it did not mean it did not know. It meant it had decided not to say.\n\nShe was getting better at telling the difference.\n\nShe wrote in her diary: Obia knows more than it says. I am almost sure of this now. I do not know what to do about it yet.\n\nThen she closed the diary.',
    },
    {
        "ep": 22,
        "title": "Dango's Pillow",
        "text": "It was a cold night on the coast.\n\nAko-chan woke briefly in the dark. The fire had gone low. The room was quiet.\n\nShe saw Dango. He was not in his usual spot. He was leaning against Obia's side, fast asleep. One paw was hanging over Obia's back leg. His nose was pressed against its silver side.\n\nObia was sitting very still.\n\nIt was awake. Its eyes were open. But it had not moved. It was holding itself still so that Dango could sleep.\n\nAko-chan watched them without moving.\n\nObia looked over at her. It did not speak. She did not speak.\n\nShe lay back down.\n\nShe did not know what it cost Obia to sit still through the night. She did not know if it cost anything at all. She did not know what Obia felt, or if feeling was the right word.\n\nBut she knew what she had seen. She knew that it had stayed.\n\nJust before dawn, she woke again. Obia had moved Dango gently back to his coat. Dango was curled there, still asleep, nose under his tail.\n\nShe wrote in her diary that morning: I saw it. I will not say it out loud. But I saw it.",
    },
]
