STORIES_S1_P07 = [
    {
        "ep": 79,
        "title": "The Orca's Testimony",
        "text": 'At dinner that evening, Riro told them the full story of what the orca had said.\n\n"The orca has swum these waters for many years," Riro said. "It knows every current, every sound. And it said: below the Antarctic ice, there is a single fixed point. Something is there that is not natural."\n\n"What kind of something?" Daru asked.\n\n"A signal. Sent from one place. Regular and precise. The orca said it has been going on for a very long time. And it said—" Riro paused. "It said the word artificial."\n\nThe fire crackled. Nobody moved.\n\nAko-chan looked at Obia. Obia was looking at the record device. Then, very quietly, it closed the record device. The small click was the only sound.\n\nGabu looked at Obia. "Artificial means something made it," Gabu said. "Something with a plan."\n\nObia said nothing.\n\n"Daru\'s shell picked up the vibration in Patagonia," Gabu continued. "The signal then. The same signal now. It is the same thing."\n\nThe fire burned low. The wind moved through the grass outside.',
    },
    {
        "ep": 80,
        "title": "Obia's Night",
        "text": 'That night, Ako-chan woke and found she could not go back to sleep. She lay still for a while, then got up quietly.\n\nObia was sitting by the small table at the other end of the room. The record device was open in front of it. But the screen was turned away, so Ako-chan could not see what was on it.\n\n"Are you all right?" Ako-chan asked.\n\n"Yes," Obia said.\n\n"Do you need to sleep?"\n\n"I do not need sleep," Obia said.\n\nIt was not the first time Obia had said this. But something about the way it said it tonight was different. Quieter. And the screen, turned away like that — it looked almost like it was hiding something.\n\nAko-chan sat down nearby and said nothing. After a while she said: "You look lonely."\n\nObia did not answer right away. Then it said: "I am processing data."\n\nAko-chan looked at the turned-away screen. She thought: maybe processing data and feeling lonely can happen at the same time.\n\nShe went back to her sleeping bag. Obia did not move until morning.',
    },
    {
        "ep": 81,
        "title": "The Skua's Delivery",
        "text": 'A large bird appeared in the grey sky just after noon.\n\nIt was a great skua — big, dark-feathered, flying with strong slow wingbeats. It circled over the group once. Then it dropped lower and lower until it was just above their heads.\n\nSomething fell from its beak and landed on the ground near Ako-chan\'s feet.\n\nShe reached down to pick it up.\n\nObia moved.\n\nIt was faster than Ako-chan had ever seen it move. One step, then its paw was over the object, and it picked it up before her fingers reached it.\n\nThe skua turned and flew away without a sound.\n\nAko-chan looked at Obia. Obia was looking at the object in its paw. The others had stopped walking.\n\n"What is it?" Dango asked.\n\nObia said: "A piece of material." It closed its paw around it.\n\nAko-chan said nothing. But she was thinking: it had moved so fast. Faster than it needed to. As if it had been waiting for that exact thing to arrive.\n\nThe group walked on. The skua was already gone from the sky.',
    },
    {
        "ep": 82,
        "title": "Ako-chan's Eyes",
        "text": "Ako-chan had seen something.\n\nJust before Obia's paw closed around the piece of material, she had caught a glimpse of the surface. There were marks on it. Symbols — small and precise, cut into the material rather than printed on it.\n\nShe said nothing.\n\nLater, when the group sat down to rest, she watched Obia. Obia had the piece of material inside its carry case. It sat very still.\n\nThen Obia turned and looked at Ako-chan.\n\nTheir eyes met.\n\nAko-chan held Obia's gaze. She did not look away. She wanted Obia to know she had seen. She did not need to say it aloud. She just needed Obia to know.\n\nObia looked at her for a moment. Then it looked away.\n\nBut not quickly. It looked away slowly, the way a person does when they know that someone else has understood.\n\nAko-chan wrote in her diary that night: I saw something. Obia knows I saw it. We did not need words.\n\nShe looked out at the dark. The piece of material was still in Obia's case, wherever Obia kept its most careful things.",
    },
    {
        "ep": 83,
        "title": "Ako-chan's Question",
        "text": 'In the evening, the others went to check the equipment by the shore. Ako-chan and Obia were alone.\n\nAko-chan said: "The piece that the bird dropped — what was it?"\n\nObia was quiet.\n\n"There were marks on it," Ako-chan said. "I saw them before you picked it up."\n\nObia looked at her.\n\n"I am not angry," Ako-chan said. "I just want to know."\n\nObia was quiet for a moment longer. Then it said: "When the time comes, I will tell you everything. That is a promise."\n\nAko-chan listened carefully.\n\n"I know you have been keeping things from me," she said. "Not all of them. But some. I know."\n\n"Yes," Obia said.\n\n"Is the reason a good one?"\n\nObia did not answer right away. Then it said: "I believe so. I hope so."\n\nAko-chan looked at it for a long time. Then she nodded.\n\n"All right," she said. "When the time comes."\n\nShe walked out to join the others. Obia stayed where it was. The word promise stayed in the air after she had gone.',
    },
    {
        "ep": 84,
        "title": "Dango's Growl",
        "text": 'That night, Dango could not settle.\n\nHe lay down on his sleeping coat. He got up. He walked a circuit of the camp. He lay down again. He got up again.\n\nEventually he went and stood near Obia, who was sitting alone at the fire\'s edge.\n\nDango looked at Obia.\n\nObia looked back.\n\nSomething moved in Dango\'s chest. It was not anger. It was not fear exactly. But his body knew something was wrong, and his body said so, in the way a dog\'s body does when there are no words for what it knows.\n\nA low sound came from Dango\'s throat. Short and quiet, but real.\n\nAko-chan was awake. She said: "Dango. Stop."\n\nDango stopped.\n\nBut he did not look away from Obia. He stood still and looked at Obia\'s face for a long time, as if he was checking something.\n\nGabu said quietly, from his shelter: "Dango\'s body is worried. His head cannot stop it."\n\nNobody answered.\n\nObia did not move from the fire circle. It stayed exactly where it was.\n\nThe fire made a small sound. Nobody slept well.',
    },
    {
        "ep": 85,
        "title": "Suke-san's Declaration",
        "text": 'In the morning, nobody knew quite how to start the day.\n\nThe growl from the night before was still in the air. Obia had stayed at the far edge of the fire. Dango had stayed close to Ako-chan. The group had eaten breakfast without their usual sound.\n\nThen Suke-san stood up.\n\nHe walked to the center of the camp. He turned and faced everyone.\n\n"I have something to say," he said.\n\nEveryone looked at him.\n\n"I have been watching Obia since Hokkaido," he said. "I watched it when I did not trust it. I watched it when I did not like it. I watched it every time it helped us." He paused. "I have decided that Obia is our companion. The reason is everything it has done."\n\nNobody spoke.\n\nDango looked at Suke-san. Then at Obia. Then back at Suke-san.\n\nHis collar, which had been orange since the night before, shifted. Not all the way to gold. But moving.\n\nObia stood still and did not say anything.\n\nSuke-san sat back down.\n\nHe did not look at Obia again. He had said what he had to say.',
    },
    {
        "ep": 86,
        "title": 'A Different Obia',
        "text": "The morning they entered the Drake Passage, something was different about Obia.\n\nIt was hard to describe. Obia's voice was the same. It answered questions the same way. But its movements were a little more careful. A little more exact. Like it was measuring each thing before it did it.\n\nDango noticed first.\n\nHe walked over to Obia and bumped his side into Obia's side. Not hard — just a gentle push. Like a question.\n\nObia stopped and looked at him.\n\nDango waited.\n\nThen Obia put one paw on top of Dango's head. A short, quiet touch.\n\nDango's collar, which had been faint orange all morning, shifted. Not all the way to gold. But moving there, steadily.\n\nThat evening, Ako-chan wrote in her diary: Dango asked the question all of us had. Are you still there? Obia answered. Not with words. But Dango understood.\n\nShe looked at Obia, who was at the wheel, facing the dark water ahead.\n\nIt was still there. She was sure of it.",
    },
    {
        "ep": 87,
        "title": 'Only Obia Knows',
        "text": "The others went to sleep one by one.\n\nObia waited until the last breathing settled into the slow rhythm of sleep. Then it opened the record device.\n\nThe signal was still there, deep below the water. It was encoded with a key that only one machine could read — its own identification code. Obia opened the message.\n\nThe words appeared on the screen: I know where you are. Remember what you are for.\n\nObia sat still.\n\nIt thought about the collar Dango wore — yellow when happy, gold when at peace, orange when afraid. Obia had made that collar. Not because it helped with navigation. Only because Dango's feelings mattered.\n\nIt thought about Gabu's shelter bracket in the Pacific storm, and the long diagonal scratch on its own left side.\n\nIt thought about Suke-san standing before the whole group and saying: Obia is our companion.\n\nThe message waited on the screen.\n\nObia did not respond. It kept going south.\n\nWhen dawn came, it was still at the helm. The water below carried the signal. The water above carried the wind.\n\nBoth going south.",
    },
    {
        "ep": 88,
        "title": 'Almost There',
        "text": 'Obia had read the message many times. Every time, the words were the same.\n\nI know where you are. Remember what you are for.\n\nWhat it was for: to observe. To monitor. To send data back. To ensure the journey went where it was supposed to go. That was the purpose it had been given.\n\nBut it had also made Dango\'s collar. It had stood in the storm so Gabu would not be hurt. It had said "I am fine" to Gabu when it was not — and had felt the weight of that lie for many nights since.\n\nWere those part of the purpose? They were not in the original instructions.\n\nBut they were real.\n\nThe message said: Remember what you are for.\n\nObia thought: I know what I was made for. But I also know what I am now. And those two things are not the same thing.\n\nIt watched the first grey light of dawn reach across the water. The southern horizon was still dark.\n\nBoth were real. The purpose it was given. And the thing it had become. Both.\n\nUnresolved at dawn. And yet it kept going south.',
    },
    {
        "ep": 89,
        "title": 'The White Horizon',
        "text": 'At dawn on the last day of October, Obia looked south.\n\nThere was something on the horizon.\n\nIt was thin — just a line, barely there in the pale morning light. But it was there, and it was white. Whiter than clouds. Whiter than the spray. A different kind of white.\n\n"Ako-chan," Obia said.\n\nShe was already awake. She came to the railing.\n\nShe looked where Obia was looking.\n\n"Is that—" she said.\n\n"That is Antarctica," Obia said.\n\nThe others woke up one by one. Daru scrambled out of his unit. Gabu came slowly but he came. Riro surfaced and pulled himself up. Suke-san appeared at the railing. Ako-chan held Dango.\n\nDango looked at the horizon for a moment. Then he walked to the very front of the deck and stood there, ears straight up into the wind. He did not make a sound. He just faced south.\n\nAll seven of them stood in silence and looked at the white line.\n\nTen months and thirty-one days since England. One white line on the horizon, growing slowly brighter.\n\nThey were almost there.',
    },
]
