STORIES_S1_P05 = [
    {
        "ep": 50,
        "title": 'Following the Trail',
        "text": 'The line of shells went from rock to rock. Each time they moved forward, the shells were a little newer. The pieces were bright and wet.\n\n"Close," said Obia. "The source is within ten meters."\n\n"Close!" said Daru. He started to move fast. "Close! Let\'s go——"\n\n"Quietly," said Gabu.\n\nDaru stopped. He turned and looked at Gabu. Gabu\'s head was just above the rock surface, watching Daru steadily.\n\nDaru said nothing. He settled back down. His legs were still ready to run, but he stayed still.\n\nAko-chan looked at them both. She had not expected Daru to stop. She had not expected Gabu to speak either.\n\n"Thank you," she said quietly, to Gabu.\n\nGabu gave one slow blink.\n\nThey all moved forward together, very quietly. One careful step at a time. The rocks were wet. The sea came up in small waves around them.\n\nAhead, a long curtain of dark seaweed draped between two big stones.\n\nSomething was behind it.\n\nA small round shape. Dense brown fur. And both tiny paws pressed flat against a small face.\n\nIt was looking straight at them.',
    },
    {
        "ep": 51,
        "title": 'Behind the Kelp',
        "text": 'No one moved.\n\nThe otter sat perfectly still behind the kelp. Both paws were pressed flat against his face. Only his eyes moved, going from one face to the next. He looked at Suke-san. He looked at Dango. He looked at Obia\'s silver body. He looked at the two small tortoises. Then at Ako-chan.\n\nHis fur was very thick and very brown. It was the kind of fur that looked warm just by looking at it.\n\nAko-chan had stopped breathing for a moment.\n\n"Hello," she said quietly. "We heard you were here."\n\nThe otter kept his paws against his face. He looked at Ako-chan for a long time.\n\n"You are a lot of different animals," he said at last.\n\nDango made a very small sound. His tail was still moving, but slowly now.\n\n"Yes," said Ako-chan. "We are."\n\n"The seal told you," said the otter.\n\n"Yes," said Ako-chan.\n\nThe otter looked at them all again. One paw moved slightly against his face. He did not run. He did not hide further into the kelp.\n\nHe sat there, looking at them with dark, careful eyes.\n\n"My name is Riro," he said.',
    },
    {
        "ep": 52,
        "title": "Riro's Assessment",
        "text": 'Riro looked at the group for a long time.\n\nThen he looked at Ako-chan specifically.\n\nHe came out from behind the kelp. He moved slowly, with care. He set each paw down on the wet rock before putting weight on it.\n\nHe stopped in front of Ako-chan. He looked at her hand.\n\nAko-chan held her hand out slowly, palm up. She did not move it.\n\nRiro leaned forward. He sniffed her hand. His small nose went left and right, very carefully. He sniffed for a long time.\n\nNo one said anything.\n\nThen Riro lifted his head.\n\n"You smell like a long journey," he said.\n\n"Yes," said Ako-chan. "A very long one."\n\n"Many places," said Riro. He looked at her hand again. "Many different soils. Ocean too. And other animals."\n\n"That is right," said Ako-chan.\n\nRiro looked at the others. He seemed to be deciding something.\n\n"How long?" he asked.\n\n"Since January," said Ako-chan.\n\nRiro nodded once. This seemed to satisfy him. He pressed his paws against his face again, calmly.\n\nDango watched from a little way back. His tail was going steadily.',
    },
    {
        "ep": 53,
        "title": "Ako-chan's Expression",
        "text": 'Riro had been talking to Daru about urchins. Daru was asking questions. Riro was answering them seriously.\n\nAko-chan had been listening. Then she looked at Riro sitting there with his thick warm fur, both paws pressed against his face between answers.\n\nShe did not decide to pick him up. It just happened.\n\nShe reached over carefully. Riro looked at her but did not pull away. She lifted him.\n\nHe was lighter than she expected. And then she felt the fur.\n\nIt was warmer and softer and denser than anything she had ever held.\n\n"…Oh," she said.\n\nThat was all. Just that one small sound. She stood completely still, holding him.\n\nDango was watching.\n\nHe had been listening to the urchin conversation too. His tail had been going at its usual speed.\n\nThen he saw Ako-chan\'s face.\n\nIt was the face she made when something was a wonderful thing.\n\nDango\'s tail did not stop. But it slowed down. Just a little. He stayed where he was. He did not move away. But something was different now.\n\nHe watched her hold Riro. He stayed quiet.',
    },
    {
        "ep": 54,
        "title": "Riro's Meal",
        "text": 'Riro found a flat rock in the sun. He looked at the sea.\n\n"I am going to eat," he said.\n\nNo one had asked, but he seemed to feel an explanation was needed.\n\nHe dove into the water. He came back with a sea urchin. He set it on the rock, positioned a smooth stone, and struck once. The shell cracked cleanly.\n\nHe ate with great focus. The group watched.\n\nWhen he was done, he looked at the open shell.\n\n"Acceptable," he said. "The current here is cold-water. That gives good flavor. But this one was not from the deep shelf. You can tell from the color." He set the shell down. "The best urchins come from the cold shelf, below twenty meters."\n\n"Near the eastern cliff?" asked Suke-san.\n\nRiro looked at him.\n\n"Yes," said Suke-san. "I know where that current runs along the coast."\n\nRiro looked at Suke-san for a moment.\n\n"You know this coast," said Riro.\n\nIt was not a question. It was recognition.\n\nSuke-san lifted his head slightly. "I live here," he said.\n\nRiro nodded. This was the correct answer.',
    },
    {
        "ep": 55,
        "title": "Riro's Unit",
        "text": 'Obia had been working since early morning.\n\nIt gathered materials from the supply kit. Metal frame. Mesh sides. A water reservoir with a slow-salt feed system. A small pump.\n\nBy late afternoon, it was done.\n\n"This unit keeps the salt level and moisture correct for a sea otter," said Obia. "You can float in it. You can also sleep in it."\n\nRiro looked at the unit. He walked around it once. He pressed one paw against his face and looked at the water inside.\n\nThen he climbed in.\n\nHe settled. He floated slightly in the shallow water. He pressed both paws against his face.\n\n"This is good," he said.\n\n"You can travel with us now," said Ako-chan.\n\nRiro looked at her from inside the unit. "I was alone for a week," he said. "That is long enough."\n\nHe pressed his paws against his face and looked out at the rest of the group.\n\n"Seven," said Obia.\n\n"Seven," said Daru. He sounded very pleased.\n\nDango counted in his head. He looked at Riro in the unit.\n\nSeven. That was right.\n\nHe was not completely sure how he felt about that.',
    },
    {
        "ep": 56,
        "title": 'The Shellfish Ranking',
        "text": '"I will now rank the shellfish of this coast," said Riro.\n\nIt was evening. Everyone was resting near the water\'s edge.\n\n"You do not have to," said Suke-san.\n\nRiro looked at him. "I want to," he said.\n\nHe began with scallops. He explained the difference between the inner muscle and the outer edge. He explained which current produced the best grain. He explained how to open one cleanly without losing the liquid. He explained three separate things about the liquid.\n\nThen he moved to abalone.\n\nDango was half asleep. Suke-san had given up arguing and was watching the sea. Daru was listening with his eyes wide.\n\nTen minutes passed. Then twenty.\n\nRiro was now explaining squid.\n\nGabu had been listening quietly from inside his shell opening. He had not moved. He had not said anything.\n\nAfter thirty minutes, Riro paused to look at the sea.\n\n"I can stop here," he said.\n\n"Please continue," said Gabu.\n\nRiro looked at him.\n\nGabu\'s head was fully out. He was watching Riro steadily.\n\n"You are interested," said Riro.\n\n"Yes," said Gabu.\n\nRiro settled back down. "Then," he said, "I will explain sea urchin grading."',
    },
    {
        "ep": 57,
        "title": "Gabu's Words",
        "text": 'The rain did not stop.\n\nGabu had been quiet all morning. He was at the edge of the shelter, watching the water fall. His shell was dark with moisture.\n\n"Under the olive tree in Greece," he said quietly, "it never got this wet."\n\nNo one said anything. They waited.\n\n"The leaves kept most of the rain off," Gabu said. "There was a place at the base of the trunk where the soil stayed dry. I used to sit there when it rained."\n\n"Do you want to go back?" asked Daru.\n\nGabu was quiet for a moment.\n\n"No," he said.\n\n"Then why mention it?" asked Suke-san.\n\nGabu did not answer straight away. He watched the rain.\n\n"It is still mine," he said at last. "The olive tree. I carry it with me."\n\n"Even here?" asked Ako-chan.\n\n"Especially here," said Gabu.\n\nHe turned and went back into his shelter.\n\nRiro had his paws against his face. He was looking at where Gabu had stood.\n\n"When I was alone on the rocks," said Riro quietly, "I remembered the other otters. It was not the same as being there. But it helped."\n\nNo one asked him anything. He did not say more.\n\nThe rain continued.',
    },
    {
        "ep": 58,
        "title": 'Everyone Decides',
        "text": '"I want to cross the Pacific," said Ako-chan. "I want to go to where the lines meet."\n\nShe said it clearly. Not as a question.\n\n"I will go," said Dango. He had already taken two steps toward the water.\n\n"I will come," said Daru. "I want to know what is there."\n\n"Of course," said Gabu. "There is nothing to think about."\n\nRiro looked toward the south. "The sea is mine," he said. "Tell me when."\n\nEveryone looked at Suke-san.\n\nHe was looking at the sea. His tail was curled. His back was very straight. The wind moved the fur at his ears.\n\n"I will go," he said quietly.\n\nHe paused.\n\n"I will go," he said again.\n\nThe second time was the same words. The same quiet voice. But it was different. The first one was for everyone. The second one was for himself.\n\nAko-chan did not ask why he said it twice.\n\n"Then we are going," she said.\n\nObia was already making notes on the terminal.\n\n"I will begin preparations tonight," it said.\n\nDango was still looking at the water. His tail was going at full speed. He had made his decision. He was happy with it.',
    },
    {
        "ep": 59,
        "title": "Obia's Answer",
        "text": 'Everyone was asleep. The stars were very bright. The sea was dark and calm.\n\nSuke-san could not sleep. He walked up to the deck. Obia was already there.\n\n"You do not sleep," said Suke-san.\n\n"No," said Obia.\n\nThey stood in silence. The water moved slowly.\n\nThen Suke-san said, "Why do you help us? You carry things. You fix things. You stay awake while we sleep. Why?"\n\nObia looked at the sea for a long moment.\n\n"I will tell you in the morning," it said. "I want to say it correctly."\n\nSuke-san looked at Obia. "Fine," he said. They stood together until the sky turned pale.\n\nIn the morning, Suke-san found Obia at the front of the boat.\n\n"Well?" said Suke-san.\n\nObia turned to face him.\n\n"Because it is important," said Obia.\n\nSuke-san waited. Obia said nothing more.\n\n"That is a very short answer."\n\n"It is the true answer."\n\nSuke-san sat down. He thought for a moment. A bird flew over and was gone.\n\n"I understand," he said at last. "That is a reasonable answer."\n\nHe stood up and walked away. After a few steps, he added, "I will still be better at most things."\n\n"That is possible," said Obia.\n\nAko-chan had heard from the doorway. She watched the tip of Suke-san\'s tail. It moved once, very slightly. Then he was gone.',
    },
    {
        "ep": 60,
        "title": 'Before the Storm',
        "text": 'Obia spoke early in the morning.\n\n"The storm will begin tonight. It will be the largest weather system we have crossed. Please take your positions now."\n\nThe deck was quiet.\n\nDango\'s tail dropped. Just a little.\n\nSuke-san saw it. He walked over and stood next to Dango without a word.\n\nRiro came up from the water. She checked the straps on her wetsuit.\n\nDaru went to his spot near the center of the boat. Gabu went to his shelter and pulled the cover down. Ako-chan checked the ropes along the rail.\n\nObia moved to the helm.\n\n"We have prepared well," said Obia. "The boat is ready."\n\n"Are we ready?" Dango asked.\n\n"You are," said Obia.\n\nDango looked at Suke-san. Suke-san was already looking south.\n\nThe sky to the south had turned a deep grey. The wind was picking up. The waves were getting longer.\n\nEveryone was in place.',
    },
    {
        "ep": 61,
        "title": 'Obia Holds',
        "text": "In the worst part of the storm, the bracket on Gabu's shelter cracked.\n\nThe bracket held the shelter to the wall of the boat. When the boat tilted hard, the metal bent. The shelter shifted.\n\nGabu pressed himself flat into the corner. The shelter shifted again.\n\nObia was at the helm. Then Obia was not at the helm.\n\nObia crossed the wet deck in the wind and rain. It put its body between the wall and the shelter and pressed hard.\n\nAnother wave hit. The bracket was broken. Only Obia's body held the shelter in place.\n\nGabu did not speak. He pressed himself flat. He could feel the weight of Obia against the wall.\n\nThen the wave passed. The boat came up. Obia held until the sea calmed a little. Then it went back to the helm.\n\nBy morning, the bracket was repaired.\n\nGabu saw the new metal when the storm ended. He looked at it for a long time.\n\nThen he saw it. On the left side of Obia's body, from the shoulder down, there was a long scratch. Dark and deep against the silver. The wall had marked it.\n\nGabu looked at the scratch for a long time.\n\nThen he put his head back down without speaking. But he knew.",
    },
    {
        "ep": 62,
        "title": 'After the Storm',
        "text": 'The sound stopped.\n\nThe boat moved slowly. The water was grey but flat. The wind was gone.\n\nBelow deck, everyone heard the quiet.\n\nThe door opened. Daru came out first.\n\nHe looked at the deck. He looked at the sky.\n\nThe sky was pink and yellow. The sun was just coming up. There were no clouds anywhere.\n\n"The sky is beautiful!" Daru shouted.\n\nHe did not shout at anyone in particular. He shouted at the whole ocean. His voice went out over the water and slowly disappeared.\n\nThen Suke-san came up. Then Riro. Then Ako-chan, holding Dango close.\n\nNo one said anything.\n\nThey all stood and looked at the sky.\n\nDaru\'s words were still in the air somehow. The sky is beautiful. Everyone had heard them. They were the right words for this moment.\n\nObia stood at the helm. It had been there all night. It was still there now.\n\nThe sun came up. The sea caught the light and turned gold.\n\nEveryone breathed.',
    },
    {
        "ep": 63,
        "title": "Ako-chan's Tears",
        "text": 'Ako-chan did not cry during the storm.\n\nThe next morning, she walked to the front of the boat alone. She sat at the bow. The sea was calm. The sky was very bright. Everything was peaceful.\n\nShe put her face in her hands and cried.\n\nShe did not hear Dango coming. He was quiet when he wanted to be.\n\nHe sat down next to her and did not speak.\n\nAfter a while, Ako-chan looked up. Dango was there, pressed against her side.\n\n"I was scared," she said.\n\nDango did not say anything. He pushed a little harder against her.\n\nAko-chan wiped her face. "I didn\'t want you to see me like this."\n\nDango turned and looked at her.\n\n"I know," she said. "You already knew I was scared."\n\nShe put her arm around him. He was warm.\n\nThey sat at the bow together. The water moved below them, quiet and bright. The sun was warm on their faces.\n\nAfter a long time, Ako-chan said, "Okay. I\'m okay now."\n\nDango wagged his tail.',
    },
]
