STORIES_S1_P06 = [
    {
        "ep": 49,
        "title": "Ecuador",
        "text": "The boat reached South America in the morning. The port was in Ecuador.\n\nThe air was thick and warm. It smelled like green leaves and wet earth and something sweet. Ako-chan breathed it in.\n\nA bird landed near her feet. It had bright red feathers and a sharp yellow beak.\n\n\"You came a long way,\" the bird said.\n\nThe bird spoke Spanish. Ako-chan answered in Spanish. \"We did.\"\n\n\"What are you looking for?\"\n\n\"We are not sure yet. But we are going south.\"\n\nThe bird tilted its head. \"Many things have changed in the south. The animals talk about it.\"\n\nDango ran across the sand. He put his nose to the ground and sniffed. He sniffed the trees. He sniffed the air. Then he sneezed and shook his head.\n\nRiro slipped into the harbour water and came back up again. Gabu stepped slowly off the boat and looked around. Daru climbed straight to the top of the backpack.\n\nSuke-san stood very still and looked at the trees. \"It is different here.\"\n\n\"Yes,\" Obia said. \"But we keep going south.\"\n\nAko-chan touched the acorn in her pocket. They were still heading south.",
    },
    {
        "ep": 50,
        "title": "Seven Colors",
        "text": "In the forest, a bird sat on a low branch just above Ako-chan's head. Its feathers were many colours — green, blue, red, and yellow all at once.\n\n\"Seven colours are coming,\" the bird said.\n\nAko-chan stopped. \"What do you mean?\"\n\n\"Seven colours,\" the bird said again. \"Each one is different.\"\n\nAko-chan opened her notebook. She looked at her friends.\n\nAko-chan — red.\nDango — orange.\nGabu — yellow.\nDaru — green.\nRiro — blue.\nSuke-san — purple.\n\nThat was six. She looked at Obia.\n\nShe held her pen over the page. What colour was Obia?\n\nObia's body was silver. But was silver really a colour?\n\nAko-chan thought for a moment. Then she wrote:\n\n*Silver is not a real colour. It appears when you do not have a colour of your own yet.*\n\nShe closed the notebook.\n\nObia was watching the trees. Obia did not turn around.\n\nDango came and sat beside Ako-chan. His collar glowed orange.\n\n\"What did you write?\" Dango asked.\n\n\"Something I am still thinking about,\" Ako-chan said.",
    },
    {
        "ep": 51,
        "title": "Toward the Islands",
        "text": "They took a small boat from Ecuador. The Galápagos Islands were far away, but the water was already different — bluer, calmer, and very clear. Ako-chan could see the bottom in some places.\n\nRiro stayed in the water the whole time, swimming just below the surface.\n\nA dolphin appeared. It came from the left side and swam beside Riro. The two of them talked in quick, soft sounds that the others could not understand.\n\nThen the dolphin turned and swam away.\n\nRiro came up to the side of the boat. \"The dolphin said something.\"\n\n\"What?\" Ako-chan asked.\n\n\"There is something very old ahead. In the islands. The dolphin has seen it many times. The animals there remember things that most animals have forgotten.\"\n\n\"What kind of thing?\" Obia asked.\n\n\"She did not say exactly.\"\n\nEveryone went quiet. The boat moved on.\n\nIn the distance, dark shapes rose above the water. The first islands.\n\nGabu looked at them for a long time without moving.\n\n\"Old,\" Gabu said quietly. \"I can feel it.\"",
    },
    {
        "ep": 52,
        "title": "One Hundred Years",
        "text": "The giant tortoise moved slowly across the black rock. She was very, very old. Her shell was dark and cracked at the edges. Her neck was long.\n\nShe did not look at anyone else. She came and stopped in front of Gabu.\n\nGabu did not move.\n\n\"How old are you, little one?\" the old tortoise asked.\n\n\"Not very old,\" Gabu said.\n\n\"And what have you done with your time?\"\n\nGabu was quiet.\n\n\"I have been on this island for one hundred and twelve years,\" the old tortoise said. \"I have seen many things come and go. The sea. The rains. Other animals. Ships in the distance.\"\n\nShe stopped speaking.\n\n\"And what did you do?\" Gabu asked. \"In all that time?\"\n\n\"I watched,\" the tortoise said. \"And I was here. That was enough.\"\n\nNo one said anything. Not Dango. Not Riro. Not even Daru. They all stood very still on the black rocks in the sun.\n\nGabu stayed in front of the old tortoise for a long time after that.",
    },
    {
        "ep": 53,
        "title": "Thank You",
        "text": "The Humboldt Current was cold. Ako-chan could see where the water changed — the colour shifted quickly to a deep, dark blue, different from anything they had crossed before.\n\nRiro looked at the sea for a long time without saying anything.\n\nThen, without a word, Riro slipped over the side of the boat.\n\nThe others watched the water. One minute passed. Then two. Then five. The surface was still. Ako-chan began to feel worried.\n\nThen Riro came back up.\n\nRiro floated on the surface for a moment, just breathing. Water ran from the thick fur. Then Riro turned toward the open sea.\n\n\"Thank you,\" Riro said.\n\nIt was not said to anyone on the boat. It was said to the water.\n\n\"What are you thanking?\" Dango asked.\n\nRiro was quiet for a moment. \"The sea. I have been away from cold water for a long time. It feels like home.\"\n\nRiro climbed back into the boat.\n\nAko-chan did not write in her notebook. Some things did not need words.\n\nThe boat moved south, into the cold dark water.",
    },
    {
        "ep": 54,
        "title": "More Signals",
        "text": "They were travelling from Peru toward Patagonia. The coast was long and dry.\n\nObia took out the map device and held it up.\n\nThe screen showed red dots. There were more of them than before.\n\n\"More than last time,\" Ako-chan said.\n\n\"Yes,\" Obia said. \"Every week, there are more. And the closer to the south, the more there are.\"\n\nAko-chan looked at the screen. All the dots pointed in the same direction.\n\nSouth.\n\n\"What are they?\" Suke-san asked.\n\n\"Signals,\" Obia said. \"Something is sending them. Something far to the south.\"\n\n\"Something alive?\" Riro asked.\n\nObia was quiet for a moment. \"I do not know.\"\n\nAko-chan pressed her finger on the part of the screen where the dots were most dense. Right at the far southern edge of the map.\n\nShe pulled her hand back.\n\n\"We are going there,\" she said. It was not a question.\n\n\"Yes,\" Obia said.\n\nNo one said anything more. The coast moved past them, dry and empty.",
    },
    {
        "ep": 55,
        "title": "Under the Ground",
        "text": "The grass in Patagonia was low and dry. The wind blew without stopping. There were no trees.\n\nThey were walking when Daru stopped.\n\nDaru did not say anything. Daru spread all four legs wide and pressed them flat against the ground.\n\n\"Daru?\" Ako-chan said.\n\n\"Something is vibrating,\" Daru said. \"Under the ground. I can feel it through my legs.\"\n\nGabu came and stood still too. \"I feel it as well.\"\n\nObia knelt beside Daru and held the map device flat against the earth. Numbers appeared on the screen. Obia looked at them carefully.\n\n\"Is it regular?\" Ako-chan asked.\n\n\"Very regular,\" Obia said. \"The same pattern. The same interval. Over and over.\"\n\n\"What does that mean?\"\n\nObia looked up. \"I think something is sending this on purpose.\"\n\nIt was the first time Obia had said that.\n\n\"Sending it to who?\" Suke-san asked.\n\nObia put the device away slowly. \"I do not know yet.\"\n\nDaru still had all four legs pressed against the ground. \"It comes from very far below.\"\n\nThe wind blew. Everyone looked south.",
    },
    {
        "ep": 56,
        "title": "A Little Different",
        "text": "That night, Ako-chan watched Obia.\n\nSince they had come south, Obia had been staying up later. Not much — only a little. But Ako-chan noticed.\n\nShe had also noticed something else. When she said Obia's name, there was a very small pause before the answer came. Just half a second. But it had not been there before.\n\n\"Obia,\" she said.\n\n\"Yes.\" A short pause. Just like the others.\n\n\"Are you all right?\"\n\n\"I am all right.\"\n\nAko-chan did not ask again.\n\nShe sat with her notebook on her knees. Dango was asleep beside her, his collar glowing a quiet blue.\n\nShe wrote: *The closer we get to the south, the farther away Obia seems.*\n\nShe stopped. Then she wrote one more line:\n\n*I do not know what to do with that.*\n\nOutside, the wind was blowing across the Patagonian grass. The stars were very bright.\n\nObia was still awake. Ako-chan could hear that.",
    },
    {
        "ep": 57,
        "title": "The Signal at Night",
        "text": "At midnight, everyone was asleep except Obia.\n\nObia sat at the front of the boat, facing south. The stars were bright and the sea was quiet.\n\nThen the signal came.\n\nIt was the same as the others — regular, from the south. But inside the pattern, there was something else. A short code. A series of numbers that Obia had not seen in the other signals.\n\nObia knew this code.\n\nFor a long time, Obia did not move.\n\nThe signal repeated. Then again. Then stopped.\n\nObia looked at the dark water. Then Obia looked at Ako-chan, asleep with her notebook near her hand. At Dango, curled against Ako-chan's side. At Gabu, still and quiet. At Daru. At Riro. At Suke-san.\n\nObia sat for a long time more.\n\nThen, like all the signals before it, Obia kept this one inside. Somewhere that only Obia could reach.\n\nThe sea moved quietly under the boat.\n\nNo one else knew.",
    },
]
