STORIES_S1_P08 = [
    {
        "ep": 90,
        "title": "Dango's Nose — Antarctic Edition",
        "text": 'The next morning, Dango did something unusual.\n\nHe walked to the edge of camp. He pushed both front paws into the snow, deep, until his chin nearly touched the surface. He breathed in. Long and slow. Then again.\n\nAko-chan watched from a few steps away.\n\nDango lifted his head. He looked south-east. He held very still.\n\n"Dango?" said Ako-chan. "What is there?"\n\nDango did not answer. He stood up slowly. Then he began to walk. Not toward the south, where the coordinates pointed. South-east.\n\nAko-chan followed. The others came behind.\n\nHis collar was gold. Not orange — not worried. Gold.\n\nHe walked for a few minutes. Then he stopped and sat down. He looked back at Ako-chan.\n\nShe looked ahead. She could not see anything. Only ice and sky.\n\nBut she had learned to trust him.\n\n"All right," she said. "We will go that way."\n\nSuke-san stepped forward without a word. Obia walked beside him. One by one, they all followed Dango.\n\nAko-chan wrote in her diary: Dango\'s body knew first.\n\nHe was not afraid. He just knew.',
    },
    {
        "ep": 91,
        "title": "Riro's Diving Report",
        "text": 'Riro was gone when Ako-chan woke up.\n\nShe was not worried. She knew where he went when he disappeared before the others were awake.\n\nAn hour later, he came back. He carried something in his hands. He set it on the ice in front of Ako-chan. It was a flat piece of ice, about the size of her hand. Something was carved into it. Lines and numbers.\n\n"A narwhal gave this to me," said Riro. "It waited several days for someone to ask. Narwhals do not give directions easily. They are careful animals."\n\nObia leaned down and studied the carving.\n\n"These are coordinates," it said. "Twelve kilometers south."\n\nRiro pointed. "That way."\n\n"That is the same direction as Dango\'s nose," said Ako-chan.\n\nShe looked at Dango. He was already looking south.\n\n"The narwhal\'s mother and father also knew the sound," said Riro. "It has been there longer than they can remember."\n\nAko-chan thought about what that meant. She looked at the small piece of ice with its careful lines.\n\nTwelve kilometers. Same direction as Dango had walked. Something very old, waiting under the ice.',
    },
    {
        "ep": 92,
        "title": 'A Sound Not from the Wind',
        "text": 'There was no wind.\n\nThere had been no wind since before lunch. The air was perfectly still. The camp was completely quiet.\n\nThen Daru stopped moving.\n\nHe put both hands flat on the ice. He pressed down hard. His eyes went wide.\n\n"Something is going through my shell," he said. "A sound. Very low. Like the vibration in Patagonia — but stronger."\n\n"From which direction?" said Obia.\n\n"I cannot tell," said Daru. "It comes from all below."\n\nGabu raised his head. He turned it very slowly. Left. Right. He held it pointing toward the south.\n\n"From the south," said Gabu. "The signal comes from the south."\n\nObia activated its sensors. Everyone waited.\n\n"Confirmed," said Obia. "An intentional low-frequency transmission. Not natural. Not random. It repeats at a fixed interval."\n\nDaru was still pressing his hands on the ice.\n\n"In Patagonia the sound was quiet," he said. "This is much louder."\n\nGabu kept looking south. "We are closer now."\n\n"Yes," said Obia. "We are much closer."\n\nAko-chan listened. She could not hear the sound herself. But she could see it in Daru\'s face, and in the way Gabu did not look away from the south.',
    },
    {
        "ep": 93,
        "title": 'A Shadow in the Valley',
        "text": 'They went down into the valley together.\n\nThe walls rose on either side. The sound was clearer here — not loud, but steady and low, like a slow pulse.\n\nObia stopped.\n\n"There," it said.\n\nAko-chan looked. At the far end of the valley, something sat perfectly still. It was small and round and dark against the white. It had not moved at all.\n\n"Biological signal," said Obia. "Small. Body temperature is normal."\n\nDango stepped forward. He looked at the small shape, then at Ako-chan. His collar was gold. Not orange. Not worried. Gold.\n\nAko-chan trusted that.\n\n"All right," she said. "Let us go closer."\n\nThey walked forward slowly. The small shape did not move. It did not turn. It did not look at them.\n\nBut somehow Ako-chan felt that it knew they were coming. She did not know why she felt that. She just did.\n\nDango walked beside her. His ears were relaxed. His step was calm.\n\nWhatever was waiting at the end of the valley was not a threat. Dango\'s body was sure of that.\n\nAko-chan kept walking toward it.',
    },
    {
        "ep": 94,
        "title": 'I Have Been Waiting',
        "text": 'The chick stood up.\n\nIt was small, but it stood straight. Its back was perfectly upright. Its flippers hung at its sides. It looked at all of them at once.\n\nThen it spoke.\n\n"I am Pen-san," it said. "I have been waiting for you."\n\nEveryone was quiet.\n\nPen-san looked at Ako-chan. "Your name is Ako-chan."\n\nThen at the dog beside her. "And you are Dango."\n\n"How do you—" Ako-chan started.\n\nPen-san continued. It said each name in turn. Obia. Gabu. Daru. Suke-san. Riro.\n\nAll seven names. All correct.\n\nAko-chan looked at Dango. Dango looked at Ako-chan. She looked at Obia. Obia was very still.\n\n"How do you know our names?" Ako-chan asked.\n\nPen-san blinked for the first time.\n\n"I knew you were coming," it said. "I have known for a long time. I cannot explain it better than that."\n\nIt settled back down onto the ice, perfectly still again.\n\nAll seven of them looked at each other. Then they looked at the small round penguin chick who had been waiting in this valley for them.\n\nNobody said anything for a while.',
    },
    {
        "ep": 95,
        "title": 'Colonel Adelie',
        "text": 'Movement. Behind a blue-grey rock at the edge of the valley.\n\nA small penguin stepped out. It was very small — smaller than any penguin Ako-chan had seen — but the way it moved was not small at all.\n\nIt looked at all seven of them, fast and sharp. One second. Two seconds. Then it had finished.\n\n"Colonel Adelie," it said. "Guard and instructor to Pen-san. I will explain the situation."\n\nIt did not wait for them to answer.\n\n"I have been observing this coast for three months," it said. "I brought Pen-san to this valley to keep it away from the interference of the structure below the ice. Close enough to hear. Far enough to wait properly."\n\n"How did you know we were coming?" Ako-chan asked.\n\n"Narwhals," said the Colonel. "And whales. And seabirds." It looked at her directly. "The whole south has known you were coming. You have been noticed at every step."\n\nAko-chan thought about Riro\'s narwhal, and the orca in October, and the albatross at the Drake Passage.\n\n"That is a long list," said Suke-san.\n\n"Yes," said the Colonel. "You have traveled far.',
    },
    {
        "ep": 96,
        "title": "The Colonel's Briefing",
        "text": 'Colonel Adelie drew lines in the snow with the tip of one flipper.\n\n"Eight kilometers of flat ice from here," it said. "Then an ice ridge. The wind at the ridge is not regular. You must be careful."\n\nIt drew a mark on the line.\n\n"On the other side of the ridge, there is one access shaft. About one meter wide. That is the only way down to the structure."\n\n"What is at the bottom?" asked Ako-chan.\n\n"A structure. Large. Below the ice surface."\n\nObia was very still. Ako-chan could see it comparing the Colonel\'s information to its own scan data. She could see it in the way its eyes moved.\n\n"At the ridge," the Colonel continued, "there is electromagnetic interference. Strong. It will affect some systems." It looked at Obia for one second. Then it continued. "The access point is at two hundred and ten degrees, magnetic south."\n\nObia spoke. "Your data matches my scan exactly."\n\nThe Colonel nodded once. "Good. Then we are in agreement."\n\nAko-chan was writing as fast as she could. She filled half a page.\n\nBeside her, Suke-san had straightened without seeming to notice. His shoulders were back. His chin was up.',
    },
    {
        "ep": 97,
        "title": "The Emperor's Eyes",
        "text": 'One morning, Pen-san crossed the camp and sat beside Ako-chan.\n\nIt had not done this before. It just came and sat. Very close. Its round body pressed gently against her side.\n\nAko-chan went still.\n\nPen-san looked straight ahead. It did not explain itself.\n\nThen it looked up at her.\n\nIts eyes were dark. Very round. Very still. The largest eyes Ako-chan had ever seen. She had noticed them before — everyone had, the first day. But this was different. This was close. This was looking back at her.\n\nShe tried to look away. She could not.\n\nShe tried to think about breakfast. She could not think about breakfast.\n\nShe opened her mouth.\n\n"...Can I hold you?" she said.\n\nThen she stopped. She had not decided to say that. The words had come out before she chose them.\n\nPen-san blinked.\n\n"If you like," it said.\n\nAko-chan picked up Pen-san carefully. Pen-san was warm and round and its down was impossibly soft.\n\nFrom behind her, she heard a very small sound. Like a short breath.\n\nShe looked back.\n\nDango\'s mouth was a little open. His collar had turned orange.\n\n"Ah," he said. Very quietly.\n\nPen-san turned its head to look at Dango. It looked very calm. Very comfortable. Very settled.\n\nDango looked at Pen-san. He looked at Ako-chan. He looked at Pen-san again.',
    },
    {
        "ep": 98,
        "title": "Dango's Resistance",
        "text": 'Ako-chan held Pen-san and walked slowly around the camp.\n\nDango followed.\n\nHe walked in circles around her feet. He tried very hard not to look at Pen-san. He looked at the ice instead. He looked at the sky. He looked at his own front paws.\n\nThen Pen-san looked at him.\n\nThose eyes opened wide again. Dark. Round. Quiet.\n\nDango\'s front left paw moved sideways. He had not meant to move it.\n\nHe stopped. He looked at his paw. He moved it back.\n\nPen-san\'s eyes were still on him.\n\nDango\'s paw moved sideways again.\n\nHe made a sound. It was not a word. Something between no and a sigh.\n\nThen he was pressed against Ako-chan\'s leg. He had not really decided to go there. But there he was.\n\nHis collar was orange. At the very edges, near the clasp, a little gold.\n\nGabu watched from his shelter. "He is losing," he said.\n\nObia stood beside Gabu. "He is trying very hard," it said. "That is different."\n\nGabu was quiet for a moment. "Yes," he said. "That is a fair thing to say.',
    },
    {
        "ep": 99,
        "title": 'The Colonel and Suke-san',
        "text": 'Colonel Adelie came to Suke-san in the afternoon.\n\nIt walked directly to him. No greeting.\n\n"You were on patrol last night," it said.\n\nSuke-san looked at it.\n\n"...You noticed," he said.\n\n"Yes," said the Colonel. "I noticed at midnight. You had already been walking for two hours."\n\nSuke-san did not answer.\n\n"I also noticed," said the Colonel, "that you adjusted your circuit. When the wind shifted at two in the morning, you moved your path to stay upwind of the camp."\n\nSuke-san\'s ears moved very slightly. He looked at the Colonel.\n\nA pause.\n\nThen both of them nodded. At exactly the same moment. A very small nod. Very clean.\n\nThe Colonel looked out toward the ridge to the south.\n\n"I would like to arrange a joint patrol," it said. "Tonight. After the others sleep."\n\n"Yes," said Suke-san.\n\n"Good," said the Colonel. It turned and walked away.\n\nAko-chan had seen the whole exchange from ten steps away. She wrote in her diary later: The Colonel and Suke-san did not need many words. I think they already understood each other from the first moment.',
    },
    {
        "ep": 100,
        "title": "Pen-san's Memory",
        "text": 'Evening. The camp was quiet. Most of the others had gone inside.\n\nPen-san sat beside Ako-chan at the edge of the camp. They both looked south.\n\nPen-san spoke first.\n\n"When I was in the egg," it said, "I could hear the sound."\n\nAko-chan turned to look at it.\n\n"From below," said Pen-san. "Low and steady. It came up through the rock where the egg was kept. It was always there. I did not know it was unusual. I thought all eggs heard a sound like that."\n\n"When did you learn it was unusual?" Ako-chan asked.\n\n"When I hatched," said Pen-san. "The sound was still there. It had been the first thing I heard. After that, I heard wind and birds and the Colonel\'s voice. But the very first thing — the very first — was that sound from below the ice."\n\nIt was quiet for a moment.\n\n"That is why I waited," said Pen-san. "The sound had been there before me. I thought it was right to wait for what was coming next."\n\nAko-chan did not write in her diary right away. She sat with the words for a long time first.',
    },
    {
        "ep": 101,
        "title": 'The Strategy Meeting',
        "text": 'Colonel Adelie drew the terrain in the snow.\n\n"I will now assign roles," it said. It looked at Suke-san.\n\n"East flank."\n\n"Understood," said Suke-san. Immediately. Without hesitation.\n\n"Obia — first in through the access shaft. You have the best sensors."\n\n"Yes," said Obia.\n\n"Daru — with Obia. You will observe and report what you see."\n\nDaru looked very pleased. "What about me?" he started to ask. Then he understood that the Colonel had just answered that question. "Oh. Yes. I understand."\n\n"Riro — undersea approach to the access point."\n\nRiro nodded.\n\n"Gabu — ridge position. Watch the weather."\n\nGabu had opened his mouth to say he was fine at the rear. The Colonel had already moved on. Gabu closed his mouth.\n\n"Ako-chan — center." The Colonel looked at her steadily. "You hear what no one else hears. Use that."\n\nAko-chan wrote the words down before she could forget them.\n\n"Pen-san — with Ako-chan."\n\nPen-san inclined its head. Very slightly. Like an emperor agreeing to terms.\n\nEveryone was in position. The plan was made.',
    },
]
